allowRemediationCommits:
  # Allow individual remediation commits
  # https://github.com/cncf/dco2?#individual
  individual: false
  # Allow third-party remediation commits
  # https://github.com/cncf/dco2?#third-party
  thirdParty: false

require:
  # https://github.com/cncf/dco2?#skipping-sign-off-for-organization-members
  members: false
