# Copyright (c) Codesphere Inc.
# SPDX-License-Identifier: Apache-2.0

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
    - amd64
    - arm64
    - arm
    main: ./cli
    binary: cs
    ldflags:
    - -s -w
    - -X github.com/codesphere-cloud/cs-go/pkg/cs.version={{.Version}}
    - -X github.com/codesphere-cloud/cs-go/pkg/cs.commit={{.Commit}}
    - -X github.com/codesphere-cloud/cs-go/pkg/cs.date={{.Date}}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^devx"
      - "^chore"

archives:
- formats: binary

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
