# Copyright (c) Codesphere Inc.
# SPDX-License-Identifier: Apache-2.0

all: false
dir: '{{.InterfaceDir}}'
force-file-write: true
filename: 'mocks.go'
formatter: gofmt
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
recursive: false
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  github.com/codesphere-cloud/cs-go/cmd:
    interfaces:
      Client:
      Env:
  github.com/codesphere-cloud/cs-go/api/openapi_client:
    config:
      all: true
    interfaces:
  github.com/codesphere-cloud/cs-go/api:
    config:
      all: true
    interfaces:
