// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cs

import (
	"github.com/codesphere-cloud/cs-go/api"
	mock "github.com/stretchr/testify/mock"
	"time"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetWorkspace provides a mock function for the type MockClient
func (_mock *MockClient) GetWorkspace(workspaceId int) (api.Workspace, error) {
	ret := _mock.Called(workspaceId)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspace")
	}

	var r0 api.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (api.Workspace, error)); ok {
		return returnFunc(workspaceId)
	}
	if returnFunc, ok := ret.Get(0).(func(int) api.Workspace); ok {
		r0 = returnFunc(workspaceId)
	} else {
		r0 = ret.Get(0).(api.Workspace)
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(workspaceId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkspace'
type MockClient_GetWorkspace_Call struct {
	*mock.Call
}

// GetWorkspace is a helper method to define mock.On call
//   - workspaceId int
func (_e *MockClient_Expecter) GetWorkspace(workspaceId any) *MockClient_GetWorkspace_Call {
	return &MockClient_GetWorkspace_Call{Call: _e.mock.On("GetWorkspace", workspaceId)}
}

func (_c *MockClient_GetWorkspace_Call) Run(run func(workspaceId int)) *MockClient_GetWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetWorkspace_Call) Return(workspace api.Workspace, err error) *MockClient_GetWorkspace_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *MockClient_GetWorkspace_Call) RunAndReturn(run func(workspaceId int) (api.Workspace, error)) *MockClient_GetWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// ScaleWorkspace provides a mock function for the type MockClient
func (_mock *MockClient) ScaleWorkspace(wsId int, replicas int) error {
	ret := _mock.Called(wsId, replicas)

	if len(ret) == 0 {
		panic("no return value specified for ScaleWorkspace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = returnFunc(wsId, replicas)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_ScaleWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScaleWorkspace'
type MockClient_ScaleWorkspace_Call struct {
	*mock.Call
}

// ScaleWorkspace is a helper method to define mock.On call
//   - wsId int
//   - replicas int
func (_e *MockClient_Expecter) ScaleWorkspace(wsId any, replicas any) *MockClient_ScaleWorkspace_Call {
	return &MockClient_ScaleWorkspace_Call{Call: _e.mock.On("ScaleWorkspace", wsId, replicas)}
}

func (_c *MockClient_ScaleWorkspace_Call) Run(run func(wsId int, replicas int)) *MockClient_ScaleWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ScaleWorkspace_Call) Return(err error) *MockClient_ScaleWorkspace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_ScaleWorkspace_Call) RunAndReturn(run func(wsId int, replicas int) error) *MockClient_ScaleWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForWorkspaceRunning provides a mock function for the type MockClient
func (_mock *MockClient) WaitForWorkspaceRunning(workspace *api.Workspace, timeout time.Duration) error {
	ret := _mock.Called(workspace, timeout)

	if len(ret) == 0 {
		panic("no return value specified for WaitForWorkspaceRunning")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*api.Workspace, time.Duration) error); ok {
		r0 = returnFunc(workspace, timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_WaitForWorkspaceRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForWorkspaceRunning'
type MockClient_WaitForWorkspaceRunning_Call struct {
	*mock.Call
}

// WaitForWorkspaceRunning is a helper method to define mock.On call
//   - workspace *api.Workspace
//   - timeout time.Duration
func (_e *MockClient_Expecter) WaitForWorkspaceRunning(workspace any, timeout any) *MockClient_WaitForWorkspaceRunning_Call {
	return &MockClient_WaitForWorkspaceRunning_Call{Call: _e.mock.On("WaitForWorkspaceRunning", workspace, timeout)}
}

func (_c *MockClient_WaitForWorkspaceRunning_Call) Run(run func(workspace *api.Workspace, timeout time.Duration)) *MockClient_WaitForWorkspaceRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *api.Workspace
		if args[0] != nil {
			arg0 = args[0].(*api.Workspace)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_WaitForWorkspaceRunning_Call) Return(err error) *MockClient_WaitForWorkspaceRunning_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_WaitForWorkspaceRunning_Call) RunAndReturn(run func(workspace *api.Workspace, timeout time.Duration) error) *MockClient_WaitForWorkspaceRunning_Call {
	_c.Call.Return(run)
	return _c
}

// WorkspaceStatus provides a mock function for the type MockClient
func (_mock *MockClient) WorkspaceStatus(workspaceId int) (*api.WorkspaceStatus, error) {
	ret := _mock.Called(workspaceId)

	if len(ret) == 0 {
		panic("no return value specified for WorkspaceStatus")
	}

	var r0 *api.WorkspaceStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*api.WorkspaceStatus, error)); ok {
		return returnFunc(workspaceId)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *api.WorkspaceStatus); ok {
		r0 = returnFunc(workspaceId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.WorkspaceStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(workspaceId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_WorkspaceStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorkspaceStatus'
type MockClient_WorkspaceStatus_Call struct {
	*mock.Call
}

// WorkspaceStatus is a helper method to define mock.On call
//   - workspaceId int
func (_e *MockClient_Expecter) WorkspaceStatus(workspaceId any) *MockClient_WorkspaceStatus_Call {
	return &MockClient_WorkspaceStatus_Call{Call: _e.mock.On("WorkspaceStatus", workspaceId)}
}

func (_c *MockClient_WorkspaceStatus_Call) Run(run func(workspaceId int)) *MockClient_WorkspaceStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_WorkspaceStatus_Call) Return(workspaceStatus *api.WorkspaceStatus, err error) *MockClient_WorkspaceStatus_Call {
	_c.Call.Return(workspaceStatus, err)
	return _c
}

func (_c *MockClient_WorkspaceStatus_Call) RunAndReturn(run func(workspaceId int) (*api.WorkspaceStatus, error)) *MockClient_WorkspaceStatus_Call {
	_c.Call.Return(run)
	return _c
}
