// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

type VaultAPI interface {

	/*
		VaultDeleteWorkspaceSecrets deleteWorkspaceSecrets

		Delete secrets in the vault for a given workspace

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param teamId
		@param workspaceId
		@return ApiVaultDeleteWorkspaceSecretsRequest
	*/
	VaultDeleteWorkspaceSecrets(ctx context.Context, teamId float32, workspaceId float32) ApiVaultDeleteWorkspaceSecretsRequest

	// VaultDeleteWorkspaceSecretsExecute executes the request
	VaultDeleteWorkspaceSecretsExecute(r ApiVaultDeleteWorkspaceSecretsRequest) (*http.Response, error)

	/*
		VaultListWorkspaceSecrets listWorkspaceSecrets

		List secrets in the vault for a given workspace

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param teamId
		@param workspaceId
		@return ApiVaultListWorkspaceSecretsRequest
	*/
	VaultListWorkspaceSecrets(ctx context.Context, teamId float32, workspaceId float32) ApiVaultListWorkspaceSecretsRequest

	// VaultListWorkspaceSecretsExecute executes the request
	//  @return []string
	VaultListWorkspaceSecretsExecute(r ApiVaultListWorkspaceSecretsRequest) ([]string, *http.Response, error)

	/*
		VaultStoreWorkspaceSecrets storeWorkspaceSecrets

		Store secrets in the vault for a given workspace

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param teamId
		@param workspaceId
		@return ApiVaultStoreWorkspaceSecretsRequest
	*/
	VaultStoreWorkspaceSecrets(ctx context.Context, teamId float32, workspaceId float32) ApiVaultStoreWorkspaceSecretsRequest

	// VaultStoreWorkspaceSecretsExecute executes the request
	//  @return map[string]interface{}
	VaultStoreWorkspaceSecretsExecute(r ApiVaultStoreWorkspaceSecretsRequest) (map[string]interface{}, *http.Response, error)
}

// VaultAPIService VaultAPI service
type VaultAPIService service

type ApiVaultDeleteWorkspaceSecretsRequest struct {
	ctx         context.Context
	ApiService  VaultAPI
	teamId      float32
	workspaceId float32
	requestBody *[]string
}

func (r ApiVaultDeleteWorkspaceSecretsRequest) RequestBody(requestBody []string) ApiVaultDeleteWorkspaceSecretsRequest {
	r.requestBody = &requestBody
	return r
}

func (r ApiVaultDeleteWorkspaceSecretsRequest) Execute() (*http.Response, error) {
	return r.ApiService.VaultDeleteWorkspaceSecretsExecute(r)
}

/*
VaultDeleteWorkspaceSecrets deleteWorkspaceSecrets

Delete secrets in the vault for a given workspace

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param teamId
	@param workspaceId
	@return ApiVaultDeleteWorkspaceSecretsRequest
*/
func (a *VaultAPIService) VaultDeleteWorkspaceSecrets(ctx context.Context, teamId float32, workspaceId float32) ApiVaultDeleteWorkspaceSecretsRequest {
	return ApiVaultDeleteWorkspaceSecretsRequest{
		ApiService:  a,
		ctx:         ctx,
		teamId:      teamId,
		workspaceId: workspaceId,
	}
}

// Execute executes the request
func (a *VaultAPIService) VaultDeleteWorkspaceSecretsExecute(r ApiVaultDeleteWorkspaceSecretsRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VaultAPIService.VaultDeleteWorkspaceSecrets")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/vault/teams/{teamId}/workspaces/{workspaceId}"
	localVarPath = strings.Replace(localVarPath, "{"+"teamId"+"}", url.PathEscape(parameterValueToString(r.teamId, "teamId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"workspaceId"+"}", url.PathEscape(parameterValueToString(r.workspaceId, "workspaceId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.requestBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v DomainsGetDomain400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v DomainsGetDomain401Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiVaultListWorkspaceSecretsRequest struct {
	ctx         context.Context
	ApiService  VaultAPI
	teamId      float32
	workspaceId float32
}

func (r ApiVaultListWorkspaceSecretsRequest) Execute() ([]string, *http.Response, error) {
	return r.ApiService.VaultListWorkspaceSecretsExecute(r)
}

/*
VaultListWorkspaceSecrets listWorkspaceSecrets

List secrets in the vault for a given workspace

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param teamId
	@param workspaceId
	@return ApiVaultListWorkspaceSecretsRequest
*/
func (a *VaultAPIService) VaultListWorkspaceSecrets(ctx context.Context, teamId float32, workspaceId float32) ApiVaultListWorkspaceSecretsRequest {
	return ApiVaultListWorkspaceSecretsRequest{
		ApiService:  a,
		ctx:         ctx,
		teamId:      teamId,
		workspaceId: workspaceId,
	}
}

// Execute executes the request
//
//	@return []string
func (a *VaultAPIService) VaultListWorkspaceSecretsExecute(r ApiVaultListWorkspaceSecretsRequest) ([]string, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue []string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VaultAPIService.VaultListWorkspaceSecrets")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/vault/teams/{teamId}/workspaces/{workspaceId}/keys"
	localVarPath = strings.Replace(localVarPath, "{"+"teamId"+"}", url.PathEscape(parameterValueToString(r.teamId, "teamId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"workspaceId"+"}", url.PathEscape(parameterValueToString(r.workspaceId, "workspaceId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v DomainsGetDomain400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v DomainsGetDomain401Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiVaultStoreWorkspaceSecretsRequest struct {
	ctx         context.Context
	ApiService  VaultAPI
	teamId      float32
	workspaceId float32
	body        *map[string]interface{}
}

func (r ApiVaultStoreWorkspaceSecretsRequest) Body(body map[string]interface{}) ApiVaultStoreWorkspaceSecretsRequest {
	r.body = &body
	return r
}

func (r ApiVaultStoreWorkspaceSecretsRequest) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.VaultStoreWorkspaceSecretsExecute(r)
}

/*
VaultStoreWorkspaceSecrets storeWorkspaceSecrets

Store secrets in the vault for a given workspace

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param teamId
	@param workspaceId
	@return ApiVaultStoreWorkspaceSecretsRequest
*/
func (a *VaultAPIService) VaultStoreWorkspaceSecrets(ctx context.Context, teamId float32, workspaceId float32) ApiVaultStoreWorkspaceSecretsRequest {
	return ApiVaultStoreWorkspaceSecretsRequest{
		ApiService:  a,
		ctx:         ctx,
		teamId:      teamId,
		workspaceId: workspaceId,
	}
}

// Execute executes the request
//
//	@return map[string]interface{}
func (a *VaultAPIService) VaultStoreWorkspaceSecretsExecute(r ApiVaultStoreWorkspaceSecretsRequest) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VaultAPIService.VaultStoreWorkspaceSecrets")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/vault/teams/{teamId}/workspaces/{workspaceId}"
	localVarPath = strings.Replace(localVarPath, "{"+"teamId"+"}", url.PathEscape(parameterValueToString(r.teamId, "teamId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"workspaceId"+"}", url.PathEscape(parameterValueToString(r.workspaceId, "workspaceId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v DomainsGetDomain400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v DomainsGetDomain401Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
