// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


package openapi_client

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)


type UsageAPI interface {

	/*
	UsageGetLandscapeServiceEvents getLandscapeServiceEvents

	Returns Audit-Events for a specific Landscape Service.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param teamId
	@param resourceId
	@return ApiUsageGetLandscapeServiceEventsRequest
	*/
	UsageGetLandscapeServiceEvents(ctx context.Context, teamId float32, resourceId string) ApiUsageGetLandscapeServiceEventsRequest

	// UsageGetLandscapeServiceEventsExecute executes the request
	//  @return UsageGetLandscapeServiceEvents200Response
	UsageGetLandscapeServiceEventsExecute(r ApiUsageGetLandscapeServiceEventsRequest) (*UsageGetLandscapeServiceEvents200Response, *http.Response, error)

	/*
	UsageGetUsageSummaryLandscape getUsageSummaryLandscape

	Get the usage summary of all Landscape Services for a team over the specified time period.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param teamId
	@return ApiUsageGetUsageSummaryLandscapeRequest
	*/
	UsageGetUsageSummaryLandscape(ctx context.Context, teamId float32) ApiUsageGetUsageSummaryLandscapeRequest

	// UsageGetUsageSummaryLandscapeExecute executes the request
	//  @return UsageGetUsageSummaryLandscape200Response
	UsageGetUsageSummaryLandscapeExecute(r ApiUsageGetUsageSummaryLandscapeRequest) (*UsageGetUsageSummaryLandscape200Response, *http.Response, error)
}

// UsageAPIService UsageAPI service
type UsageAPIService service

type ApiUsageGetLandscapeServiceEventsRequest struct {
	ctx context.Context
	ApiService UsageAPI
	teamId float32
	resourceId string
	beginDate *time.Time
	endDate *time.Time
	limit *int
	offset *int
}

func (r ApiUsageGetLandscapeServiceEventsRequest) BeginDate(beginDate time.Time) ApiUsageGetLandscapeServiceEventsRequest {
	r.beginDate = &beginDate
	return r
}

func (r ApiUsageGetLandscapeServiceEventsRequest) EndDate(endDate time.Time) ApiUsageGetLandscapeServiceEventsRequest {
	r.endDate = &endDate
	return r
}

func (r ApiUsageGetLandscapeServiceEventsRequest) Limit(limit int) ApiUsageGetLandscapeServiceEventsRequest {
	r.limit = &limit
	return r
}

func (r ApiUsageGetLandscapeServiceEventsRequest) Offset(offset int) ApiUsageGetLandscapeServiceEventsRequest {
	r.offset = &offset
	return r
}

func (r ApiUsageGetLandscapeServiceEventsRequest) Execute() (*UsageGetLandscapeServiceEvents200Response, *http.Response, error) {
	return r.ApiService.UsageGetLandscapeServiceEventsExecute(r)
}

/*
UsageGetLandscapeServiceEvents getLandscapeServiceEvents

Returns Audit-Events for a specific Landscape Service.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param teamId
 @param resourceId
 @return ApiUsageGetLandscapeServiceEventsRequest
*/
func (a *UsageAPIService) UsageGetLandscapeServiceEvents(ctx context.Context, teamId float32, resourceId string) ApiUsageGetLandscapeServiceEventsRequest {
	return ApiUsageGetLandscapeServiceEventsRequest{
		ApiService: a,
		ctx: ctx,
		teamId: teamId,
		resourceId: resourceId,
	}
}

// Execute executes the request
//  @return UsageGetLandscapeServiceEvents200Response
func (a *UsageAPIService) UsageGetLandscapeServiceEventsExecute(r ApiUsageGetLandscapeServiceEventsRequest) (*UsageGetLandscapeServiceEvents200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *UsageGetLandscapeServiceEvents200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "UsageAPIService.UsageGetLandscapeServiceEvents")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/usage/teams/{teamId}/resources/landscape-service/{resourceId}/events"
	localVarPath = strings.Replace(localVarPath, "{"+"teamId"+"}", url.PathEscape(parameterValueToString(r.teamId, "teamId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"resourceId"+"}", url.PathEscape(parameterValueToString(r.resourceId, "resourceId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.beginDate == nil {
		return localVarReturnValue, nil, reportError("beginDate is required and must be specified")
	}
	if r.endDate == nil {
		return localVarReturnValue, nil, reportError("endDate is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "beginDate", r.beginDate, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "endDate", r.endDate, "form", "")
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	} else {
        var defaultValue int = 25
        parameterAddToHeaderOrQuery(localVarQueryParams, "limit", defaultValue, "form", "")
        r.limit = &defaultValue
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	} else {
        var defaultValue int = 0
        parameterAddToHeaderOrQuery(localVarQueryParams, "offset", defaultValue, "form", "")
        r.offset = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v DomainsGetDomain400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v DomainsGetDomain401Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUsageGetUsageSummaryLandscapeRequest struct {
	ctx context.Context
	ApiService UsageAPI
	teamId float32
	beginDate *time.Time
	endDate *time.Time
	limit *int
	offset *int
}

func (r ApiUsageGetUsageSummaryLandscapeRequest) BeginDate(beginDate time.Time) ApiUsageGetUsageSummaryLandscapeRequest {
	r.beginDate = &beginDate
	return r
}

func (r ApiUsageGetUsageSummaryLandscapeRequest) EndDate(endDate time.Time) ApiUsageGetUsageSummaryLandscapeRequest {
	r.endDate = &endDate
	return r
}

func (r ApiUsageGetUsageSummaryLandscapeRequest) Limit(limit int) ApiUsageGetUsageSummaryLandscapeRequest {
	r.limit = &limit
	return r
}

func (r ApiUsageGetUsageSummaryLandscapeRequest) Offset(offset int) ApiUsageGetUsageSummaryLandscapeRequest {
	r.offset = &offset
	return r
}

func (r ApiUsageGetUsageSummaryLandscapeRequest) Execute() (*UsageGetUsageSummaryLandscape200Response, *http.Response, error) {
	return r.ApiService.UsageGetUsageSummaryLandscapeExecute(r)
}

/*
UsageGetUsageSummaryLandscape getUsageSummaryLandscape

Get the usage summary of all Landscape Services for a team over the specified time period.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param teamId
 @return ApiUsageGetUsageSummaryLandscapeRequest
*/
func (a *UsageAPIService) UsageGetUsageSummaryLandscape(ctx context.Context, teamId float32) ApiUsageGetUsageSummaryLandscapeRequest {
	return ApiUsageGetUsageSummaryLandscapeRequest{
		ApiService: a,
		ctx: ctx,
		teamId: teamId,
	}
}

// Execute executes the request
//  @return UsageGetUsageSummaryLandscape200Response
func (a *UsageAPIService) UsageGetUsageSummaryLandscapeExecute(r ApiUsageGetUsageSummaryLandscapeRequest) (*UsageGetUsageSummaryLandscape200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *UsageGetUsageSummaryLandscape200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "UsageAPIService.UsageGetUsageSummaryLandscape")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/usage/teams/{teamId}/resources/landscape-service/summary"
	localVarPath = strings.Replace(localVarPath, "{"+"teamId"+"}", url.PathEscape(parameterValueToString(r.teamId, "teamId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.beginDate == nil {
		return localVarReturnValue, nil, reportError("beginDate is required and must be specified")
	}
	if r.endDate == nil {
		return localVarReturnValue, nil, reportError("endDate is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "beginDate", r.beginDate, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "endDate", r.endDate, "form", "")
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	} else {
        var defaultValue int = 25
        parameterAddToHeaderOrQuery(localVarQueryParams, "limit", defaultValue, "form", "")
        r.limit = &defaultValue
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	} else {
        var defaultValue int = 0
        parameterAddToHeaderOrQuery(localVarQueryParams, "offset", defaultValue, "form", "")
        r.offset = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v DomainsGetDomain400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v DomainsGetDomain401Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
