// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


package openapi_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DomainsGetDomain400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainsGetDomain400Response{}

// DomainsGetDomain400Response struct for DomainsGetDomain400Response
type DomainsGetDomain400Response struct {
	Status int `json:"status"`
	Title string `json:"title"`
	Detail *string `json:"detail,omitempty"`
	TraceId string `json:"traceId"`
}

type _DomainsGetDomain400Response DomainsGetDomain400Response

// NewDomainsGetDomain400Response instantiates a new DomainsGetDomain400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainsGetDomain400Response(status int, title string, traceId string) *DomainsGetDomain400Response {
	this := DomainsGetDomain400Response{}
	this.Status = status
	this.Title = title
	this.TraceId = traceId
	return &this
}

// NewDomainsGetDomain400ResponseWithDefaults instantiates a new DomainsGetDomain400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainsGetDomain400ResponseWithDefaults() *DomainsGetDomain400Response {
	this := DomainsGetDomain400Response{}
	return &this
}

// GetStatus returns the Status field value
func (o *DomainsGetDomain400Response) GetStatus() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DomainsGetDomain400Response) GetStatusOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DomainsGetDomain400Response) SetStatus(v int) {
	o.Status = v
}

// GetTitle returns the Title field value
func (o *DomainsGetDomain400Response) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *DomainsGetDomain400Response) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *DomainsGetDomain400Response) SetTitle(v string) {
	o.Title = v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *DomainsGetDomain400Response) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainsGetDomain400Response) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *DomainsGetDomain400Response) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *DomainsGetDomain400Response) SetDetail(v string) {
	o.Detail = &v
}

// GetTraceId returns the TraceId field value
func (o *DomainsGetDomain400Response) GetTraceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TraceId
}

// GetTraceIdOk returns a tuple with the TraceId field value
// and a boolean to check if the value has been set.
func (o *DomainsGetDomain400Response) GetTraceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TraceId, true
}

// SetTraceId sets field value
func (o *DomainsGetDomain400Response) SetTraceId(v string) {
	o.TraceId = v
}

func (o DomainsGetDomain400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainsGetDomain400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["title"] = o.Title
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	toSerialize["traceId"] = o.TraceId
	return toSerialize, nil
}

func (o *DomainsGetDomain400Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"title",
		"traceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainsGetDomain400Response := _DomainsGetDomain400Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDomainsGetDomain400Response)

	if err != nil {
		return err
	}

	*o = DomainsGetDomain400Response(varDomainsGetDomain400Response)

	return err
}

type NullableDomainsGetDomain400Response struct {
	value *DomainsGetDomain400Response
	isSet bool
}

func (v NullableDomainsGetDomain400Response) Get() *DomainsGetDomain400Response {
	return v.value
}

func (v *NullableDomainsGetDomain400Response) Set(val *DomainsGetDomain400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainsGetDomain400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainsGetDomain400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainsGetDomain400Response(val *DomainsGetDomain400Response) *NullableDomainsGetDomain400Response {
	return &NullableDomainsGetDomain400Response{value: val, isSet: true}
}

func (v NullableDomainsGetDomain400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainsGetDomain400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

