// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the SshListPublicKeys200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SshListPublicKeys200ResponseInner{}

// SshListPublicKeys200ResponseInner struct for SshListPublicKeys200ResponseInner
type SshListPublicKeys200ResponseInner struct {
	PublicKey            string    `json:"publicKey"`
	PublicKeyFingerprint string    `json:"publicKeyFingerprint"`
	Title                string    `json:"title"`
	CreatedAt            time.Time `json:"createdAt"`
}

type _SshListPublicKeys200ResponseInner SshListPublicKeys200ResponseInner

// NewSshListPublicKeys200ResponseInner instantiates a new SshListPublicKeys200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSshListPublicKeys200ResponseInner(publicKey string, publicKeyFingerprint string, title string, createdAt time.Time) *SshListPublicKeys200ResponseInner {
	this := SshListPublicKeys200ResponseInner{}
	this.PublicKey = publicKey
	this.PublicKeyFingerprint = publicKeyFingerprint
	this.Title = title
	this.CreatedAt = createdAt
	return &this
}

// NewSshListPublicKeys200ResponseInnerWithDefaults instantiates a new SshListPublicKeys200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSshListPublicKeys200ResponseInnerWithDefaults() *SshListPublicKeys200ResponseInner {
	this := SshListPublicKeys200ResponseInner{}
	return &this
}

// GetPublicKey returns the PublicKey field value
func (o *SshListPublicKeys200ResponseInner) GetPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value
// and a boolean to check if the value has been set.
func (o *SshListPublicKeys200ResponseInner) GetPublicKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicKey, true
}

// SetPublicKey sets field value
func (o *SshListPublicKeys200ResponseInner) SetPublicKey(v string) {
	o.PublicKey = v
}

// GetPublicKeyFingerprint returns the PublicKeyFingerprint field value
func (o *SshListPublicKeys200ResponseInner) GetPublicKeyFingerprint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicKeyFingerprint
}

// GetPublicKeyFingerprintOk returns a tuple with the PublicKeyFingerprint field value
// and a boolean to check if the value has been set.
func (o *SshListPublicKeys200ResponseInner) GetPublicKeyFingerprintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicKeyFingerprint, true
}

// SetPublicKeyFingerprint sets field value
func (o *SshListPublicKeys200ResponseInner) SetPublicKeyFingerprint(v string) {
	o.PublicKeyFingerprint = v
}

// GetTitle returns the Title field value
func (o *SshListPublicKeys200ResponseInner) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *SshListPublicKeys200ResponseInner) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *SshListPublicKeys200ResponseInner) SetTitle(v string) {
	o.Title = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *SshListPublicKeys200ResponseInner) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SshListPublicKeys200ResponseInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SshListPublicKeys200ResponseInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o SshListPublicKeys200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SshListPublicKeys200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["publicKey"] = o.PublicKey
	toSerialize["publicKeyFingerprint"] = o.PublicKeyFingerprint
	toSerialize["title"] = o.Title
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

func (o *SshListPublicKeys200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"publicKey",
		"publicKeyFingerprint",
		"title",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSshListPublicKeys200ResponseInner := _SshListPublicKeys200ResponseInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSshListPublicKeys200ResponseInner)

	if err != nil {
		return err
	}

	*o = SshListPublicKeys200ResponseInner(varSshListPublicKeys200ResponseInner)

	return err
}

type NullableSshListPublicKeys200ResponseInner struct {
	value *SshListPublicKeys200ResponseInner
	isSet bool
}

func (v NullableSshListPublicKeys200ResponseInner) Get() *SshListPublicKeys200ResponseInner {
	return v.value
}

func (v *NullableSshListPublicKeys200ResponseInner) Set(val *SshListPublicKeys200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSshListPublicKeys200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSshListPublicKeys200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSshListPublicKeys200ResponseInner(val *SshListPublicKeys200ResponseInner) *NullableSshListPublicKeys200ResponseInner {
	return &NullableSshListPublicKeys200ResponseInner{value: val, isSet: true}
}

func (v NullableSshListPublicKeys200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSshListPublicKeys200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
