// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WorkspacesListEnvVars200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspacesListEnvVars200ResponseInner{}

// WorkspacesListEnvVars200ResponseInner struct for WorkspacesListEnvVars200ResponseInner
type WorkspacesListEnvVars200ResponseInner struct {
	Name  string `json:"name" validate:"regexp=^[A-Za-z_][A-Za-z0-9_.-]*$"`
	Value string `json:"value"`
}

type _WorkspacesListEnvVars200ResponseInner WorkspacesListEnvVars200ResponseInner

// NewWorkspacesListEnvVars200ResponseInner instantiates a new WorkspacesListEnvVars200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspacesListEnvVars200ResponseInner(name string, value string) *WorkspacesListEnvVars200ResponseInner {
	this := WorkspacesListEnvVars200ResponseInner{}
	this.Name = name
	this.Value = value
	return &this
}

// NewWorkspacesListEnvVars200ResponseInnerWithDefaults instantiates a new WorkspacesListEnvVars200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspacesListEnvVars200ResponseInnerWithDefaults() *WorkspacesListEnvVars200ResponseInner {
	this := WorkspacesListEnvVars200ResponseInner{}
	return &this
}

// GetName returns the Name field value
func (o *WorkspacesListEnvVars200ResponseInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WorkspacesListEnvVars200ResponseInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WorkspacesListEnvVars200ResponseInner) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *WorkspacesListEnvVars200ResponseInner) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *WorkspacesListEnvVars200ResponseInner) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *WorkspacesListEnvVars200ResponseInner) SetValue(v string) {
	o.Value = v
}

func (o WorkspacesListEnvVars200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspacesListEnvVars200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *WorkspacesListEnvVars200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkspacesListEnvVars200ResponseInner := _WorkspacesListEnvVars200ResponseInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkspacesListEnvVars200ResponseInner)

	if err != nil {
		return err
	}

	*o = WorkspacesListEnvVars200ResponseInner(varWorkspacesListEnvVars200ResponseInner)

	return err
}

type NullableWorkspacesListEnvVars200ResponseInner struct {
	value *WorkspacesListEnvVars200ResponseInner
	isSet bool
}

func (v NullableWorkspacesListEnvVars200ResponseInner) Get() *WorkspacesListEnvVars200ResponseInner {
	return v.value
}

func (v *NullableWorkspacesListEnvVars200ResponseInner) Set(val *WorkspacesListEnvVars200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspacesListEnvVars200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspacesListEnvVars200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspacesListEnvVars200ResponseInner(val *WorkspacesListEnvVars200ResponseInner) *NullableWorkspacesListEnvVars200ResponseInner {
	return &NullableWorkspacesListEnvVars200ResponseInner{value: val, isSet: true}
}

func (v NullableWorkspacesListEnvVars200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspacesListEnvVars200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
