/*
Codesphere Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the DomainsGetDomain200ResponseCustomConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainsGetDomain200ResponseCustomConfig{}

// DomainsGetDomain200ResponseCustomConfig struct for DomainsGetDomain200ResponseCustomConfig
type DomainsGetDomain200ResponseCustomConfig struct {
	MaxBodySizeMb         *float32 `json:"maxBodySizeMb,omitempty"`
	MaxConnectionTimeoutS *float32 `json:"maxConnectionTimeoutS,omitempty"`
	UseRegex              *bool    `json:"useRegex,omitempty"`
}

// NewDomainsGetDomain200ResponseCustomConfig instantiates a new DomainsGetDomain200ResponseCustomConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainsGetDomain200ResponseCustomConfig() *DomainsGetDomain200ResponseCustomConfig {
	this := DomainsGetDomain200ResponseCustomConfig{}
	return &this
}

// NewDomainsGetDomain200ResponseCustomConfigWithDefaults instantiates a new DomainsGetDomain200ResponseCustomConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainsGetDomain200ResponseCustomConfigWithDefaults() *DomainsGetDomain200ResponseCustomConfig {
	this := DomainsGetDomain200ResponseCustomConfig{}
	return &this
}

// GetMaxBodySizeMb returns the MaxBodySizeMb field value if set, zero value otherwise.
func (o *DomainsGetDomain200ResponseCustomConfig) GetMaxBodySizeMb() float32 {
	if o == nil || IsNil(o.MaxBodySizeMb) {
		var ret float32
		return ret
	}
	return *o.MaxBodySizeMb
}

// GetMaxBodySizeMbOk returns a tuple with the MaxBodySizeMb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainsGetDomain200ResponseCustomConfig) GetMaxBodySizeMbOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxBodySizeMb) {
		return nil, false
	}
	return o.MaxBodySizeMb, true
}

// HasMaxBodySizeMb returns a boolean if a field has been set.
func (o *DomainsGetDomain200ResponseCustomConfig) HasMaxBodySizeMb() bool {
	if o != nil && !IsNil(o.MaxBodySizeMb) {
		return true
	}

	return false
}

// SetMaxBodySizeMb gets a reference to the given float32 and assigns it to the MaxBodySizeMb field.
func (o *DomainsGetDomain200ResponseCustomConfig) SetMaxBodySizeMb(v float32) {
	o.MaxBodySizeMb = &v
}

// GetMaxConnectionTimeoutS returns the MaxConnectionTimeoutS field value if set, zero value otherwise.
func (o *DomainsGetDomain200ResponseCustomConfig) GetMaxConnectionTimeoutS() float32 {
	if o == nil || IsNil(o.MaxConnectionTimeoutS) {
		var ret float32
		return ret
	}
	return *o.MaxConnectionTimeoutS
}

// GetMaxConnectionTimeoutSOk returns a tuple with the MaxConnectionTimeoutS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainsGetDomain200ResponseCustomConfig) GetMaxConnectionTimeoutSOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxConnectionTimeoutS) {
		return nil, false
	}
	return o.MaxConnectionTimeoutS, true
}

// HasMaxConnectionTimeoutS returns a boolean if a field has been set.
func (o *DomainsGetDomain200ResponseCustomConfig) HasMaxConnectionTimeoutS() bool {
	if o != nil && !IsNil(o.MaxConnectionTimeoutS) {
		return true
	}

	return false
}

// SetMaxConnectionTimeoutS gets a reference to the given float32 and assigns it to the MaxConnectionTimeoutS field.
func (o *DomainsGetDomain200ResponseCustomConfig) SetMaxConnectionTimeoutS(v float32) {
	o.MaxConnectionTimeoutS = &v
}

// GetUseRegex returns the UseRegex field value if set, zero value otherwise.
func (o *DomainsGetDomain200ResponseCustomConfig) GetUseRegex() bool {
	if o == nil || IsNil(o.UseRegex) {
		var ret bool
		return ret
	}
	return *o.UseRegex
}

// GetUseRegexOk returns a tuple with the UseRegex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainsGetDomain200ResponseCustomConfig) GetUseRegexOk() (*bool, bool) {
	if o == nil || IsNil(o.UseRegex) {
		return nil, false
	}
	return o.UseRegex, true
}

// HasUseRegex returns a boolean if a field has been set.
func (o *DomainsGetDomain200ResponseCustomConfig) HasUseRegex() bool {
	if o != nil && !IsNil(o.UseRegex) {
		return true
	}

	return false
}

// SetUseRegex gets a reference to the given bool and assigns it to the UseRegex field.
func (o *DomainsGetDomain200ResponseCustomConfig) SetUseRegex(v bool) {
	o.UseRegex = &v
}

func (o DomainsGetDomain200ResponseCustomConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainsGetDomain200ResponseCustomConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaxBodySizeMb) {
		toSerialize["maxBodySizeMb"] = o.MaxBodySizeMb
	}
	if !IsNil(o.MaxConnectionTimeoutS) {
		toSerialize["maxConnectionTimeoutS"] = o.MaxConnectionTimeoutS
	}
	if !IsNil(o.UseRegex) {
		toSerialize["useRegex"] = o.UseRegex
	}
	return toSerialize, nil
}

type NullableDomainsGetDomain200ResponseCustomConfig struct {
	value *DomainsGetDomain200ResponseCustomConfig
	isSet bool
}

func (v NullableDomainsGetDomain200ResponseCustomConfig) Get() *DomainsGetDomain200ResponseCustomConfig {
	return v.value
}

func (v *NullableDomainsGetDomain200ResponseCustomConfig) Set(val *DomainsGetDomain200ResponseCustomConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainsGetDomain200ResponseCustomConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainsGetDomain200ResponseCustomConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainsGetDomain200ResponseCustomConfig(val *DomainsGetDomain200ResponseCustomConfig) *NullableDomainsGetDomain200ResponseCustomConfig {
	return &NullableDomainsGetDomain200ResponseCustomConfig{value: val, isSet: true}
}

func (v NullableDomainsGetDomain200ResponseCustomConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainsGetDomain200ResponseCustomConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
