// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape{}

// ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape struct for ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape
type ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape struct {
	GitUrl    string `json:"gitUrl"`
	CiProfile string `json:"ciProfile"`
}

type _ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape

// NewManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape instantiates a new ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape(gitUrl string, ciProfile string) *ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape {
	this := ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape{}
	this.GitUrl = gitUrl
	this.CiProfile = ciProfile
	return &this
}

// NewManagedServicesListProviders200ResponseInnerAnyOfBackendLandscapeWithDefaults instantiates a new ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedServicesListProviders200ResponseInnerAnyOfBackendLandscapeWithDefaults() *ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape {
	this := ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape{}
	return &this
}

// GetGitUrl returns the GitUrl field value
func (o *ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape) GetGitUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GitUrl
}

// GetGitUrlOk returns a tuple with the GitUrl field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape) GetGitUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GitUrl, true
}

// SetGitUrl sets field value
func (o *ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape) SetGitUrl(v string) {
	o.GitUrl = v
}

// GetCiProfile returns the CiProfile field value
func (o *ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape) GetCiProfile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CiProfile
}

// GetCiProfileOk returns a tuple with the CiProfile field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape) GetCiProfileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CiProfile, true
}

// SetCiProfile sets field value
func (o *ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape) SetCiProfile(v string) {
	o.CiProfile = v
}

func (o ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["gitUrl"] = o.GitUrl
	toSerialize["ciProfile"] = o.CiProfile
	return toSerialize, nil
}

func (o *ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"gitUrl",
		"ciProfile",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape := _ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape)

	if err != nil {
		return err
	}

	*o = ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape(varManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape)

	return err
}

type NullableManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape struct {
	value *ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape
	isSet bool
}

func (v NullableManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape) Get() *ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape {
	return v.value
}

func (v *NullableManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape) Set(val *ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape(val *ManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape) *NullableManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape {
	return &NullableManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape{value: val, isSet: true}
}

func (v NullableManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesListProviders200ResponseInnerAnyOfBackendLandscape) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
