// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the WorkspacesPipelineStatus200ResponseInnerStepsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspacesPipelineStatus200ResponseInnerStepsInner{}

// WorkspacesPipelineStatus200ResponseInnerStepsInner struct for WorkspacesPipelineStatus200ResponseInnerStepsInner
type WorkspacesPipelineStatus200ResponseInnerStepsInner struct {
	State      string     `json:"state"`
	StartedAt  *time.Time `json:"startedAt,omitempty"`
	FinishedAt *time.Time `json:"finishedAt,omitempty"`
}

type _WorkspacesPipelineStatus200ResponseInnerStepsInner WorkspacesPipelineStatus200ResponseInnerStepsInner

// NewWorkspacesPipelineStatus200ResponseInnerStepsInner instantiates a new WorkspacesPipelineStatus200ResponseInnerStepsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspacesPipelineStatus200ResponseInnerStepsInner(state string) *WorkspacesPipelineStatus200ResponseInnerStepsInner {
	this := WorkspacesPipelineStatus200ResponseInnerStepsInner{}
	this.State = state
	return &this
}

// NewWorkspacesPipelineStatus200ResponseInnerStepsInnerWithDefaults instantiates a new WorkspacesPipelineStatus200ResponseInnerStepsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspacesPipelineStatus200ResponseInnerStepsInnerWithDefaults() *WorkspacesPipelineStatus200ResponseInnerStepsInner {
	this := WorkspacesPipelineStatus200ResponseInnerStepsInner{}
	return &this
}

// GetState returns the State field value
func (o *WorkspacesPipelineStatus200ResponseInnerStepsInner) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *WorkspacesPipelineStatus200ResponseInnerStepsInner) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *WorkspacesPipelineStatus200ResponseInnerStepsInner) SetState(v string) {
	o.State = v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *WorkspacesPipelineStatus200ResponseInnerStepsInner) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspacesPipelineStatus200ResponseInnerStepsInner) GetStartedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *WorkspacesPipelineStatus200ResponseInnerStepsInner) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given time.Time and assigns it to the StartedAt field.
func (o *WorkspacesPipelineStatus200ResponseInnerStepsInner) SetStartedAt(v time.Time) {
	o.StartedAt = &v
}

// GetFinishedAt returns the FinishedAt field value if set, zero value otherwise.
func (o *WorkspacesPipelineStatus200ResponseInnerStepsInner) GetFinishedAt() time.Time {
	if o == nil || IsNil(o.FinishedAt) {
		var ret time.Time
		return ret
	}
	return *o.FinishedAt
}

// GetFinishedAtOk returns a tuple with the FinishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspacesPipelineStatus200ResponseInnerStepsInner) GetFinishedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FinishedAt) {
		return nil, false
	}
	return o.FinishedAt, true
}

// HasFinishedAt returns a boolean if a field has been set.
func (o *WorkspacesPipelineStatus200ResponseInnerStepsInner) HasFinishedAt() bool {
	if o != nil && !IsNil(o.FinishedAt) {
		return true
	}

	return false
}

// SetFinishedAt gets a reference to the given time.Time and assigns it to the FinishedAt field.
func (o *WorkspacesPipelineStatus200ResponseInnerStepsInner) SetFinishedAt(v time.Time) {
	o.FinishedAt = &v
}

func (o WorkspacesPipelineStatus200ResponseInnerStepsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspacesPipelineStatus200ResponseInnerStepsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	if !IsNil(o.StartedAt) {
		toSerialize["startedAt"] = o.StartedAt
	}
	if !IsNil(o.FinishedAt) {
		toSerialize["finishedAt"] = o.FinishedAt
	}
	return toSerialize, nil
}

func (o *WorkspacesPipelineStatus200ResponseInnerStepsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkspacesPipelineStatus200ResponseInnerStepsInner := _WorkspacesPipelineStatus200ResponseInnerStepsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkspacesPipelineStatus200ResponseInnerStepsInner)

	if err != nil {
		return err
	}

	*o = WorkspacesPipelineStatus200ResponseInnerStepsInner(varWorkspacesPipelineStatus200ResponseInnerStepsInner)

	return err
}

type NullableWorkspacesPipelineStatus200ResponseInnerStepsInner struct {
	value *WorkspacesPipelineStatus200ResponseInnerStepsInner
	isSet bool
}

func (v NullableWorkspacesPipelineStatus200ResponseInnerStepsInner) Get() *WorkspacesPipelineStatus200ResponseInnerStepsInner {
	return v.value
}

func (v *NullableWorkspacesPipelineStatus200ResponseInnerStepsInner) Set(val *WorkspacesPipelineStatus200ResponseInnerStepsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspacesPipelineStatus200ResponseInnerStepsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspacesPipelineStatus200ResponseInnerStepsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspacesPipelineStatus200ResponseInnerStepsInner(val *WorkspacesPipelineStatus200ResponseInnerStepsInner) *NullableWorkspacesPipelineStatus200ResponseInnerStepsInner {
	return &NullableWorkspacesPipelineStatus200ResponseInnerStepsInner{value: val, isSet: true}
}

func (v NullableWorkspacesPipelineStatus200ResponseInnerStepsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspacesPipelineStatus200ResponseInnerStepsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
