// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
	"fmt"
)

// ManagedServicesUpsertProviderRequest struct for ManagedServicesUpsertProviderRequest
type ManagedServicesUpsertProviderRequest struct {
	ManagedServicesUpsertProviderRequestAnyOf  *ManagedServicesUpsertProviderRequestAnyOf
	ManagedServicesUpsertProviderRequestAnyOf1 *ManagedServicesUpsertProviderRequestAnyOf1
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ManagedServicesUpsertProviderRequest) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ManagedServicesUpsertProviderRequestAnyOf
	err = json.Unmarshal(data, &dst.ManagedServicesUpsertProviderRequestAnyOf)
	if err == nil {
		jsonManagedServicesUpsertProviderRequestAnyOf, _ := json.Marshal(dst.ManagedServicesUpsertProviderRequestAnyOf)
		if string(jsonManagedServicesUpsertProviderRequestAnyOf) == "{}" { // empty struct
			dst.ManagedServicesUpsertProviderRequestAnyOf = nil
		} else {
			return nil // data stored in dst.ManagedServicesUpsertProviderRequestAnyOf, return on the first match
		}
	} else {
		dst.ManagedServicesUpsertProviderRequestAnyOf = nil
	}

	// try to unmarshal JSON data into ManagedServicesUpsertProviderRequestAnyOf1
	err = json.Unmarshal(data, &dst.ManagedServicesUpsertProviderRequestAnyOf1)
	if err == nil {
		jsonManagedServicesUpsertProviderRequestAnyOf1, _ := json.Marshal(dst.ManagedServicesUpsertProviderRequestAnyOf1)
		if string(jsonManagedServicesUpsertProviderRequestAnyOf1) == "{}" { // empty struct
			dst.ManagedServicesUpsertProviderRequestAnyOf1 = nil
		} else {
			return nil // data stored in dst.ManagedServicesUpsertProviderRequestAnyOf1, return on the first match
		}
	} else {
		dst.ManagedServicesUpsertProviderRequestAnyOf1 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ManagedServicesUpsertProviderRequest)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ManagedServicesUpsertProviderRequest) MarshalJSON() ([]byte, error) {
	if src.ManagedServicesUpsertProviderRequestAnyOf != nil {
		return json.Marshal(&src.ManagedServicesUpsertProviderRequestAnyOf)
	}

	if src.ManagedServicesUpsertProviderRequestAnyOf1 != nil {
		return json.Marshal(&src.ManagedServicesUpsertProviderRequestAnyOf1)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableManagedServicesUpsertProviderRequest struct {
	value *ManagedServicesUpsertProviderRequest
	isSet bool
}

func (v NullableManagedServicesUpsertProviderRequest) Get() *ManagedServicesUpsertProviderRequest {
	return v.value
}

func (v *NullableManagedServicesUpsertProviderRequest) Set(val *ManagedServicesUpsertProviderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesUpsertProviderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesUpsertProviderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesUpsertProviderRequest(val *ManagedServicesUpsertProviderRequest) *NullableManagedServicesUpsertProviderRequest {
	return &NullableManagedServicesUpsertProviderRequest{value: val, isSet: true}
}

func (v NullableManagedServicesUpsertProviderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesUpsertProviderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
