// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ManagedServicesList200ResponseInnerRecentEventsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedServicesList200ResponseInnerRecentEventsInner{}

// ManagedServicesList200ResponseInnerRecentEventsInner struct for ManagedServicesList200ResponseInnerRecentEventsInner
type ManagedServicesList200ResponseInnerRecentEventsInner struct {
	EventName         string            `json:"eventName"`
	Timestamp         time.Time         `json:"timestamp"`
	ObservedTimestamp time.Time         `json:"observedTimestamp"`
	SeverityNumber    int               `json:"severityNumber"`
	Body              string            `json:"body"`
	Resource          string            `json:"resource"`
	Attributes        map[string]string `json:"attributes"`
}

type _ManagedServicesList200ResponseInnerRecentEventsInner ManagedServicesList200ResponseInnerRecentEventsInner

// NewManagedServicesList200ResponseInnerRecentEventsInner instantiates a new ManagedServicesList200ResponseInnerRecentEventsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedServicesList200ResponseInnerRecentEventsInner(eventName string, timestamp time.Time, observedTimestamp time.Time, severityNumber int, body string, resource string, attributes map[string]string) *ManagedServicesList200ResponseInnerRecentEventsInner {
	this := ManagedServicesList200ResponseInnerRecentEventsInner{}
	this.EventName = eventName
	this.Timestamp = timestamp
	this.ObservedTimestamp = observedTimestamp
	this.SeverityNumber = severityNumber
	this.Body = body
	this.Resource = resource
	this.Attributes = attributes
	return &this
}

// NewManagedServicesList200ResponseInnerRecentEventsInnerWithDefaults instantiates a new ManagedServicesList200ResponseInnerRecentEventsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedServicesList200ResponseInnerRecentEventsInnerWithDefaults() *ManagedServicesList200ResponseInnerRecentEventsInner {
	this := ManagedServicesList200ResponseInnerRecentEventsInner{}
	return &this
}

// GetEventName returns the EventName field value
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) GetEventName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventName
}

// GetEventNameOk returns a tuple with the EventName field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) GetEventNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventName, true
}

// SetEventName sets field value
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) SetEventName(v string) {
	o.EventName = v
}

// GetTimestamp returns the Timestamp field value
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetObservedTimestamp returns the ObservedTimestamp field value
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) GetObservedTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ObservedTimestamp
}

// GetObservedTimestampOk returns a tuple with the ObservedTimestamp field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) GetObservedTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedTimestamp, true
}

// SetObservedTimestamp sets field value
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) SetObservedTimestamp(v time.Time) {
	o.ObservedTimestamp = v
}

// GetSeverityNumber returns the SeverityNumber field value
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) GetSeverityNumber() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.SeverityNumber
}

// GetSeverityNumberOk returns a tuple with the SeverityNumber field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) GetSeverityNumberOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SeverityNumber, true
}

// SetSeverityNumber sets field value
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) SetSeverityNumber(v int) {
	o.SeverityNumber = v
}

// GetBody returns the Body field value
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) GetBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) SetBody(v string) {
	o.Body = v
}

// GetResource returns the Resource field value
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) GetResource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Resource
}

// GetResourceOk returns a tuple with the Resource field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) GetResourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resource, true
}

// SetResource sets field value
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) SetResource(v string) {
	o.Resource = v
}

// GetAttributes returns the Attributes field value
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) GetAttributes() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) GetAttributesOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ManagedServicesList200ResponseInnerRecentEventsInner) SetAttributes(v map[string]string) {
	o.Attributes = v
}

func (o ManagedServicesList200ResponseInnerRecentEventsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedServicesList200ResponseInnerRecentEventsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["eventName"] = o.EventName
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["observedTimestamp"] = o.ObservedTimestamp
	toSerialize["severityNumber"] = o.SeverityNumber
	toSerialize["body"] = o.Body
	toSerialize["resource"] = o.Resource
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ManagedServicesList200ResponseInnerRecentEventsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"eventName",
		"timestamp",
		"observedTimestamp",
		"severityNumber",
		"body",
		"resource",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedServicesList200ResponseInnerRecentEventsInner := _ManagedServicesList200ResponseInnerRecentEventsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedServicesList200ResponseInnerRecentEventsInner)

	if err != nil {
		return err
	}

	*o = ManagedServicesList200ResponseInnerRecentEventsInner(varManagedServicesList200ResponseInnerRecentEventsInner)

	return err
}

type NullableManagedServicesList200ResponseInnerRecentEventsInner struct {
	value *ManagedServicesList200ResponseInnerRecentEventsInner
	isSet bool
}

func (v NullableManagedServicesList200ResponseInnerRecentEventsInner) Get() *ManagedServicesList200ResponseInnerRecentEventsInner {
	return v.value
}

func (v *NullableManagedServicesList200ResponseInnerRecentEventsInner) Set(val *ManagedServicesList200ResponseInnerRecentEventsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesList200ResponseInnerRecentEventsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesList200ResponseInnerRecentEventsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesList200ResponseInnerRecentEventsInner(val *ManagedServicesList200ResponseInnerRecentEventsInner) *NullableManagedServicesList200ResponseInnerRecentEventsInner {
	return &NullableManagedServicesList200ResponseInnerRecentEventsInner{value: val, isSet: true}
}

func (v NullableManagedServicesList200ResponseInnerRecentEventsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesList200ResponseInnerRecentEventsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
