// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ManagedServicesList200ResponseInnerStatusAnyOf7 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedServicesList200ResponseInnerStatusAnyOf7{}

// ManagedServicesList200ResponseInnerStatusAnyOf7 struct for ManagedServicesList200ResponseInnerStatusAnyOf7
type ManagedServicesList200ResponseInnerStatusAnyOf7 struct {
	State      string `json:"state"`
	DetailsRef string `json:"detailsRef"`
}

type _ManagedServicesList200ResponseInnerStatusAnyOf7 ManagedServicesList200ResponseInnerStatusAnyOf7

// NewManagedServicesList200ResponseInnerStatusAnyOf7 instantiates a new ManagedServicesList200ResponseInnerStatusAnyOf7 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedServicesList200ResponseInnerStatusAnyOf7(state string, detailsRef string) *ManagedServicesList200ResponseInnerStatusAnyOf7 {
	this := ManagedServicesList200ResponseInnerStatusAnyOf7{}
	this.State = state
	this.DetailsRef = detailsRef
	return &this
}

// NewManagedServicesList200ResponseInnerStatusAnyOf7WithDefaults instantiates a new ManagedServicesList200ResponseInnerStatusAnyOf7 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedServicesList200ResponseInnerStatusAnyOf7WithDefaults() *ManagedServicesList200ResponseInnerStatusAnyOf7 {
	this := ManagedServicesList200ResponseInnerStatusAnyOf7{}
	return &this
}

// GetState returns the State field value
func (o *ManagedServicesList200ResponseInnerStatusAnyOf7) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesList200ResponseInnerStatusAnyOf7) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ManagedServicesList200ResponseInnerStatusAnyOf7) SetState(v string) {
	o.State = v
}

// GetDetailsRef returns the DetailsRef field value
func (o *ManagedServicesList200ResponseInnerStatusAnyOf7) GetDetailsRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DetailsRef
}

// GetDetailsRefOk returns a tuple with the DetailsRef field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesList200ResponseInnerStatusAnyOf7) GetDetailsRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DetailsRef, true
}

// SetDetailsRef sets field value
func (o *ManagedServicesList200ResponseInnerStatusAnyOf7) SetDetailsRef(v string) {
	o.DetailsRef = v
}

func (o ManagedServicesList200ResponseInnerStatusAnyOf7) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedServicesList200ResponseInnerStatusAnyOf7) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	toSerialize["detailsRef"] = o.DetailsRef
	return toSerialize, nil
}

func (o *ManagedServicesList200ResponseInnerStatusAnyOf7) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
		"detailsRef",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedServicesList200ResponseInnerStatusAnyOf7 := _ManagedServicesList200ResponseInnerStatusAnyOf7{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedServicesList200ResponseInnerStatusAnyOf7)

	if err != nil {
		return err
	}

	*o = ManagedServicesList200ResponseInnerStatusAnyOf7(varManagedServicesList200ResponseInnerStatusAnyOf7)

	return err
}

type NullableManagedServicesList200ResponseInnerStatusAnyOf7 struct {
	value *ManagedServicesList200ResponseInnerStatusAnyOf7
	isSet bool
}

func (v NullableManagedServicesList200ResponseInnerStatusAnyOf7) Get() *ManagedServicesList200ResponseInnerStatusAnyOf7 {
	return v.value
}

func (v *NullableManagedServicesList200ResponseInnerStatusAnyOf7) Set(val *ManagedServicesList200ResponseInnerStatusAnyOf7) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesList200ResponseInnerStatusAnyOf7) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesList200ResponseInnerStatusAnyOf7) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesList200ResponseInnerStatusAnyOf7(val *ManagedServicesList200ResponseInnerStatusAnyOf7) *NullableManagedServicesList200ResponseInnerStatusAnyOf7 {
	return &NullableManagedServicesList200ResponseInnerStatusAnyOf7{value: val, isSet: true}
}

func (v NullableManagedServicesList200ResponseInnerStatusAnyOf7) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesList200ResponseInnerStatusAnyOf7) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
