// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ManagedServicesCreateRequestRecoverFromAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedServicesCreateRequestRecoverFromAnyOf{}

// ManagedServicesCreateRequestRecoverFromAnyOf struct for ManagedServicesCreateRequestRecoverFromAnyOf
type ManagedServicesCreateRequestRecoverFromAnyOf struct {
	// UUID
	Id      string                 `json:"id"`
	Config  map[string]interface{} `json:"config"`
	Secrets map[string]interface{} `json:"secrets"`
}

type _ManagedServicesCreateRequestRecoverFromAnyOf ManagedServicesCreateRequestRecoverFromAnyOf

// NewManagedServicesCreateRequestRecoverFromAnyOf instantiates a new ManagedServicesCreateRequestRecoverFromAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedServicesCreateRequestRecoverFromAnyOf(id string, config map[string]interface{}, secrets map[string]interface{}) *ManagedServicesCreateRequestRecoverFromAnyOf {
	this := ManagedServicesCreateRequestRecoverFromAnyOf{}
	this.Id = id
	this.Config = config
	this.Secrets = secrets
	return &this
}

// NewManagedServicesCreateRequestRecoverFromAnyOfWithDefaults instantiates a new ManagedServicesCreateRequestRecoverFromAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedServicesCreateRequestRecoverFromAnyOfWithDefaults() *ManagedServicesCreateRequestRecoverFromAnyOf {
	this := ManagedServicesCreateRequestRecoverFromAnyOf{}
	return &this
}

// GetId returns the Id field value
func (o *ManagedServicesCreateRequestRecoverFromAnyOf) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateRequestRecoverFromAnyOf) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ManagedServicesCreateRequestRecoverFromAnyOf) SetId(v string) {
	o.Id = v
}

// GetConfig returns the Config field value
func (o *ManagedServicesCreateRequestRecoverFromAnyOf) GetConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateRequestRecoverFromAnyOf) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// SetConfig sets field value
func (o *ManagedServicesCreateRequestRecoverFromAnyOf) SetConfig(v map[string]interface{}) {
	o.Config = v
}

// GetSecrets returns the Secrets field value
func (o *ManagedServicesCreateRequestRecoverFromAnyOf) GetSecrets() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateRequestRecoverFromAnyOf) GetSecretsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Secrets, true
}

// SetSecrets sets field value
func (o *ManagedServicesCreateRequestRecoverFromAnyOf) SetSecrets(v map[string]interface{}) {
	o.Secrets = v
}

func (o ManagedServicesCreateRequestRecoverFromAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedServicesCreateRequestRecoverFromAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["config"] = o.Config
	toSerialize["secrets"] = o.Secrets
	return toSerialize, nil
}

func (o *ManagedServicesCreateRequestRecoverFromAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"config",
		"secrets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedServicesCreateRequestRecoverFromAnyOf := _ManagedServicesCreateRequestRecoverFromAnyOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedServicesCreateRequestRecoverFromAnyOf)

	if err != nil {
		return err
	}

	*o = ManagedServicesCreateRequestRecoverFromAnyOf(varManagedServicesCreateRequestRecoverFromAnyOf)

	return err
}

type NullableManagedServicesCreateRequestRecoverFromAnyOf struct {
	value *ManagedServicesCreateRequestRecoverFromAnyOf
	isSet bool
}

func (v NullableManagedServicesCreateRequestRecoverFromAnyOf) Get() *ManagedServicesCreateRequestRecoverFromAnyOf {
	return v.value
}

func (v *NullableManagedServicesCreateRequestRecoverFromAnyOf) Set(val *ManagedServicesCreateRequestRecoverFromAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesCreateRequestRecoverFromAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesCreateRequestRecoverFromAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesCreateRequestRecoverFromAnyOf(val *ManagedServicesCreateRequestRecoverFromAnyOf) *NullableManagedServicesCreateRequestRecoverFromAnyOf {
	return &NullableManagedServicesCreateRequestRecoverFromAnyOf{value: val, isSet: true}
}

func (v NullableManagedServicesCreateRequestRecoverFromAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesCreateRequestRecoverFromAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
