// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ManagedServicesList200ResponseInnerStatusAnyOf3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedServicesList200ResponseInnerStatusAnyOf3{}

// ManagedServicesList200ResponseInnerStatusAnyOf3 struct for ManagedServicesList200ResponseInnerStatusAnyOf3
type ManagedServicesList200ResponseInnerStatusAnyOf3 struct {
	State     string    `json:"state"`
	DeletedAt time.Time `json:"deletedAt"`
}

type _ManagedServicesList200ResponseInnerStatusAnyOf3 ManagedServicesList200ResponseInnerStatusAnyOf3

// NewManagedServicesList200ResponseInnerStatusAnyOf3 instantiates a new ManagedServicesList200ResponseInnerStatusAnyOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedServicesList200ResponseInnerStatusAnyOf3(state string, deletedAt time.Time) *ManagedServicesList200ResponseInnerStatusAnyOf3 {
	this := ManagedServicesList200ResponseInnerStatusAnyOf3{}
	this.State = state
	this.DeletedAt = deletedAt
	return &this
}

// NewManagedServicesList200ResponseInnerStatusAnyOf3WithDefaults instantiates a new ManagedServicesList200ResponseInnerStatusAnyOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedServicesList200ResponseInnerStatusAnyOf3WithDefaults() *ManagedServicesList200ResponseInnerStatusAnyOf3 {
	this := ManagedServicesList200ResponseInnerStatusAnyOf3{}
	return &this
}

// GetState returns the State field value
func (o *ManagedServicesList200ResponseInnerStatusAnyOf3) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesList200ResponseInnerStatusAnyOf3) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ManagedServicesList200ResponseInnerStatusAnyOf3) SetState(v string) {
	o.State = v
}

// GetDeletedAt returns the DeletedAt field value
func (o *ManagedServicesList200ResponseInnerStatusAnyOf3) GetDeletedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesList200ResponseInnerStatusAnyOf3) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeletedAt, true
}

// SetDeletedAt sets field value
func (o *ManagedServicesList200ResponseInnerStatusAnyOf3) SetDeletedAt(v time.Time) {
	o.DeletedAt = v
}

func (o ManagedServicesList200ResponseInnerStatusAnyOf3) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedServicesList200ResponseInnerStatusAnyOf3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	toSerialize["deletedAt"] = o.DeletedAt
	return toSerialize, nil
}

func (o *ManagedServicesList200ResponseInnerStatusAnyOf3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
		"deletedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedServicesList200ResponseInnerStatusAnyOf3 := _ManagedServicesList200ResponseInnerStatusAnyOf3{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedServicesList200ResponseInnerStatusAnyOf3)

	if err != nil {
		return err
	}

	*o = ManagedServicesList200ResponseInnerStatusAnyOf3(varManagedServicesList200ResponseInnerStatusAnyOf3)

	return err
}

type NullableManagedServicesList200ResponseInnerStatusAnyOf3 struct {
	value *ManagedServicesList200ResponseInnerStatusAnyOf3
	isSet bool
}

func (v NullableManagedServicesList200ResponseInnerStatusAnyOf3) Get() *ManagedServicesList200ResponseInnerStatusAnyOf3 {
	return v.value
}

func (v *NullableManagedServicesList200ResponseInnerStatusAnyOf3) Set(val *ManagedServicesList200ResponseInnerStatusAnyOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesList200ResponseInnerStatusAnyOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesList200ResponseInnerStatusAnyOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesList200ResponseInnerStatusAnyOf3(val *ManagedServicesList200ResponseInnerStatusAnyOf3) *NullableManagedServicesList200ResponseInnerStatusAnyOf3 {
	return &NullableManagedServicesList200ResponseInnerStatusAnyOf3{value: val, isSet: true}
}

func (v NullableManagedServicesList200ResponseInnerStatusAnyOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesList200ResponseInnerStatusAnyOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
