// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ManagedServicesCreateProviderRequestAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedServicesCreateProviderRequestAnyOf1{}

// ManagedServicesCreateProviderRequestAnyOf1 struct for ManagedServicesCreateProviderRequestAnyOf1
type ManagedServicesCreateProviderRequestAnyOf1 struct {
	GitUrl string                                          `json:"gitUrl"`
	GitRef *string                                         `json:"gitRef,omitempty"`
	Scope  *ManagedServicesCreateProviderRequestAnyOfScope `json:"scope,omitempty"`
}

type _ManagedServicesCreateProviderRequestAnyOf1 ManagedServicesCreateProviderRequestAnyOf1

// NewManagedServicesCreateProviderRequestAnyOf1 instantiates a new ManagedServicesCreateProviderRequestAnyOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedServicesCreateProviderRequestAnyOf1(gitUrl string) *ManagedServicesCreateProviderRequestAnyOf1 {
	this := ManagedServicesCreateProviderRequestAnyOf1{}
	this.GitUrl = gitUrl
	return &this
}

// NewManagedServicesCreateProviderRequestAnyOf1WithDefaults instantiates a new ManagedServicesCreateProviderRequestAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedServicesCreateProviderRequestAnyOf1WithDefaults() *ManagedServicesCreateProviderRequestAnyOf1 {
	this := ManagedServicesCreateProviderRequestAnyOf1{}
	return &this
}

// GetGitUrl returns the GitUrl field value
func (o *ManagedServicesCreateProviderRequestAnyOf1) GetGitUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GitUrl
}

// GetGitUrlOk returns a tuple with the GitUrl field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateProviderRequestAnyOf1) GetGitUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GitUrl, true
}

// SetGitUrl sets field value
func (o *ManagedServicesCreateProviderRequestAnyOf1) SetGitUrl(v string) {
	o.GitUrl = v
}

// GetGitRef returns the GitRef field value if set, zero value otherwise.
func (o *ManagedServicesCreateProviderRequestAnyOf1) GetGitRef() string {
	if o == nil || IsNil(o.GitRef) {
		var ret string
		return ret
	}
	return *o.GitRef
}

// GetGitRefOk returns a tuple with the GitRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateProviderRequestAnyOf1) GetGitRefOk() (*string, bool) {
	if o == nil || IsNil(o.GitRef) {
		return nil, false
	}
	return o.GitRef, true
}

// HasGitRef returns a boolean if a field has been set.
func (o *ManagedServicesCreateProviderRequestAnyOf1) HasGitRef() bool {
	if o != nil && !IsNil(o.GitRef) {
		return true
	}

	return false
}

// SetGitRef gets a reference to the given string and assigns it to the GitRef field.
func (o *ManagedServicesCreateProviderRequestAnyOf1) SetGitRef(v string) {
	o.GitRef = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *ManagedServicesCreateProviderRequestAnyOf1) GetScope() ManagedServicesCreateProviderRequestAnyOfScope {
	if o == nil || IsNil(o.Scope) {
		var ret ManagedServicesCreateProviderRequestAnyOfScope
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateProviderRequestAnyOf1) GetScopeOk() (*ManagedServicesCreateProviderRequestAnyOfScope, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *ManagedServicesCreateProviderRequestAnyOf1) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given ManagedServicesCreateProviderRequestAnyOfScope and assigns it to the Scope field.
func (o *ManagedServicesCreateProviderRequestAnyOf1) SetScope(v ManagedServicesCreateProviderRequestAnyOfScope) {
	o.Scope = &v
}

func (o ManagedServicesCreateProviderRequestAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedServicesCreateProviderRequestAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["gitUrl"] = o.GitUrl
	if !IsNil(o.GitRef) {
		toSerialize["gitRef"] = o.GitRef
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	return toSerialize, nil
}

func (o *ManagedServicesCreateProviderRequestAnyOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"gitUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedServicesCreateProviderRequestAnyOf1 := _ManagedServicesCreateProviderRequestAnyOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedServicesCreateProviderRequestAnyOf1)

	if err != nil {
		return err
	}

	*o = ManagedServicesCreateProviderRequestAnyOf1(varManagedServicesCreateProviderRequestAnyOf1)

	return err
}

type NullableManagedServicesCreateProviderRequestAnyOf1 struct {
	value *ManagedServicesCreateProviderRequestAnyOf1
	isSet bool
}

func (v NullableManagedServicesCreateProviderRequestAnyOf1) Get() *ManagedServicesCreateProviderRequestAnyOf1 {
	return v.value
}

func (v *NullableManagedServicesCreateProviderRequestAnyOf1) Set(val *ManagedServicesCreateProviderRequestAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesCreateProviderRequestAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesCreateProviderRequestAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesCreateProviderRequestAnyOf1(val *ManagedServicesCreateProviderRequestAnyOf1) *NullableManagedServicesCreateProviderRequestAnyOf1 {
	return &NullableManagedServicesCreateProviderRequestAnyOf1{value: val, isSet: true}
}

func (v NullableManagedServicesCreateProviderRequestAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesCreateProviderRequestAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
