// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
	"fmt"
)

// ManagedServicesCreateProviderRequest struct for ManagedServicesCreateProviderRequest
type ManagedServicesCreateProviderRequest struct {
	ManagedServicesCreateProviderRequestAnyOf  *ManagedServicesCreateProviderRequestAnyOf
	ManagedServicesCreateProviderRequestAnyOf1 *ManagedServicesCreateProviderRequestAnyOf1
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ManagedServicesCreateProviderRequest) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ManagedServicesCreateProviderRequestAnyOf
	err = json.Unmarshal(data, &dst.ManagedServicesCreateProviderRequestAnyOf)
	if err == nil {
		jsonManagedServicesCreateProviderRequestAnyOf, _ := json.Marshal(dst.ManagedServicesCreateProviderRequestAnyOf)
		if string(jsonManagedServicesCreateProviderRequestAnyOf) == "{}" { // empty struct
			dst.ManagedServicesCreateProviderRequestAnyOf = nil
		} else {
			return nil // data stored in dst.ManagedServicesCreateProviderRequestAnyOf, return on the first match
		}
	} else {
		dst.ManagedServicesCreateProviderRequestAnyOf = nil
	}

	// try to unmarshal JSON data into ManagedServicesCreateProviderRequestAnyOf1
	err = json.Unmarshal(data, &dst.ManagedServicesCreateProviderRequestAnyOf1)
	if err == nil {
		jsonManagedServicesCreateProviderRequestAnyOf1, _ := json.Marshal(dst.ManagedServicesCreateProviderRequestAnyOf1)
		if string(jsonManagedServicesCreateProviderRequestAnyOf1) == "{}" { // empty struct
			dst.ManagedServicesCreateProviderRequestAnyOf1 = nil
		} else {
			return nil // data stored in dst.ManagedServicesCreateProviderRequestAnyOf1, return on the first match
		}
	} else {
		dst.ManagedServicesCreateProviderRequestAnyOf1 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ManagedServicesCreateProviderRequest)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ManagedServicesCreateProviderRequest) MarshalJSON() ([]byte, error) {
	if src.ManagedServicesCreateProviderRequestAnyOf != nil {
		return json.Marshal(&src.ManagedServicesCreateProviderRequestAnyOf)
	}

	if src.ManagedServicesCreateProviderRequestAnyOf1 != nil {
		return json.Marshal(&src.ManagedServicesCreateProviderRequestAnyOf1)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableManagedServicesCreateProviderRequest struct {
	value *ManagedServicesCreateProviderRequest
	isSet bool
}

func (v NullableManagedServicesCreateProviderRequest) Get() *ManagedServicesCreateProviderRequest {
	return v.value
}

func (v *NullableManagedServicesCreateProviderRequest) Set(val *ManagedServicesCreateProviderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesCreateProviderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesCreateProviderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesCreateProviderRequest(val *ManagedServicesCreateProviderRequest) *NullableManagedServicesCreateProviderRequest {
	return &NullableManagedServicesCreateProviderRequest{value: val, isSet: true}
}

func (v NullableManagedServicesCreateProviderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesCreateProviderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
