// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the TeamsListMembers200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TeamsListMembers200ResponseInner{}

// TeamsListMembers200ResponseInner struct for TeamsListMembers200ResponseInner
type TeamsListMembers200ResponseInner struct {
	UserId int `json:"userId"`
	TeamId int `json:"teamId"`
	// The role assigned to the team. 0 = Admin, 1 = Member.
	Role      int            `json:"role"`
	Pending   bool           `json:"pending"`
	CreatedAt time.Time      `json:"createdAt"`
	Name      NullableString `json:"name,omitempty"`
	Email     NullableString `json:"email,omitempty"`
	AvatarUrl NullableString `json:"avatarUrl,omitempty"`
	DeletedAt *time.Time     `json:"deletedAt,omitempty"`
}

type _TeamsListMembers200ResponseInner TeamsListMembers200ResponseInner

// NewTeamsListMembers200ResponseInner instantiates a new TeamsListMembers200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamsListMembers200ResponseInner(userId int, teamId int, role int, pending bool, createdAt time.Time) *TeamsListMembers200ResponseInner {
	this := TeamsListMembers200ResponseInner{}
	this.UserId = userId
	this.TeamId = teamId
	this.Role = role
	this.Pending = pending
	this.CreatedAt = createdAt
	return &this
}

// NewTeamsListMembers200ResponseInnerWithDefaults instantiates a new TeamsListMembers200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamsListMembers200ResponseInnerWithDefaults() *TeamsListMembers200ResponseInner {
	this := TeamsListMembers200ResponseInner{}
	return &this
}

// GetUserId returns the UserId field value
func (o *TeamsListMembers200ResponseInner) GetUserId() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *TeamsListMembers200ResponseInner) GetUserIdOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *TeamsListMembers200ResponseInner) SetUserId(v int) {
	o.UserId = v
}

// GetTeamId returns the TeamId field value
func (o *TeamsListMembers200ResponseInner) GetTeamId() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value
// and a boolean to check if the value has been set.
func (o *TeamsListMembers200ResponseInner) GetTeamIdOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TeamId, true
}

// SetTeamId sets field value
func (o *TeamsListMembers200ResponseInner) SetTeamId(v int) {
	o.TeamId = v
}

// GetRole returns the Role field value
func (o *TeamsListMembers200ResponseInner) GetRole() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *TeamsListMembers200ResponseInner) GetRoleOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *TeamsListMembers200ResponseInner) SetRole(v int) {
	o.Role = v
}

// GetPending returns the Pending field value
func (o *TeamsListMembers200ResponseInner) GetPending() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Pending
}

// GetPendingOk returns a tuple with the Pending field value
// and a boolean to check if the value has been set.
func (o *TeamsListMembers200ResponseInner) GetPendingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pending, true
}

// SetPending sets field value
func (o *TeamsListMembers200ResponseInner) SetPending(v bool) {
	o.Pending = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *TeamsListMembers200ResponseInner) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *TeamsListMembers200ResponseInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *TeamsListMembers200ResponseInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TeamsListMembers200ResponseInner) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TeamsListMembers200ResponseInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *TeamsListMembers200ResponseInner) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *TeamsListMembers200ResponseInner) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *TeamsListMembers200ResponseInner) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *TeamsListMembers200ResponseInner) UnsetName() {
	o.Name.Unset()
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TeamsListMembers200ResponseInner) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TeamsListMembers200ResponseInner) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *TeamsListMembers200ResponseInner) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *TeamsListMembers200ResponseInner) SetEmail(v string) {
	o.Email.Set(&v)
}

// SetEmailNil sets the value for Email to be an explicit nil
func (o *TeamsListMembers200ResponseInner) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *TeamsListMembers200ResponseInner) UnsetEmail() {
	o.Email.Unset()
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TeamsListMembers200ResponseInner) GetAvatarUrl() string {
	if o == nil || IsNil(o.AvatarUrl.Get()) {
		var ret string
		return ret
	}
	return *o.AvatarUrl.Get()
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TeamsListMembers200ResponseInner) GetAvatarUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvatarUrl.Get(), o.AvatarUrl.IsSet()
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *TeamsListMembers200ResponseInner) HasAvatarUrl() bool {
	if o != nil && o.AvatarUrl.IsSet() {
		return true
	}

	return false
}

// SetAvatarUrl gets a reference to the given NullableString and assigns it to the AvatarUrl field.
func (o *TeamsListMembers200ResponseInner) SetAvatarUrl(v string) {
	o.AvatarUrl.Set(&v)
}

// SetAvatarUrlNil sets the value for AvatarUrl to be an explicit nil
func (o *TeamsListMembers200ResponseInner) SetAvatarUrlNil() {
	o.AvatarUrl.Set(nil)
}

// UnsetAvatarUrl ensures that no value is present for AvatarUrl, not even an explicit nil
func (o *TeamsListMembers200ResponseInner) UnsetAvatarUrl() {
	o.AvatarUrl.Unset()
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *TeamsListMembers200ResponseInner) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamsListMembers200ResponseInner) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *TeamsListMembers200ResponseInner) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given time.Time and assigns it to the DeletedAt field.
func (o *TeamsListMembers200ResponseInner) SetDeletedAt(v time.Time) {
	o.DeletedAt = &v
}

func (o TeamsListMembers200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TeamsListMembers200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userId"] = o.UserId
	toSerialize["teamId"] = o.TeamId
	toSerialize["role"] = o.Role
	toSerialize["pending"] = o.Pending
	toSerialize["createdAt"] = o.CreatedAt
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	if o.AvatarUrl.IsSet() {
		toSerialize["avatarUrl"] = o.AvatarUrl.Get()
	}
	if !IsNil(o.DeletedAt) {
		toSerialize["deletedAt"] = o.DeletedAt
	}
	return toSerialize, nil
}

func (o *TeamsListMembers200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userId",
		"teamId",
		"role",
		"pending",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTeamsListMembers200ResponseInner := _TeamsListMembers200ResponseInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTeamsListMembers200ResponseInner)

	if err != nil {
		return err
	}

	*o = TeamsListMembers200ResponseInner(varTeamsListMembers200ResponseInner)

	return err
}

type NullableTeamsListMembers200ResponseInner struct {
	value *TeamsListMembers200ResponseInner
	isSet bool
}

func (v NullableTeamsListMembers200ResponseInner) Get() *TeamsListMembers200ResponseInner {
	return v.value
}

func (v *NullableTeamsListMembers200ResponseInner) Set(val *TeamsListMembers200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamsListMembers200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamsListMembers200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamsListMembers200ResponseInner(val *TeamsListMembers200ResponseInner) *NullableTeamsListMembers200ResponseInner {
	return &NullableTeamsListMembers200ResponseInner{value: val, isSet: true}
}

func (v NullableTeamsListMembers200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamsListMembers200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
