// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ManagedServicesList200ResponseInnerBackupsAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedServicesList200ResponseInnerBackupsAnyOf1{}

// ManagedServicesList200ResponseInnerBackupsAnyOf1 struct for ManagedServicesList200ResponseInnerBackupsAnyOf1
type ManagedServicesList200ResponseInnerBackupsAnyOf1 struct {
	Enabled bool                                                          `json:"enabled"`
	Entries []ManagedServicesList200ResponseInnerBackupsAnyOfEntriesInner `json:"entries"`
}

type _ManagedServicesList200ResponseInnerBackupsAnyOf1 ManagedServicesList200ResponseInnerBackupsAnyOf1

// NewManagedServicesList200ResponseInnerBackupsAnyOf1 instantiates a new ManagedServicesList200ResponseInnerBackupsAnyOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedServicesList200ResponseInnerBackupsAnyOf1(enabled bool, entries []ManagedServicesList200ResponseInnerBackupsAnyOfEntriesInner) *ManagedServicesList200ResponseInnerBackupsAnyOf1 {
	this := ManagedServicesList200ResponseInnerBackupsAnyOf1{}
	this.Enabled = enabled
	this.Entries = entries
	return &this
}

// NewManagedServicesList200ResponseInnerBackupsAnyOf1WithDefaults instantiates a new ManagedServicesList200ResponseInnerBackupsAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedServicesList200ResponseInnerBackupsAnyOf1WithDefaults() *ManagedServicesList200ResponseInnerBackupsAnyOf1 {
	this := ManagedServicesList200ResponseInnerBackupsAnyOf1{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *ManagedServicesList200ResponseInnerBackupsAnyOf1) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesList200ResponseInnerBackupsAnyOf1) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ManagedServicesList200ResponseInnerBackupsAnyOf1) SetEnabled(v bool) {
	o.Enabled = v
}

// GetEntries returns the Entries field value
func (o *ManagedServicesList200ResponseInnerBackupsAnyOf1) GetEntries() []ManagedServicesList200ResponseInnerBackupsAnyOfEntriesInner {
	if o == nil {
		var ret []ManagedServicesList200ResponseInnerBackupsAnyOfEntriesInner
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesList200ResponseInnerBackupsAnyOf1) GetEntriesOk() ([]ManagedServicesList200ResponseInnerBackupsAnyOfEntriesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *ManagedServicesList200ResponseInnerBackupsAnyOf1) SetEntries(v []ManagedServicesList200ResponseInnerBackupsAnyOfEntriesInner) {
	o.Entries = v
}

func (o ManagedServicesList200ResponseInnerBackupsAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedServicesList200ResponseInnerBackupsAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["entries"] = o.Entries
	return toSerialize, nil
}

func (o *ManagedServicesList200ResponseInnerBackupsAnyOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"entries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedServicesList200ResponseInnerBackupsAnyOf1 := _ManagedServicesList200ResponseInnerBackupsAnyOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedServicesList200ResponseInnerBackupsAnyOf1)

	if err != nil {
		return err
	}

	*o = ManagedServicesList200ResponseInnerBackupsAnyOf1(varManagedServicesList200ResponseInnerBackupsAnyOf1)

	return err
}

type NullableManagedServicesList200ResponseInnerBackupsAnyOf1 struct {
	value *ManagedServicesList200ResponseInnerBackupsAnyOf1
	isSet bool
}

func (v NullableManagedServicesList200ResponseInnerBackupsAnyOf1) Get() *ManagedServicesList200ResponseInnerBackupsAnyOf1 {
	return v.value
}

func (v *NullableManagedServicesList200ResponseInnerBackupsAnyOf1) Set(val *ManagedServicesList200ResponseInnerBackupsAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesList200ResponseInnerBackupsAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesList200ResponseInnerBackupsAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesList200ResponseInnerBackupsAnyOf1(val *ManagedServicesList200ResponseInnerBackupsAnyOf1) *NullableManagedServicesList200ResponseInnerBackupsAnyOf1 {
	return &NullableManagedServicesList200ResponseInnerBackupsAnyOf1{value: val, isSet: true}
}

func (v NullableManagedServicesList200ResponseInnerBackupsAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesList200ResponseInnerBackupsAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
