// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OrganizationsAddOrgMemberRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationsAddOrgMemberRequest{}

// OrganizationsAddOrgMemberRequest struct for OrganizationsAddOrgMemberRequest
type OrganizationsAddOrgMemberRequest struct {
	// Valid email address
	Email string `json:"email"`
	Role  string `json:"role"`
}

type _OrganizationsAddOrgMemberRequest OrganizationsAddOrgMemberRequest

// NewOrganizationsAddOrgMemberRequest instantiates a new OrganizationsAddOrgMemberRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationsAddOrgMemberRequest(email string, role string) *OrganizationsAddOrgMemberRequest {
	this := OrganizationsAddOrgMemberRequest{}
	this.Email = email
	this.Role = role
	return &this
}

// NewOrganizationsAddOrgMemberRequestWithDefaults instantiates a new OrganizationsAddOrgMemberRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationsAddOrgMemberRequestWithDefaults() *OrganizationsAddOrgMemberRequest {
	this := OrganizationsAddOrgMemberRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *OrganizationsAddOrgMemberRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *OrganizationsAddOrgMemberRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *OrganizationsAddOrgMemberRequest) SetEmail(v string) {
	o.Email = v
}

// GetRole returns the Role field value
func (o *OrganizationsAddOrgMemberRequest) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *OrganizationsAddOrgMemberRequest) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *OrganizationsAddOrgMemberRequest) SetRole(v string) {
	o.Role = v
}

func (o OrganizationsAddOrgMemberRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationsAddOrgMemberRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *OrganizationsAddOrgMemberRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationsAddOrgMemberRequest := _OrganizationsAddOrgMemberRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationsAddOrgMemberRequest)

	if err != nil {
		return err
	}

	*o = OrganizationsAddOrgMemberRequest(varOrganizationsAddOrgMemberRequest)

	return err
}

type NullableOrganizationsAddOrgMemberRequest struct {
	value *OrganizationsAddOrgMemberRequest
	isSet bool
}

func (v NullableOrganizationsAddOrgMemberRequest) Get() *OrganizationsAddOrgMemberRequest {
	return v.value
}

func (v *NullableOrganizationsAddOrgMemberRequest) Set(val *OrganizationsAddOrgMemberRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationsAddOrgMemberRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationsAddOrgMemberRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationsAddOrgMemberRequest(val *OrganizationsAddOrgMemberRequest) *NullableOrganizationsAddOrgMemberRequest {
	return &NullableOrganizationsAddOrgMemberRequest{value: val, isSet: true}
}

func (v NullableOrganizationsAddOrgMemberRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationsAddOrgMemberRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
