// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the TeamsMigrateTeamToOrgRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TeamsMigrateTeamToOrgRequest{}

// TeamsMigrateTeamToOrgRequest struct for TeamsMigrateTeamToOrgRequest
type TeamsMigrateTeamToOrgRequest struct {
	// The unique identifier of the organization where the team will be moved.
	OrganizationId *string `json:"organizationId,omitempty"`
	// (Default: false) Set to true to force migration despite membership mismatches. Warning: Users not belonging to the target organization will be stripped from the team.
	Force *bool `json:"force,omitempty"`
}

// NewTeamsMigrateTeamToOrgRequest instantiates a new TeamsMigrateTeamToOrgRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamsMigrateTeamToOrgRequest() *TeamsMigrateTeamToOrgRequest {
	this := TeamsMigrateTeamToOrgRequest{}
	return &this
}

// NewTeamsMigrateTeamToOrgRequestWithDefaults instantiates a new TeamsMigrateTeamToOrgRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamsMigrateTeamToOrgRequestWithDefaults() *TeamsMigrateTeamToOrgRequest {
	this := TeamsMigrateTeamToOrgRequest{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *TeamsMigrateTeamToOrgRequest) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamsMigrateTeamToOrgRequest) GetOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *TeamsMigrateTeamToOrgRequest) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *TeamsMigrateTeamToOrgRequest) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetForce returns the Force field value if set, zero value otherwise.
func (o *TeamsMigrateTeamToOrgRequest) GetForce() bool {
	if o == nil || IsNil(o.Force) {
		var ret bool
		return ret
	}
	return *o.Force
}

// GetForceOk returns a tuple with the Force field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamsMigrateTeamToOrgRequest) GetForceOk() (*bool, bool) {
	if o == nil || IsNil(o.Force) {
		return nil, false
	}
	return o.Force, true
}

// HasForce returns a boolean if a field has been set.
func (o *TeamsMigrateTeamToOrgRequest) HasForce() bool {
	if o != nil && !IsNil(o.Force) {
		return true
	}

	return false
}

// SetForce gets a reference to the given bool and assigns it to the Force field.
func (o *TeamsMigrateTeamToOrgRequest) SetForce(v bool) {
	o.Force = &v
}

func (o TeamsMigrateTeamToOrgRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TeamsMigrateTeamToOrgRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if !IsNil(o.Force) {
		toSerialize["force"] = o.Force
	}
	return toSerialize, nil
}

type NullableTeamsMigrateTeamToOrgRequest struct {
	value *TeamsMigrateTeamToOrgRequest
	isSet bool
}

func (v NullableTeamsMigrateTeamToOrgRequest) Get() *TeamsMigrateTeamToOrgRequest {
	return v.value
}

func (v *NullableTeamsMigrateTeamToOrgRequest) Set(val *TeamsMigrateTeamToOrgRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamsMigrateTeamToOrgRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamsMigrateTeamToOrgRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamsMigrateTeamToOrgRequest(val *TeamsMigrateTeamToOrgRequest) *NullableTeamsMigrateTeamToOrgRequest {
	return &NullableTeamsMigrateTeamToOrgRequest{value: val, isSet: true}
}

func (v NullableTeamsMigrateTeamToOrgRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamsMigrateTeamToOrgRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
