// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the WorkspacesUpdateWorkspaceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspacesUpdateWorkspaceRequest{}

// WorkspacesUpdateWorkspaceRequest struct for WorkspacesUpdateWorkspaceRequest
type WorkspacesUpdateWorkspaceRequest struct {
	PlanId     *int           `json:"planId,omitempty"`
	BaseImage  *string        `json:"baseImage,omitempty"`
	Name       *string        `json:"name,omitempty"`
	Replicas   *int           `json:"replicas,omitempty"`
	VpnConfig  NullableString `json:"vpnConfig,omitempty"`
	Restricted *bool          `json:"restricted,omitempty"`
}

// NewWorkspacesUpdateWorkspaceRequest instantiates a new WorkspacesUpdateWorkspaceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspacesUpdateWorkspaceRequest() *WorkspacesUpdateWorkspaceRequest {
	this := WorkspacesUpdateWorkspaceRequest{}
	return &this
}

// NewWorkspacesUpdateWorkspaceRequestWithDefaults instantiates a new WorkspacesUpdateWorkspaceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspacesUpdateWorkspaceRequestWithDefaults() *WorkspacesUpdateWorkspaceRequest {
	this := WorkspacesUpdateWorkspaceRequest{}
	return &this
}

// GetPlanId returns the PlanId field value if set, zero value otherwise.
func (o *WorkspacesUpdateWorkspaceRequest) GetPlanId() int {
	if o == nil || IsNil(o.PlanId) {
		var ret int
		return ret
	}
	return *o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspacesUpdateWorkspaceRequest) GetPlanIdOk() (*int, bool) {
	if o == nil || IsNil(o.PlanId) {
		return nil, false
	}
	return o.PlanId, true
}

// HasPlanId returns a boolean if a field has been set.
func (o *WorkspacesUpdateWorkspaceRequest) HasPlanId() bool {
	if o != nil && !IsNil(o.PlanId) {
		return true
	}

	return false
}

// SetPlanId gets a reference to the given int and assigns it to the PlanId field.
func (o *WorkspacesUpdateWorkspaceRequest) SetPlanId(v int) {
	o.PlanId = &v
}

// GetBaseImage returns the BaseImage field value if set, zero value otherwise.
func (o *WorkspacesUpdateWorkspaceRequest) GetBaseImage() string {
	if o == nil || IsNil(o.BaseImage) {
		var ret string
		return ret
	}
	return *o.BaseImage
}

// GetBaseImageOk returns a tuple with the BaseImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspacesUpdateWorkspaceRequest) GetBaseImageOk() (*string, bool) {
	if o == nil || IsNil(o.BaseImage) {
		return nil, false
	}
	return o.BaseImage, true
}

// HasBaseImage returns a boolean if a field has been set.
func (o *WorkspacesUpdateWorkspaceRequest) HasBaseImage() bool {
	if o != nil && !IsNil(o.BaseImage) {
		return true
	}

	return false
}

// SetBaseImage gets a reference to the given string and assigns it to the BaseImage field.
func (o *WorkspacesUpdateWorkspaceRequest) SetBaseImage(v string) {
	o.BaseImage = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *WorkspacesUpdateWorkspaceRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspacesUpdateWorkspaceRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *WorkspacesUpdateWorkspaceRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *WorkspacesUpdateWorkspaceRequest) SetName(v string) {
	o.Name = &v
}

// GetReplicas returns the Replicas field value if set, zero value otherwise.
func (o *WorkspacesUpdateWorkspaceRequest) GetReplicas() int {
	if o == nil || IsNil(o.Replicas) {
		var ret int
		return ret
	}
	return *o.Replicas
}

// GetReplicasOk returns a tuple with the Replicas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspacesUpdateWorkspaceRequest) GetReplicasOk() (*int, bool) {
	if o == nil || IsNil(o.Replicas) {
		return nil, false
	}
	return o.Replicas, true
}

// HasReplicas returns a boolean if a field has been set.
func (o *WorkspacesUpdateWorkspaceRequest) HasReplicas() bool {
	if o != nil && !IsNil(o.Replicas) {
		return true
	}

	return false
}

// SetReplicas gets a reference to the given int and assigns it to the Replicas field.
func (o *WorkspacesUpdateWorkspaceRequest) SetReplicas(v int) {
	o.Replicas = &v
}

// GetVpnConfig returns the VpnConfig field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkspacesUpdateWorkspaceRequest) GetVpnConfig() string {
	if o == nil || IsNil(o.VpnConfig.Get()) {
		var ret string
		return ret
	}
	return *o.VpnConfig.Get()
}

// GetVpnConfigOk returns a tuple with the VpnConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkspacesUpdateWorkspaceRequest) GetVpnConfigOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VpnConfig.Get(), o.VpnConfig.IsSet()
}

// HasVpnConfig returns a boolean if a field has been set.
func (o *WorkspacesUpdateWorkspaceRequest) HasVpnConfig() bool {
	if o != nil && o.VpnConfig.IsSet() {
		return true
	}

	return false
}

// SetVpnConfig gets a reference to the given NullableString and assigns it to the VpnConfig field.
func (o *WorkspacesUpdateWorkspaceRequest) SetVpnConfig(v string) {
	o.VpnConfig.Set(&v)
}

// SetVpnConfigNil sets the value for VpnConfig to be an explicit nil
func (o *WorkspacesUpdateWorkspaceRequest) SetVpnConfigNil() {
	o.VpnConfig.Set(nil)
}

// UnsetVpnConfig ensures that no value is present for VpnConfig, not even an explicit nil
func (o *WorkspacesUpdateWorkspaceRequest) UnsetVpnConfig() {
	o.VpnConfig.Unset()
}

// GetRestricted returns the Restricted field value if set, zero value otherwise.
func (o *WorkspacesUpdateWorkspaceRequest) GetRestricted() bool {
	if o == nil || IsNil(o.Restricted) {
		var ret bool
		return ret
	}
	return *o.Restricted
}

// GetRestrictedOk returns a tuple with the Restricted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspacesUpdateWorkspaceRequest) GetRestrictedOk() (*bool, bool) {
	if o == nil || IsNil(o.Restricted) {
		return nil, false
	}
	return o.Restricted, true
}

// HasRestricted returns a boolean if a field has been set.
func (o *WorkspacesUpdateWorkspaceRequest) HasRestricted() bool {
	if o != nil && !IsNil(o.Restricted) {
		return true
	}

	return false
}

// SetRestricted gets a reference to the given bool and assigns it to the Restricted field.
func (o *WorkspacesUpdateWorkspaceRequest) SetRestricted(v bool) {
	o.Restricted = &v
}

func (o WorkspacesUpdateWorkspaceRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspacesUpdateWorkspaceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PlanId) {
		toSerialize["planId"] = o.PlanId
	}
	if !IsNil(o.BaseImage) {
		toSerialize["baseImage"] = o.BaseImage
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Replicas) {
		toSerialize["replicas"] = o.Replicas
	}
	if o.VpnConfig.IsSet() {
		toSerialize["vpnConfig"] = o.VpnConfig.Get()
	}
	if !IsNil(o.Restricted) {
		toSerialize["restricted"] = o.Restricted
	}
	return toSerialize, nil
}

type NullableWorkspacesUpdateWorkspaceRequest struct {
	value *WorkspacesUpdateWorkspaceRequest
	isSet bool
}

func (v NullableWorkspacesUpdateWorkspaceRequest) Get() *WorkspacesUpdateWorkspaceRequest {
	return v.value
}

func (v *NullableWorkspacesUpdateWorkspaceRequest) Set(val *WorkspacesUpdateWorkspaceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspacesUpdateWorkspaceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspacesUpdateWorkspaceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspacesUpdateWorkspaceRequest(val *WorkspacesUpdateWorkspaceRequest) *NullableWorkspacesUpdateWorkspaceRequest {
	return &NullableWorkspacesUpdateWorkspaceRequest{value: val, isSet: true}
}

func (v NullableWorkspacesUpdateWorkspaceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspacesUpdateWorkspaceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
