// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ManagedServicesCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedServicesCreateRequest{}

// ManagedServicesCreateRequest struct for ManagedServicesCreateRequest
type ManagedServicesCreateRequest struct {
	Backups     *ManagedServicesCreateRequestBackups        `json:"backups,omitempty"`
	Config      map[string]interface{}                      `json:"config"`
	Provider    ManagedServicesList200ResponseInnerProvider `json:"provider"`
	Name        string                                      `json:"name"`
	Plan        ManagedServicesList200ResponseInnerPlan     `json:"plan"`
	RecoverFrom *ManagedServicesCreateRequestRecoverFrom    `json:"recoverFrom,omitempty"`
	Secrets     map[string]interface{}                      `json:"secrets"`
	TeamId      int                                         `json:"teamId"`
}

type _ManagedServicesCreateRequest ManagedServicesCreateRequest

// NewManagedServicesCreateRequest instantiates a new ManagedServicesCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedServicesCreateRequest(config map[string]interface{}, provider ManagedServicesList200ResponseInnerProvider, name string, plan ManagedServicesList200ResponseInnerPlan, secrets map[string]interface{}, teamId int) *ManagedServicesCreateRequest {
	this := ManagedServicesCreateRequest{}
	this.Config = config
	this.Provider = provider
	this.Name = name
	this.Plan = plan
	this.Secrets = secrets
	this.TeamId = teamId
	return &this
}

// NewManagedServicesCreateRequestWithDefaults instantiates a new ManagedServicesCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedServicesCreateRequestWithDefaults() *ManagedServicesCreateRequest {
	this := ManagedServicesCreateRequest{}
	return &this
}

// GetBackups returns the Backups field value if set, zero value otherwise.
func (o *ManagedServicesCreateRequest) GetBackups() ManagedServicesCreateRequestBackups {
	if o == nil || IsNil(o.Backups) {
		var ret ManagedServicesCreateRequestBackups
		return ret
	}
	return *o.Backups
}

// GetBackupsOk returns a tuple with the Backups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateRequest) GetBackupsOk() (*ManagedServicesCreateRequestBackups, bool) {
	if o == nil || IsNil(o.Backups) {
		return nil, false
	}
	return o.Backups, true
}

// HasBackups returns a boolean if a field has been set.
func (o *ManagedServicesCreateRequest) HasBackups() bool {
	if o != nil && !IsNil(o.Backups) {
		return true
	}

	return false
}

// SetBackups gets a reference to the given ManagedServicesCreateRequestBackups and assigns it to the Backups field.
func (o *ManagedServicesCreateRequest) SetBackups(v ManagedServicesCreateRequestBackups) {
	o.Backups = &v
}

// GetConfig returns the Config field value
func (o *ManagedServicesCreateRequest) GetConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateRequest) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// SetConfig sets field value
func (o *ManagedServicesCreateRequest) SetConfig(v map[string]interface{}) {
	o.Config = v
}

// GetProvider returns the Provider field value
func (o *ManagedServicesCreateRequest) GetProvider() ManagedServicesList200ResponseInnerProvider {
	if o == nil {
		var ret ManagedServicesList200ResponseInnerProvider
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateRequest) GetProviderOk() (*ManagedServicesList200ResponseInnerProvider, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *ManagedServicesCreateRequest) SetProvider(v ManagedServicesList200ResponseInnerProvider) {
	o.Provider = v
}

// GetName returns the Name field value
func (o *ManagedServicesCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ManagedServicesCreateRequest) SetName(v string) {
	o.Name = v
}

// GetPlan returns the Plan field value
func (o *ManagedServicesCreateRequest) GetPlan() ManagedServicesList200ResponseInnerPlan {
	if o == nil {
		var ret ManagedServicesList200ResponseInnerPlan
		return ret
	}

	return o.Plan
}

// GetPlanOk returns a tuple with the Plan field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateRequest) GetPlanOk() (*ManagedServicesList200ResponseInnerPlan, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plan, true
}

// SetPlan sets field value
func (o *ManagedServicesCreateRequest) SetPlan(v ManagedServicesList200ResponseInnerPlan) {
	o.Plan = v
}

// GetRecoverFrom returns the RecoverFrom field value if set, zero value otherwise.
func (o *ManagedServicesCreateRequest) GetRecoverFrom() ManagedServicesCreateRequestRecoverFrom {
	if o == nil || IsNil(o.RecoverFrom) {
		var ret ManagedServicesCreateRequestRecoverFrom
		return ret
	}
	return *o.RecoverFrom
}

// GetRecoverFromOk returns a tuple with the RecoverFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateRequest) GetRecoverFromOk() (*ManagedServicesCreateRequestRecoverFrom, bool) {
	if o == nil || IsNil(o.RecoverFrom) {
		return nil, false
	}
	return o.RecoverFrom, true
}

// HasRecoverFrom returns a boolean if a field has been set.
func (o *ManagedServicesCreateRequest) HasRecoverFrom() bool {
	if o != nil && !IsNil(o.RecoverFrom) {
		return true
	}

	return false
}

// SetRecoverFrom gets a reference to the given ManagedServicesCreateRequestRecoverFrom and assigns it to the RecoverFrom field.
func (o *ManagedServicesCreateRequest) SetRecoverFrom(v ManagedServicesCreateRequestRecoverFrom) {
	o.RecoverFrom = &v
}

// GetSecrets returns the Secrets field value
func (o *ManagedServicesCreateRequest) GetSecrets() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateRequest) GetSecretsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Secrets, true
}

// SetSecrets sets field value
func (o *ManagedServicesCreateRequest) SetSecrets(v map[string]interface{}) {
	o.Secrets = v
}

// GetTeamId returns the TeamId field value
func (o *ManagedServicesCreateRequest) GetTeamId() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateRequest) GetTeamIdOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TeamId, true
}

// SetTeamId sets field value
func (o *ManagedServicesCreateRequest) SetTeamId(v int) {
	o.TeamId = v
}

func (o ManagedServicesCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedServicesCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Backups) {
		toSerialize["backups"] = o.Backups
	}
	toSerialize["config"] = o.Config
	toSerialize["provider"] = o.Provider
	toSerialize["name"] = o.Name
	toSerialize["plan"] = o.Plan
	if !IsNil(o.RecoverFrom) {
		toSerialize["recoverFrom"] = o.RecoverFrom
	}
	toSerialize["secrets"] = o.Secrets
	toSerialize["teamId"] = o.TeamId
	return toSerialize, nil
}

func (o *ManagedServicesCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"config",
		"provider",
		"name",
		"plan",
		"secrets",
		"teamId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedServicesCreateRequest := _ManagedServicesCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedServicesCreateRequest)

	if err != nil {
		return err
	}

	*o = ManagedServicesCreateRequest(varManagedServicesCreateRequest)

	return err
}

type NullableManagedServicesCreateRequest struct {
	value *ManagedServicesCreateRequest
	isSet bool
}

func (v NullableManagedServicesCreateRequest) Get() *ManagedServicesCreateRequest {
	return v.value
}

func (v *NullableManagedServicesCreateRequest) Set(val *ManagedServicesCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesCreateRequest(val *ManagedServicesCreateRequest) *NullableManagedServicesCreateRequest {
	return &NullableManagedServicesCreateRequest{value: val, isSet: true}
}

func (v NullableManagedServicesCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
