// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TeamsChangeRoleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TeamsChangeRoleRequest{}

// TeamsChangeRoleRequest struct for TeamsChangeRoleRequest
type TeamsChangeRoleRequest struct {
	// The role assigned to the team. 0 = Admin, 1 = Member.
	Role int `json:"role"`
}

type _TeamsChangeRoleRequest TeamsChangeRoleRequest

// NewTeamsChangeRoleRequest instantiates a new TeamsChangeRoleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamsChangeRoleRequest(role int) *TeamsChangeRoleRequest {
	this := TeamsChangeRoleRequest{}
	this.Role = role
	return &this
}

// NewTeamsChangeRoleRequestWithDefaults instantiates a new TeamsChangeRoleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamsChangeRoleRequestWithDefaults() *TeamsChangeRoleRequest {
	this := TeamsChangeRoleRequest{}
	return &this
}

// GetRole returns the Role field value
func (o *TeamsChangeRoleRequest) GetRole() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *TeamsChangeRoleRequest) GetRoleOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *TeamsChangeRoleRequest) SetRole(v int) {
	o.Role = v
}

func (o TeamsChangeRoleRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TeamsChangeRoleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *TeamsChangeRoleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTeamsChangeRoleRequest := _TeamsChangeRoleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTeamsChangeRoleRequest)

	if err != nil {
		return err
	}

	*o = TeamsChangeRoleRequest(varTeamsChangeRoleRequest)

	return err
}

type NullableTeamsChangeRoleRequest struct {
	value *TeamsChangeRoleRequest
	isSet bool
}

func (v NullableTeamsChangeRoleRequest) Get() *TeamsChangeRoleRequest {
	return v.value
}

func (v *NullableTeamsChangeRoleRequest) Set(val *TeamsChangeRoleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamsChangeRoleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamsChangeRoleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamsChangeRoleRequest(val *TeamsChangeRoleRequest) *NullableTeamsChangeRoleRequest {
	return &NullableTeamsChangeRoleRequest{value: val, isSet: true}
}

func (v NullableTeamsChangeRoleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamsChangeRoleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
