// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ManagedServicesList200ResponseInnerStatusAnyOf8 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedServicesList200ResponseInnerStatusAnyOf8{}

// ManagedServicesList200ResponseInnerStatusAnyOf8 struct for ManagedServicesList200ResponseInnerStatusAnyOf8
type ManagedServicesList200ResponseInnerStatusAnyOf8 struct {
	State string `json:"state"`
}

type _ManagedServicesList200ResponseInnerStatusAnyOf8 ManagedServicesList200ResponseInnerStatusAnyOf8

// NewManagedServicesList200ResponseInnerStatusAnyOf8 instantiates a new ManagedServicesList200ResponseInnerStatusAnyOf8 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedServicesList200ResponseInnerStatusAnyOf8(state string) *ManagedServicesList200ResponseInnerStatusAnyOf8 {
	this := ManagedServicesList200ResponseInnerStatusAnyOf8{}
	this.State = state
	return &this
}

// NewManagedServicesList200ResponseInnerStatusAnyOf8WithDefaults instantiates a new ManagedServicesList200ResponseInnerStatusAnyOf8 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedServicesList200ResponseInnerStatusAnyOf8WithDefaults() *ManagedServicesList200ResponseInnerStatusAnyOf8 {
	this := ManagedServicesList200ResponseInnerStatusAnyOf8{}
	return &this
}

// GetState returns the State field value
func (o *ManagedServicesList200ResponseInnerStatusAnyOf8) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesList200ResponseInnerStatusAnyOf8) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ManagedServicesList200ResponseInnerStatusAnyOf8) SetState(v string) {
	o.State = v
}

func (o ManagedServicesList200ResponseInnerStatusAnyOf8) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedServicesList200ResponseInnerStatusAnyOf8) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *ManagedServicesList200ResponseInnerStatusAnyOf8) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedServicesList200ResponseInnerStatusAnyOf8 := _ManagedServicesList200ResponseInnerStatusAnyOf8{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedServicesList200ResponseInnerStatusAnyOf8)

	if err != nil {
		return err
	}

	*o = ManagedServicesList200ResponseInnerStatusAnyOf8(varManagedServicesList200ResponseInnerStatusAnyOf8)

	return err
}

type NullableManagedServicesList200ResponseInnerStatusAnyOf8 struct {
	value *ManagedServicesList200ResponseInnerStatusAnyOf8
	isSet bool
}

func (v NullableManagedServicesList200ResponseInnerStatusAnyOf8) Get() *ManagedServicesList200ResponseInnerStatusAnyOf8 {
	return v.value
}

func (v *NullableManagedServicesList200ResponseInnerStatusAnyOf8) Set(val *ManagedServicesList200ResponseInnerStatusAnyOf8) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesList200ResponseInnerStatusAnyOf8) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesList200ResponseInnerStatusAnyOf8) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesList200ResponseInnerStatusAnyOf8(val *ManagedServicesList200ResponseInnerStatusAnyOf8) *NullableManagedServicesList200ResponseInnerStatusAnyOf8 {
	return &NullableManagedServicesList200ResponseInnerStatusAnyOf8{value: val, isSet: true}
}

func (v NullableManagedServicesList200ResponseInnerStatusAnyOf8) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesList200ResponseInnerStatusAnyOf8) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
