// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ManagedServicesCreateRequestBackupsAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedServicesCreateRequestBackupsAnyOf{}

// ManagedServicesCreateRequestBackupsAnyOf struct for ManagedServicesCreateRequestBackupsAnyOf
type ManagedServicesCreateRequestBackupsAnyOf struct {
	Enabled             bool                   `json:"enabled"`
	DeleteRetentionDays int                    `json:"deleteRetentionDays"`
	IntervalH           int                    `json:"intervalH"`
	Config              map[string]interface{} `json:"config"`
	Secrets             map[string]interface{} `json:"secrets"`
}

type _ManagedServicesCreateRequestBackupsAnyOf ManagedServicesCreateRequestBackupsAnyOf

// NewManagedServicesCreateRequestBackupsAnyOf instantiates a new ManagedServicesCreateRequestBackupsAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedServicesCreateRequestBackupsAnyOf(enabled bool, deleteRetentionDays int, intervalH int, config map[string]interface{}, secrets map[string]interface{}) *ManagedServicesCreateRequestBackupsAnyOf {
	this := ManagedServicesCreateRequestBackupsAnyOf{}
	this.Enabled = enabled
	this.DeleteRetentionDays = deleteRetentionDays
	this.IntervalH = intervalH
	this.Config = config
	this.Secrets = secrets
	return &this
}

// NewManagedServicesCreateRequestBackupsAnyOfWithDefaults instantiates a new ManagedServicesCreateRequestBackupsAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedServicesCreateRequestBackupsAnyOfWithDefaults() *ManagedServicesCreateRequestBackupsAnyOf {
	this := ManagedServicesCreateRequestBackupsAnyOf{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *ManagedServicesCreateRequestBackupsAnyOf) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateRequestBackupsAnyOf) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ManagedServicesCreateRequestBackupsAnyOf) SetEnabled(v bool) {
	o.Enabled = v
}

// GetDeleteRetentionDays returns the DeleteRetentionDays field value
func (o *ManagedServicesCreateRequestBackupsAnyOf) GetDeleteRetentionDays() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.DeleteRetentionDays
}

// GetDeleteRetentionDaysOk returns a tuple with the DeleteRetentionDays field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateRequestBackupsAnyOf) GetDeleteRetentionDaysOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeleteRetentionDays, true
}

// SetDeleteRetentionDays sets field value
func (o *ManagedServicesCreateRequestBackupsAnyOf) SetDeleteRetentionDays(v int) {
	o.DeleteRetentionDays = v
}

// GetIntervalH returns the IntervalH field value
func (o *ManagedServicesCreateRequestBackupsAnyOf) GetIntervalH() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.IntervalH
}

// GetIntervalHOk returns a tuple with the IntervalH field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateRequestBackupsAnyOf) GetIntervalHOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntervalH, true
}

// SetIntervalH sets field value
func (o *ManagedServicesCreateRequestBackupsAnyOf) SetIntervalH(v int) {
	o.IntervalH = v
}

// GetConfig returns the Config field value
func (o *ManagedServicesCreateRequestBackupsAnyOf) GetConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateRequestBackupsAnyOf) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// SetConfig sets field value
func (o *ManagedServicesCreateRequestBackupsAnyOf) SetConfig(v map[string]interface{}) {
	o.Config = v
}

// GetSecrets returns the Secrets field value
func (o *ManagedServicesCreateRequestBackupsAnyOf) GetSecrets() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateRequestBackupsAnyOf) GetSecretsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Secrets, true
}

// SetSecrets sets field value
func (o *ManagedServicesCreateRequestBackupsAnyOf) SetSecrets(v map[string]interface{}) {
	o.Secrets = v
}

func (o ManagedServicesCreateRequestBackupsAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedServicesCreateRequestBackupsAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["deleteRetentionDays"] = o.DeleteRetentionDays
	toSerialize["intervalH"] = o.IntervalH
	toSerialize["config"] = o.Config
	toSerialize["secrets"] = o.Secrets
	return toSerialize, nil
}

func (o *ManagedServicesCreateRequestBackupsAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"deleteRetentionDays",
		"intervalH",
		"config",
		"secrets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedServicesCreateRequestBackupsAnyOf := _ManagedServicesCreateRequestBackupsAnyOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedServicesCreateRequestBackupsAnyOf)

	if err != nil {
		return err
	}

	*o = ManagedServicesCreateRequestBackupsAnyOf(varManagedServicesCreateRequestBackupsAnyOf)

	return err
}

type NullableManagedServicesCreateRequestBackupsAnyOf struct {
	value *ManagedServicesCreateRequestBackupsAnyOf
	isSet bool
}

func (v NullableManagedServicesCreateRequestBackupsAnyOf) Get() *ManagedServicesCreateRequestBackupsAnyOf {
	return v.value
}

func (v *NullableManagedServicesCreateRequestBackupsAnyOf) Set(val *ManagedServicesCreateRequestBackupsAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesCreateRequestBackupsAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesCreateRequestBackupsAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesCreateRequestBackupsAnyOf(val *ManagedServicesCreateRequestBackupsAnyOf) *NullableManagedServicesCreateRequestBackupsAnyOf {
	return &NullableManagedServicesCreateRequestBackupsAnyOf{value: val, isSet: true}
}

func (v NullableManagedServicesCreateRequestBackupsAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesCreateRequestBackupsAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
