// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TeamsInviteMemberRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TeamsInviteMemberRequest{}

// TeamsInviteMemberRequest struct for TeamsInviteMemberRequest
type TeamsInviteMemberRequest struct {
	UserEmail string `json:"userEmail"`
	// The role assigned to the team. 0 = Admin, 1 = Member.
	Role int `json:"role"`
}

type _TeamsInviteMemberRequest TeamsInviteMemberRequest

// NewTeamsInviteMemberRequest instantiates a new TeamsInviteMemberRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamsInviteMemberRequest(userEmail string, role int) *TeamsInviteMemberRequest {
	this := TeamsInviteMemberRequest{}
	this.UserEmail = userEmail
	this.Role = role
	return &this
}

// NewTeamsInviteMemberRequestWithDefaults instantiates a new TeamsInviteMemberRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamsInviteMemberRequestWithDefaults() *TeamsInviteMemberRequest {
	this := TeamsInviteMemberRequest{}
	return &this
}

// GetUserEmail returns the UserEmail field value
func (o *TeamsInviteMemberRequest) GetUserEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserEmail
}

// GetUserEmailOk returns a tuple with the UserEmail field value
// and a boolean to check if the value has been set.
func (o *TeamsInviteMemberRequest) GetUserEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserEmail, true
}

// SetUserEmail sets field value
func (o *TeamsInviteMemberRequest) SetUserEmail(v string) {
	o.UserEmail = v
}

// GetRole returns the Role field value
func (o *TeamsInviteMemberRequest) GetRole() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *TeamsInviteMemberRequest) GetRoleOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *TeamsInviteMemberRequest) SetRole(v int) {
	o.Role = v
}

func (o TeamsInviteMemberRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TeamsInviteMemberRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userEmail"] = o.UserEmail
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *TeamsInviteMemberRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userEmail",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTeamsInviteMemberRequest := _TeamsInviteMemberRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTeamsInviteMemberRequest)

	if err != nil {
		return err
	}

	*o = TeamsInviteMemberRequest(varTeamsInviteMemberRequest)

	return err
}

type NullableTeamsInviteMemberRequest struct {
	value *TeamsInviteMemberRequest
	isSet bool
}

func (v NullableTeamsInviteMemberRequest) Get() *TeamsInviteMemberRequest {
	return v.value
}

func (v *NullableTeamsInviteMemberRequest) Set(val *TeamsInviteMemberRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamsInviteMemberRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamsInviteMemberRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamsInviteMemberRequest(val *TeamsInviteMemberRequest) *NullableTeamsInviteMemberRequest {
	return &NullableTeamsInviteMemberRequest{value: val, isSet: true}
}

func (v NullableTeamsInviteMemberRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamsInviteMemberRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
