// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1{}

// ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1 struct for ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1
type ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1 struct {
	Type    string `json:"type"`
	TeamIds []int  `json:"teamIds"`
}

type _ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1 ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1

// NewManagedServicesCreateProviderRequestAnyOfScopeAnyOf1 instantiates a new ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedServicesCreateProviderRequestAnyOfScopeAnyOf1(type_ string, teamIds []int) *ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1 {
	this := ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1{}
	this.Type = type_
	this.TeamIds = teamIds
	return &this
}

// NewManagedServicesCreateProviderRequestAnyOfScopeAnyOf1WithDefaults instantiates a new ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedServicesCreateProviderRequestAnyOfScopeAnyOf1WithDefaults() *ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1 {
	this := ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1{}
	return &this
}

// GetType returns the Type field value
func (o *ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1) SetType(v string) {
	o.Type = v
}

// GetTeamIds returns the TeamIds field value
func (o *ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1) GetTeamIds() []int {
	if o == nil {
		var ret []int
		return ret
	}

	return o.TeamIds
}

// GetTeamIdsOk returns a tuple with the TeamIds field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1) GetTeamIdsOk() ([]int, bool) {
	if o == nil {
		return nil, false
	}
	return o.TeamIds, true
}

// SetTeamIds sets field value
func (o *ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1) SetTeamIds(v []int) {
	o.TeamIds = v
}

func (o ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["teamIds"] = o.TeamIds
	return toSerialize, nil
}

func (o *ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"teamIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedServicesCreateProviderRequestAnyOfScopeAnyOf1 := _ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedServicesCreateProviderRequestAnyOfScopeAnyOf1)

	if err != nil {
		return err
	}

	*o = ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1(varManagedServicesCreateProviderRequestAnyOfScopeAnyOf1)

	return err
}

type NullableManagedServicesCreateProviderRequestAnyOfScopeAnyOf1 struct {
	value *ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1
	isSet bool
}

func (v NullableManagedServicesCreateProviderRequestAnyOfScopeAnyOf1) Get() *ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1 {
	return v.value
}

func (v *NullableManagedServicesCreateProviderRequestAnyOfScopeAnyOf1) Set(val *ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesCreateProviderRequestAnyOfScopeAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesCreateProviderRequestAnyOfScopeAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesCreateProviderRequestAnyOfScopeAnyOf1(val *ManagedServicesCreateProviderRequestAnyOfScopeAnyOf1) *NullableManagedServicesCreateProviderRequestAnyOfScopeAnyOf1 {
	return &NullableManagedServicesCreateProviderRequestAnyOfScopeAnyOf1{value: val, isSet: true}
}

func (v NullableManagedServicesCreateProviderRequestAnyOfScopeAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesCreateProviderRequestAnyOfScopeAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
