/*
Codesphere Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DomainsGetDomain404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainsGetDomain404Response{}

// DomainsGetDomain404Response struct for DomainsGetDomain404Response
type DomainsGetDomain404Response struct {
	Status  int     `json:"status"`
	Title   string  `json:"title"`
	Details *string `json:"details,omitempty"`
	TraceId string  `json:"traceId"`
}

type _DomainsGetDomain404Response DomainsGetDomain404Response

// NewDomainsGetDomain404Response instantiates a new DomainsGetDomain404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainsGetDomain404Response(status int, title string, traceId string) *DomainsGetDomain404Response {
	this := DomainsGetDomain404Response{}
	this.Status = status
	this.Title = title
	this.TraceId = traceId
	return &this
}

// NewDomainsGetDomain404ResponseWithDefaults instantiates a new DomainsGetDomain404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainsGetDomain404ResponseWithDefaults() *DomainsGetDomain404Response {
	this := DomainsGetDomain404Response{}
	return &this
}

// GetStatus returns the Status field value
func (o *DomainsGetDomain404Response) GetStatus() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DomainsGetDomain404Response) GetStatusOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DomainsGetDomain404Response) SetStatus(v int) {
	o.Status = v
}

// GetTitle returns the Title field value
func (o *DomainsGetDomain404Response) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *DomainsGetDomain404Response) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *DomainsGetDomain404Response) SetTitle(v string) {
	o.Title = v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *DomainsGetDomain404Response) GetDetails() string {
	if o == nil || IsNil(o.Details) {
		var ret string
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainsGetDomain404Response) GetDetailsOk() (*string, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *DomainsGetDomain404Response) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given string and assigns it to the Details field.
func (o *DomainsGetDomain404Response) SetDetails(v string) {
	o.Details = &v
}

// GetTraceId returns the TraceId field value
func (o *DomainsGetDomain404Response) GetTraceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TraceId
}

// GetTraceIdOk returns a tuple with the TraceId field value
// and a boolean to check if the value has been set.
func (o *DomainsGetDomain404Response) GetTraceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TraceId, true
}

// SetTraceId sets field value
func (o *DomainsGetDomain404Response) SetTraceId(v string) {
	o.TraceId = v
}

func (o DomainsGetDomain404Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainsGetDomain404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["title"] = o.Title
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	toSerialize["traceId"] = o.TraceId
	return toSerialize, nil
}

func (o *DomainsGetDomain404Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"title",
		"traceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainsGetDomain404Response := _DomainsGetDomain404Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDomainsGetDomain404Response)

	if err != nil {
		return err
	}

	*o = DomainsGetDomain404Response(varDomainsGetDomain404Response)

	return err
}

type NullableDomainsGetDomain404Response struct {
	value *DomainsGetDomain404Response
	isSet bool
}

func (v NullableDomainsGetDomain404Response) Get() *DomainsGetDomain404Response {
	return v.value
}

func (v *NullableDomainsGetDomain404Response) Set(val *DomainsGetDomain404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainsGetDomain404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainsGetDomain404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainsGetDomain404Response(val *DomainsGetDomain404Response) *NullableDomainsGetDomain404Response {
	return &NullableDomainsGetDomain404Response{value: val, isSet: true}
}

func (v NullableDomainsGetDomain404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainsGetDomain404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
