// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TeamsInviteMember402Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TeamsInviteMember402Response{}

// TeamsInviteMember402Response struct for TeamsInviteMember402Response
type TeamsInviteMember402Response struct {
	Status  int     `json:"status"`
	Title   string  `json:"title"`
	Detail  *string `json:"detail,omitempty"`
	TraceId string  `json:"traceId"`
}

type _TeamsInviteMember402Response TeamsInviteMember402Response

// NewTeamsInviteMember402Response instantiates a new TeamsInviteMember402Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamsInviteMember402Response(status int, title string, traceId string) *TeamsInviteMember402Response {
	this := TeamsInviteMember402Response{}
	this.Status = status
	this.Title = title
	this.TraceId = traceId
	return &this
}

// NewTeamsInviteMember402ResponseWithDefaults instantiates a new TeamsInviteMember402Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamsInviteMember402ResponseWithDefaults() *TeamsInviteMember402Response {
	this := TeamsInviteMember402Response{}
	return &this
}

// GetStatus returns the Status field value
func (o *TeamsInviteMember402Response) GetStatus() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TeamsInviteMember402Response) GetStatusOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TeamsInviteMember402Response) SetStatus(v int) {
	o.Status = v
}

// GetTitle returns the Title field value
func (o *TeamsInviteMember402Response) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *TeamsInviteMember402Response) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *TeamsInviteMember402Response) SetTitle(v string) {
	o.Title = v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *TeamsInviteMember402Response) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamsInviteMember402Response) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *TeamsInviteMember402Response) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *TeamsInviteMember402Response) SetDetail(v string) {
	o.Detail = &v
}

// GetTraceId returns the TraceId field value
func (o *TeamsInviteMember402Response) GetTraceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TraceId
}

// GetTraceIdOk returns a tuple with the TraceId field value
// and a boolean to check if the value has been set.
func (o *TeamsInviteMember402Response) GetTraceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TraceId, true
}

// SetTraceId sets field value
func (o *TeamsInviteMember402Response) SetTraceId(v string) {
	o.TraceId = v
}

func (o TeamsInviteMember402Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TeamsInviteMember402Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["title"] = o.Title
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	toSerialize["traceId"] = o.TraceId
	return toSerialize, nil
}

func (o *TeamsInviteMember402Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"title",
		"traceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTeamsInviteMember402Response := _TeamsInviteMember402Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTeamsInviteMember402Response)

	if err != nil {
		return err
	}

	*o = TeamsInviteMember402Response(varTeamsInviteMember402Response)

	return err
}

type NullableTeamsInviteMember402Response struct {
	value *TeamsInviteMember402Response
	isSet bool
}

func (v NullableTeamsInviteMember402Response) Get() *TeamsInviteMember402Response {
	return v.value
}

func (v *NullableTeamsInviteMember402Response) Set(val *TeamsInviteMember402Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamsInviteMember402Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamsInviteMember402Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamsInviteMember402Response(val *TeamsInviteMember402Response) *NullableTeamsInviteMember402Response {
	return &NullableTeamsInviteMember402Response{value: val, isSet: true}
}

func (v NullableTeamsInviteMember402Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamsInviteMember402Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
