// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the WorkspacesPipelineStatus200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspacesPipelineStatus200ResponseInner{}

// WorkspacesPipelineStatus200ResponseInner struct for WorkspacesPipelineStatus200ResponseInner
type WorkspacesPipelineStatus200ResponseInner struct {
	State      string                                               `json:"state"`
	StartedAt  *time.Time                                           `json:"startedAt,omitempty"`
	FinishedAt *time.Time                                           `json:"finishedAt,omitempty"`
	Steps      []WorkspacesPipelineStatus200ResponseInnerStepsInner `json:"steps"`
	Replica    string                                               `json:"replica"`
	Server     string                                               `json:"server" validate:"regexp=^(?:[a-z]|[a-z][-a-z0-9]{0,30}[a-z0-9])$"`
}

type _WorkspacesPipelineStatus200ResponseInner WorkspacesPipelineStatus200ResponseInner

// NewWorkspacesPipelineStatus200ResponseInner instantiates a new WorkspacesPipelineStatus200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspacesPipelineStatus200ResponseInner(state string, steps []WorkspacesPipelineStatus200ResponseInnerStepsInner, replica string, server string) *WorkspacesPipelineStatus200ResponseInner {
	this := WorkspacesPipelineStatus200ResponseInner{}
	this.State = state
	this.Steps = steps
	this.Replica = replica
	this.Server = server
	return &this
}

// NewWorkspacesPipelineStatus200ResponseInnerWithDefaults instantiates a new WorkspacesPipelineStatus200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspacesPipelineStatus200ResponseInnerWithDefaults() *WorkspacesPipelineStatus200ResponseInner {
	this := WorkspacesPipelineStatus200ResponseInner{}
	return &this
}

// GetState returns the State field value
func (o *WorkspacesPipelineStatus200ResponseInner) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *WorkspacesPipelineStatus200ResponseInner) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *WorkspacesPipelineStatus200ResponseInner) SetState(v string) {
	o.State = v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *WorkspacesPipelineStatus200ResponseInner) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspacesPipelineStatus200ResponseInner) GetStartedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *WorkspacesPipelineStatus200ResponseInner) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given time.Time and assigns it to the StartedAt field.
func (o *WorkspacesPipelineStatus200ResponseInner) SetStartedAt(v time.Time) {
	o.StartedAt = &v
}

// GetFinishedAt returns the FinishedAt field value if set, zero value otherwise.
func (o *WorkspacesPipelineStatus200ResponseInner) GetFinishedAt() time.Time {
	if o == nil || IsNil(o.FinishedAt) {
		var ret time.Time
		return ret
	}
	return *o.FinishedAt
}

// GetFinishedAtOk returns a tuple with the FinishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspacesPipelineStatus200ResponseInner) GetFinishedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FinishedAt) {
		return nil, false
	}
	return o.FinishedAt, true
}

// HasFinishedAt returns a boolean if a field has been set.
func (o *WorkspacesPipelineStatus200ResponseInner) HasFinishedAt() bool {
	if o != nil && !IsNil(o.FinishedAt) {
		return true
	}

	return false
}

// SetFinishedAt gets a reference to the given time.Time and assigns it to the FinishedAt field.
func (o *WorkspacesPipelineStatus200ResponseInner) SetFinishedAt(v time.Time) {
	o.FinishedAt = &v
}

// GetSteps returns the Steps field value
func (o *WorkspacesPipelineStatus200ResponseInner) GetSteps() []WorkspacesPipelineStatus200ResponseInnerStepsInner {
	if o == nil {
		var ret []WorkspacesPipelineStatus200ResponseInnerStepsInner
		return ret
	}

	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value
// and a boolean to check if the value has been set.
func (o *WorkspacesPipelineStatus200ResponseInner) GetStepsOk() ([]WorkspacesPipelineStatus200ResponseInnerStepsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Steps, true
}

// SetSteps sets field value
func (o *WorkspacesPipelineStatus200ResponseInner) SetSteps(v []WorkspacesPipelineStatus200ResponseInnerStepsInner) {
	o.Steps = v
}

// GetReplica returns the Replica field value
func (o *WorkspacesPipelineStatus200ResponseInner) GetReplica() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Replica
}

// GetReplicaOk returns a tuple with the Replica field value
// and a boolean to check if the value has been set.
func (o *WorkspacesPipelineStatus200ResponseInner) GetReplicaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Replica, true
}

// SetReplica sets field value
func (o *WorkspacesPipelineStatus200ResponseInner) SetReplica(v string) {
	o.Replica = v
}

// GetServer returns the Server field value
func (o *WorkspacesPipelineStatus200ResponseInner) GetServer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Server
}

// GetServerOk returns a tuple with the Server field value
// and a boolean to check if the value has been set.
func (o *WorkspacesPipelineStatus200ResponseInner) GetServerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Server, true
}

// SetServer sets field value
func (o *WorkspacesPipelineStatus200ResponseInner) SetServer(v string) {
	o.Server = v
}

func (o WorkspacesPipelineStatus200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspacesPipelineStatus200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	if !IsNil(o.StartedAt) {
		toSerialize["startedAt"] = o.StartedAt
	}
	if !IsNil(o.FinishedAt) {
		toSerialize["finishedAt"] = o.FinishedAt
	}
	toSerialize["steps"] = o.Steps
	toSerialize["replica"] = o.Replica
	toSerialize["server"] = o.Server
	return toSerialize, nil
}

func (o *WorkspacesPipelineStatus200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
		"steps",
		"replica",
		"server",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkspacesPipelineStatus200ResponseInner := _WorkspacesPipelineStatus200ResponseInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkspacesPipelineStatus200ResponseInner)

	if err != nil {
		return err
	}

	*o = WorkspacesPipelineStatus200ResponseInner(varWorkspacesPipelineStatus200ResponseInner)

	return err
}

type NullableWorkspacesPipelineStatus200ResponseInner struct {
	value *WorkspacesPipelineStatus200ResponseInner
	isSet bool
}

func (v NullableWorkspacesPipelineStatus200ResponseInner) Get() *WorkspacesPipelineStatus200ResponseInner {
	return v.value
}

func (v *NullableWorkspacesPipelineStatus200ResponseInner) Set(val *WorkspacesPipelineStatus200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspacesPipelineStatus200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspacesPipelineStatus200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspacesPipelineStatus200ResponseInner(val *WorkspacesPipelineStatus200ResponseInner) *NullableWorkspacesPipelineStatus200ResponseInner {
	return &NullableWorkspacesPipelineStatus200ResponseInner{value: val, isSet: true}
}

func (v NullableWorkspacesPipelineStatus200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspacesPipelineStatus200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
