// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ManagedServicesCreateRequestBackupsAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedServicesCreateRequestBackupsAnyOf1{}

// ManagedServicesCreateRequestBackupsAnyOf1 struct for ManagedServicesCreateRequestBackupsAnyOf1
type ManagedServicesCreateRequestBackupsAnyOf1 struct {
	Enabled bool `json:"enabled"`
}

type _ManagedServicesCreateRequestBackupsAnyOf1 ManagedServicesCreateRequestBackupsAnyOf1

// NewManagedServicesCreateRequestBackupsAnyOf1 instantiates a new ManagedServicesCreateRequestBackupsAnyOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedServicesCreateRequestBackupsAnyOf1(enabled bool) *ManagedServicesCreateRequestBackupsAnyOf1 {
	this := ManagedServicesCreateRequestBackupsAnyOf1{}
	this.Enabled = enabled
	return &this
}

// NewManagedServicesCreateRequestBackupsAnyOf1WithDefaults instantiates a new ManagedServicesCreateRequestBackupsAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedServicesCreateRequestBackupsAnyOf1WithDefaults() *ManagedServicesCreateRequestBackupsAnyOf1 {
	this := ManagedServicesCreateRequestBackupsAnyOf1{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *ManagedServicesCreateRequestBackupsAnyOf1) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesCreateRequestBackupsAnyOf1) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ManagedServicesCreateRequestBackupsAnyOf1) SetEnabled(v bool) {
	o.Enabled = v
}

func (o ManagedServicesCreateRequestBackupsAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedServicesCreateRequestBackupsAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	return toSerialize, nil
}

func (o *ManagedServicesCreateRequestBackupsAnyOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedServicesCreateRequestBackupsAnyOf1 := _ManagedServicesCreateRequestBackupsAnyOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedServicesCreateRequestBackupsAnyOf1)

	if err != nil {
		return err
	}

	*o = ManagedServicesCreateRequestBackupsAnyOf1(varManagedServicesCreateRequestBackupsAnyOf1)

	return err
}

type NullableManagedServicesCreateRequestBackupsAnyOf1 struct {
	value *ManagedServicesCreateRequestBackupsAnyOf1
	isSet bool
}

func (v NullableManagedServicesCreateRequestBackupsAnyOf1) Get() *ManagedServicesCreateRequestBackupsAnyOf1 {
	return v.value
}

func (v *NullableManagedServicesCreateRequestBackupsAnyOf1) Set(val *ManagedServicesCreateRequestBackupsAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesCreateRequestBackupsAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesCreateRequestBackupsAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesCreateRequestBackupsAnyOf1(val *ManagedServicesCreateRequestBackupsAnyOf1) *NullableManagedServicesCreateRequestBackupsAnyOf1 {
	return &NullableManagedServicesCreateRequestBackupsAnyOf1{value: val, isSet: true}
}

func (v NullableManagedServicesCreateRequestBackupsAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesCreateRequestBackupsAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
