// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
	"fmt"
)

// ManagedServicesList200ResponseInnerBackups struct for ManagedServicesList200ResponseInnerBackups
type ManagedServicesList200ResponseInnerBackups struct {
	ManagedServicesList200ResponseInnerBackupsAnyOf  *ManagedServicesList200ResponseInnerBackupsAnyOf
	ManagedServicesList200ResponseInnerBackupsAnyOf1 *ManagedServicesList200ResponseInnerBackupsAnyOf1
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ManagedServicesList200ResponseInnerBackups) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ManagedServicesList200ResponseInnerBackupsAnyOf
	err = json.Unmarshal(data, &dst.ManagedServicesList200ResponseInnerBackupsAnyOf)
	if err == nil {
		jsonManagedServicesList200ResponseInnerBackupsAnyOf, _ := json.Marshal(dst.ManagedServicesList200ResponseInnerBackupsAnyOf)
		if string(jsonManagedServicesList200ResponseInnerBackupsAnyOf) == "{}" { // empty struct
			dst.ManagedServicesList200ResponseInnerBackupsAnyOf = nil
		} else {
			return nil // data stored in dst.ManagedServicesList200ResponseInnerBackupsAnyOf, return on the first match
		}
	} else {
		dst.ManagedServicesList200ResponseInnerBackupsAnyOf = nil
	}

	// try to unmarshal JSON data into ManagedServicesList200ResponseInnerBackupsAnyOf1
	err = json.Unmarshal(data, &dst.ManagedServicesList200ResponseInnerBackupsAnyOf1)
	if err == nil {
		jsonManagedServicesList200ResponseInnerBackupsAnyOf1, _ := json.Marshal(dst.ManagedServicesList200ResponseInnerBackupsAnyOf1)
		if string(jsonManagedServicesList200ResponseInnerBackupsAnyOf1) == "{}" { // empty struct
			dst.ManagedServicesList200ResponseInnerBackupsAnyOf1 = nil
		} else {
			return nil // data stored in dst.ManagedServicesList200ResponseInnerBackupsAnyOf1, return on the first match
		}
	} else {
		dst.ManagedServicesList200ResponseInnerBackupsAnyOf1 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ManagedServicesList200ResponseInnerBackups)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ManagedServicesList200ResponseInnerBackups) MarshalJSON() ([]byte, error) {
	if src.ManagedServicesList200ResponseInnerBackupsAnyOf != nil {
		return json.Marshal(&src.ManagedServicesList200ResponseInnerBackupsAnyOf)
	}

	if src.ManagedServicesList200ResponseInnerBackupsAnyOf1 != nil {
		return json.Marshal(&src.ManagedServicesList200ResponseInnerBackupsAnyOf1)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableManagedServicesList200ResponseInnerBackups struct {
	value *ManagedServicesList200ResponseInnerBackups
	isSet bool
}

func (v NullableManagedServicesList200ResponseInnerBackups) Get() *ManagedServicesList200ResponseInnerBackups {
	return v.value
}

func (v *NullableManagedServicesList200ResponseInnerBackups) Set(val *ManagedServicesList200ResponseInnerBackups) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesList200ResponseInnerBackups) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesList200ResponseInnerBackups) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesList200ResponseInnerBackups(val *ManagedServicesList200ResponseInnerBackups) *NullableManagedServicesList200ResponseInnerBackups {
	return &NullableManagedServicesList200ResponseInnerBackups{value: val, isSet: true}
}

func (v NullableManagedServicesList200ResponseInnerBackups) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesList200ResponseInnerBackups) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
