// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
	"fmt"
)

// ManagedServicesList200ResponseInnerStatus struct for ManagedServicesList200ResponseInnerStatus
type ManagedServicesList200ResponseInnerStatus struct {
	ManagedServicesList200ResponseInnerStatusAnyOf  *ManagedServicesList200ResponseInnerStatusAnyOf
	ManagedServicesList200ResponseInnerStatusAnyOf1 *ManagedServicesList200ResponseInnerStatusAnyOf1
	ManagedServicesList200ResponseInnerStatusAnyOf2 *ManagedServicesList200ResponseInnerStatusAnyOf2
	ManagedServicesList200ResponseInnerStatusAnyOf3 *ManagedServicesList200ResponseInnerStatusAnyOf3
	ManagedServicesList200ResponseInnerStatusAnyOf4 *ManagedServicesList200ResponseInnerStatusAnyOf4
	ManagedServicesList200ResponseInnerStatusAnyOf5 *ManagedServicesList200ResponseInnerStatusAnyOf5
	ManagedServicesList200ResponseInnerStatusAnyOf6 *ManagedServicesList200ResponseInnerStatusAnyOf6
	ManagedServicesList200ResponseInnerStatusAnyOf7 *ManagedServicesList200ResponseInnerStatusAnyOf7
	ManagedServicesList200ResponseInnerStatusAnyOf8 *ManagedServicesList200ResponseInnerStatusAnyOf8
	ManagedServicesList200ResponseInnerStatusAnyOf9 *ManagedServicesList200ResponseInnerStatusAnyOf9
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ManagedServicesList200ResponseInnerStatus) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ManagedServicesList200ResponseInnerStatusAnyOf
	err = json.Unmarshal(data, &dst.ManagedServicesList200ResponseInnerStatusAnyOf)
	if err == nil {
		jsonManagedServicesList200ResponseInnerStatusAnyOf, _ := json.Marshal(dst.ManagedServicesList200ResponseInnerStatusAnyOf)
		if string(jsonManagedServicesList200ResponseInnerStatusAnyOf) == "{}" { // empty struct
			dst.ManagedServicesList200ResponseInnerStatusAnyOf = nil
		} else {
			return nil // data stored in dst.ManagedServicesList200ResponseInnerStatusAnyOf, return on the first match
		}
	} else {
		dst.ManagedServicesList200ResponseInnerStatusAnyOf = nil
	}

	// try to unmarshal JSON data into ManagedServicesList200ResponseInnerStatusAnyOf1
	err = json.Unmarshal(data, &dst.ManagedServicesList200ResponseInnerStatusAnyOf1)
	if err == nil {
		jsonManagedServicesList200ResponseInnerStatusAnyOf1, _ := json.Marshal(dst.ManagedServicesList200ResponseInnerStatusAnyOf1)
		if string(jsonManagedServicesList200ResponseInnerStatusAnyOf1) == "{}" { // empty struct
			dst.ManagedServicesList200ResponseInnerStatusAnyOf1 = nil
		} else {
			return nil // data stored in dst.ManagedServicesList200ResponseInnerStatusAnyOf1, return on the first match
		}
	} else {
		dst.ManagedServicesList200ResponseInnerStatusAnyOf1 = nil
	}

	// try to unmarshal JSON data into ManagedServicesList200ResponseInnerStatusAnyOf2
	err = json.Unmarshal(data, &dst.ManagedServicesList200ResponseInnerStatusAnyOf2)
	if err == nil {
		jsonManagedServicesList200ResponseInnerStatusAnyOf2, _ := json.Marshal(dst.ManagedServicesList200ResponseInnerStatusAnyOf2)
		if string(jsonManagedServicesList200ResponseInnerStatusAnyOf2) == "{}" { // empty struct
			dst.ManagedServicesList200ResponseInnerStatusAnyOf2 = nil
		} else {
			return nil // data stored in dst.ManagedServicesList200ResponseInnerStatusAnyOf2, return on the first match
		}
	} else {
		dst.ManagedServicesList200ResponseInnerStatusAnyOf2 = nil
	}

	// try to unmarshal JSON data into ManagedServicesList200ResponseInnerStatusAnyOf3
	err = json.Unmarshal(data, &dst.ManagedServicesList200ResponseInnerStatusAnyOf3)
	if err == nil {
		jsonManagedServicesList200ResponseInnerStatusAnyOf3, _ := json.Marshal(dst.ManagedServicesList200ResponseInnerStatusAnyOf3)
		if string(jsonManagedServicesList200ResponseInnerStatusAnyOf3) == "{}" { // empty struct
			dst.ManagedServicesList200ResponseInnerStatusAnyOf3 = nil
		} else {
			return nil // data stored in dst.ManagedServicesList200ResponseInnerStatusAnyOf3, return on the first match
		}
	} else {
		dst.ManagedServicesList200ResponseInnerStatusAnyOf3 = nil
	}

	// try to unmarshal JSON data into ManagedServicesList200ResponseInnerStatusAnyOf4
	err = json.Unmarshal(data, &dst.ManagedServicesList200ResponseInnerStatusAnyOf4)
	if err == nil {
		jsonManagedServicesList200ResponseInnerStatusAnyOf4, _ := json.Marshal(dst.ManagedServicesList200ResponseInnerStatusAnyOf4)
		if string(jsonManagedServicesList200ResponseInnerStatusAnyOf4) == "{}" { // empty struct
			dst.ManagedServicesList200ResponseInnerStatusAnyOf4 = nil
		} else {
			return nil // data stored in dst.ManagedServicesList200ResponseInnerStatusAnyOf4, return on the first match
		}
	} else {
		dst.ManagedServicesList200ResponseInnerStatusAnyOf4 = nil
	}

	// try to unmarshal JSON data into ManagedServicesList200ResponseInnerStatusAnyOf5
	err = json.Unmarshal(data, &dst.ManagedServicesList200ResponseInnerStatusAnyOf5)
	if err == nil {
		jsonManagedServicesList200ResponseInnerStatusAnyOf5, _ := json.Marshal(dst.ManagedServicesList200ResponseInnerStatusAnyOf5)
		if string(jsonManagedServicesList200ResponseInnerStatusAnyOf5) == "{}" { // empty struct
			dst.ManagedServicesList200ResponseInnerStatusAnyOf5 = nil
		} else {
			return nil // data stored in dst.ManagedServicesList200ResponseInnerStatusAnyOf5, return on the first match
		}
	} else {
		dst.ManagedServicesList200ResponseInnerStatusAnyOf5 = nil
	}

	// try to unmarshal JSON data into ManagedServicesList200ResponseInnerStatusAnyOf6
	err = json.Unmarshal(data, &dst.ManagedServicesList200ResponseInnerStatusAnyOf6)
	if err == nil {
		jsonManagedServicesList200ResponseInnerStatusAnyOf6, _ := json.Marshal(dst.ManagedServicesList200ResponseInnerStatusAnyOf6)
		if string(jsonManagedServicesList200ResponseInnerStatusAnyOf6) == "{}" { // empty struct
			dst.ManagedServicesList200ResponseInnerStatusAnyOf6 = nil
		} else {
			return nil // data stored in dst.ManagedServicesList200ResponseInnerStatusAnyOf6, return on the first match
		}
	} else {
		dst.ManagedServicesList200ResponseInnerStatusAnyOf6 = nil
	}

	// try to unmarshal JSON data into ManagedServicesList200ResponseInnerStatusAnyOf7
	err = json.Unmarshal(data, &dst.ManagedServicesList200ResponseInnerStatusAnyOf7)
	if err == nil {
		jsonManagedServicesList200ResponseInnerStatusAnyOf7, _ := json.Marshal(dst.ManagedServicesList200ResponseInnerStatusAnyOf7)
		if string(jsonManagedServicesList200ResponseInnerStatusAnyOf7) == "{}" { // empty struct
			dst.ManagedServicesList200ResponseInnerStatusAnyOf7 = nil
		} else {
			return nil // data stored in dst.ManagedServicesList200ResponseInnerStatusAnyOf7, return on the first match
		}
	} else {
		dst.ManagedServicesList200ResponseInnerStatusAnyOf7 = nil
	}

	// try to unmarshal JSON data into ManagedServicesList200ResponseInnerStatusAnyOf8
	err = json.Unmarshal(data, &dst.ManagedServicesList200ResponseInnerStatusAnyOf8)
	if err == nil {
		jsonManagedServicesList200ResponseInnerStatusAnyOf8, _ := json.Marshal(dst.ManagedServicesList200ResponseInnerStatusAnyOf8)
		if string(jsonManagedServicesList200ResponseInnerStatusAnyOf8) == "{}" { // empty struct
			dst.ManagedServicesList200ResponseInnerStatusAnyOf8 = nil
		} else {
			return nil // data stored in dst.ManagedServicesList200ResponseInnerStatusAnyOf8, return on the first match
		}
	} else {
		dst.ManagedServicesList200ResponseInnerStatusAnyOf8 = nil
	}

	// try to unmarshal JSON data into ManagedServicesList200ResponseInnerStatusAnyOf9
	err = json.Unmarshal(data, &dst.ManagedServicesList200ResponseInnerStatusAnyOf9)
	if err == nil {
		jsonManagedServicesList200ResponseInnerStatusAnyOf9, _ := json.Marshal(dst.ManagedServicesList200ResponseInnerStatusAnyOf9)
		if string(jsonManagedServicesList200ResponseInnerStatusAnyOf9) == "{}" { // empty struct
			dst.ManagedServicesList200ResponseInnerStatusAnyOf9 = nil
		} else {
			return nil // data stored in dst.ManagedServicesList200ResponseInnerStatusAnyOf9, return on the first match
		}
	} else {
		dst.ManagedServicesList200ResponseInnerStatusAnyOf9 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ManagedServicesList200ResponseInnerStatus)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ManagedServicesList200ResponseInnerStatus) MarshalJSON() ([]byte, error) {
	if src.ManagedServicesList200ResponseInnerStatusAnyOf != nil {
		return json.Marshal(&src.ManagedServicesList200ResponseInnerStatusAnyOf)
	}

	if src.ManagedServicesList200ResponseInnerStatusAnyOf1 != nil {
		return json.Marshal(&src.ManagedServicesList200ResponseInnerStatusAnyOf1)
	}

	if src.ManagedServicesList200ResponseInnerStatusAnyOf2 != nil {
		return json.Marshal(&src.ManagedServicesList200ResponseInnerStatusAnyOf2)
	}

	if src.ManagedServicesList200ResponseInnerStatusAnyOf3 != nil {
		return json.Marshal(&src.ManagedServicesList200ResponseInnerStatusAnyOf3)
	}

	if src.ManagedServicesList200ResponseInnerStatusAnyOf4 != nil {
		return json.Marshal(&src.ManagedServicesList200ResponseInnerStatusAnyOf4)
	}

	if src.ManagedServicesList200ResponseInnerStatusAnyOf5 != nil {
		return json.Marshal(&src.ManagedServicesList200ResponseInnerStatusAnyOf5)
	}

	if src.ManagedServicesList200ResponseInnerStatusAnyOf6 != nil {
		return json.Marshal(&src.ManagedServicesList200ResponseInnerStatusAnyOf6)
	}

	if src.ManagedServicesList200ResponseInnerStatusAnyOf7 != nil {
		return json.Marshal(&src.ManagedServicesList200ResponseInnerStatusAnyOf7)
	}

	if src.ManagedServicesList200ResponseInnerStatusAnyOf8 != nil {
		return json.Marshal(&src.ManagedServicesList200ResponseInnerStatusAnyOf8)
	}

	if src.ManagedServicesList200ResponseInnerStatusAnyOf9 != nil {
		return json.Marshal(&src.ManagedServicesList200ResponseInnerStatusAnyOf9)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableManagedServicesList200ResponseInnerStatus struct {
	value *ManagedServicesList200ResponseInnerStatus
	isSet bool
}

func (v NullableManagedServicesList200ResponseInnerStatus) Get() *ManagedServicesList200ResponseInnerStatus {
	return v.value
}

func (v *NullableManagedServicesList200ResponseInnerStatus) Set(val *ManagedServicesList200ResponseInnerStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesList200ResponseInnerStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesList200ResponseInnerStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesList200ResponseInnerStatus(val *ManagedServicesList200ResponseInnerStatus) *NullableManagedServicesList200ResponseInnerStatus {
	return &NullableManagedServicesList200ResponseInnerStatus{value: val, isSet: true}
}

func (v NullableManagedServicesList200ResponseInnerStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesList200ResponseInnerStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
