// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue{}

// ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue struct for ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue
type ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue struct {
	GitRef      string  `json:"gitRef"`
	CiProfile   string  `json:"ciProfile"`
	AppVersion  *string `json:"appVersion,omitempty"`
	Description *string `json:"description,omitempty"`
}

type _ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue

// NewManagedServicesListProviders200ResponseInnerAnyOfVersionsValue instantiates a new ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedServicesListProviders200ResponseInnerAnyOfVersionsValue(gitRef string, ciProfile string) *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue {
	this := ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue{}
	this.GitRef = gitRef
	this.CiProfile = ciProfile
	return &this
}

// NewManagedServicesListProviders200ResponseInnerAnyOfVersionsValueWithDefaults instantiates a new ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedServicesListProviders200ResponseInnerAnyOfVersionsValueWithDefaults() *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue {
	this := ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue{}
	return &this
}

// GetGitRef returns the GitRef field value
func (o *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) GetGitRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GitRef
}

// GetGitRefOk returns a tuple with the GitRef field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) GetGitRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GitRef, true
}

// SetGitRef sets field value
func (o *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) SetGitRef(v string) {
	o.GitRef = v
}

// GetCiProfile returns the CiProfile field value
func (o *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) GetCiProfile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CiProfile
}

// GetCiProfileOk returns a tuple with the CiProfile field value
// and a boolean to check if the value has been set.
func (o *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) GetCiProfileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CiProfile, true
}

// SetCiProfile sets field value
func (o *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) SetCiProfile(v string) {
	o.CiProfile = v
}

// GetAppVersion returns the AppVersion field value if set, zero value otherwise.
func (o *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) GetAppVersion() string {
	if o == nil || IsNil(o.AppVersion) {
		var ret string
		return ret
	}
	return *o.AppVersion
}

// GetAppVersionOk returns a tuple with the AppVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) GetAppVersionOk() (*string, bool) {
	if o == nil || IsNil(o.AppVersion) {
		return nil, false
	}
	return o.AppVersion, true
}

// HasAppVersion returns a boolean if a field has been set.
func (o *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) HasAppVersion() bool {
	if o != nil && !IsNil(o.AppVersion) {
		return true
	}

	return false
}

// SetAppVersion gets a reference to the given string and assigns it to the AppVersion field.
func (o *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) SetAppVersion(v string) {
	o.AppVersion = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) SetDescription(v string) {
	o.Description = &v
}

func (o ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["gitRef"] = o.GitRef
	toSerialize["ciProfile"] = o.CiProfile
	if !IsNil(o.AppVersion) {
		toSerialize["appVersion"] = o.AppVersion
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"gitRef",
		"ciProfile",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedServicesListProviders200ResponseInnerAnyOfVersionsValue := _ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedServicesListProviders200ResponseInnerAnyOfVersionsValue)

	if err != nil {
		return err
	}

	*o = ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue(varManagedServicesListProviders200ResponseInnerAnyOfVersionsValue)

	return err
}

type NullableManagedServicesListProviders200ResponseInnerAnyOfVersionsValue struct {
	value *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue
	isSet bool
}

func (v NullableManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) Get() *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue {
	return v.value
}

func (v *NullableManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) Set(val *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesListProviders200ResponseInnerAnyOfVersionsValue(val *ManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) *NullableManagedServicesListProviders200ResponseInnerAnyOfVersionsValue {
	return &NullableManagedServicesListProviders200ResponseInnerAnyOfVersionsValue{value: val, isSet: true}
}

func (v NullableManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesListProviders200ResponseInnerAnyOfVersionsValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
