// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


package openapi_client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the UsageGetLandscapeServiceEvents200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageGetLandscapeServiceEvents200Response{}

// UsageGetLandscapeServiceEvents200Response struct for UsageGetLandscapeServiceEvents200Response
type UsageGetLandscapeServiceEvents200Response struct {
	TotalItems int `json:"totalItems"`
	// Limits the number of items in the response.
	Limit *int `json:"limit,omitempty"`
	// Starting index within the collection of items.
	Offset *int `json:"offset,omitempty"`
	BeginDate time.Time `json:"beginDate"`
	EndDate time.Time `json:"endDate"`
	Events []UsageGetLandscapeServiceEvents200ResponseEventsInner `json:"events"`
}

type _UsageGetLandscapeServiceEvents200Response UsageGetLandscapeServiceEvents200Response

// NewUsageGetLandscapeServiceEvents200Response instantiates a new UsageGetLandscapeServiceEvents200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageGetLandscapeServiceEvents200Response(totalItems int, beginDate time.Time, endDate time.Time, events []UsageGetLandscapeServiceEvents200ResponseEventsInner) *UsageGetLandscapeServiceEvents200Response {
	this := UsageGetLandscapeServiceEvents200Response{}
	this.TotalItems = totalItems
	var limit int = 25
	this.Limit = &limit
	var offset int = 0
	this.Offset = &offset
	this.BeginDate = beginDate
	this.EndDate = endDate
	this.Events = events
	return &this
}

// NewUsageGetLandscapeServiceEvents200ResponseWithDefaults instantiates a new UsageGetLandscapeServiceEvents200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageGetLandscapeServiceEvents200ResponseWithDefaults() *UsageGetLandscapeServiceEvents200Response {
	this := UsageGetLandscapeServiceEvents200Response{}
	var limit int = 25
	this.Limit = &limit
	var offset int = 0
	this.Offset = &offset
	return &this
}

// GetTotalItems returns the TotalItems field value
func (o *UsageGetLandscapeServiceEvents200Response) GetTotalItems() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.TotalItems
}

// GetTotalItemsOk returns a tuple with the TotalItems field value
// and a boolean to check if the value has been set.
func (o *UsageGetLandscapeServiceEvents200Response) GetTotalItemsOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalItems, true
}

// SetTotalItems sets field value
func (o *UsageGetLandscapeServiceEvents200Response) SetTotalItems(v int) {
	o.TotalItems = v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *UsageGetLandscapeServiceEvents200Response) GetLimit() int {
	if o == nil || IsNil(o.Limit) {
		var ret int
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageGetLandscapeServiceEvents200Response) GetLimitOk() (*int, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *UsageGetLandscapeServiceEvents200Response) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int and assigns it to the Limit field.
func (o *UsageGetLandscapeServiceEvents200Response) SetLimit(v int) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *UsageGetLandscapeServiceEvents200Response) GetOffset() int {
	if o == nil || IsNil(o.Offset) {
		var ret int
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageGetLandscapeServiceEvents200Response) GetOffsetOk() (*int, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *UsageGetLandscapeServiceEvents200Response) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int and assigns it to the Offset field.
func (o *UsageGetLandscapeServiceEvents200Response) SetOffset(v int) {
	o.Offset = &v
}

// GetBeginDate returns the BeginDate field value
func (o *UsageGetLandscapeServiceEvents200Response) GetBeginDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.BeginDate
}

// GetBeginDateOk returns a tuple with the BeginDate field value
// and a boolean to check if the value has been set.
func (o *UsageGetLandscapeServiceEvents200Response) GetBeginDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BeginDate, true
}

// SetBeginDate sets field value
func (o *UsageGetLandscapeServiceEvents200Response) SetBeginDate(v time.Time) {
	o.BeginDate = v
}

// GetEndDate returns the EndDate field value
func (o *UsageGetLandscapeServiceEvents200Response) GetEndDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value
// and a boolean to check if the value has been set.
func (o *UsageGetLandscapeServiceEvents200Response) GetEndDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndDate, true
}

// SetEndDate sets field value
func (o *UsageGetLandscapeServiceEvents200Response) SetEndDate(v time.Time) {
	o.EndDate = v
}

// GetEvents returns the Events field value
func (o *UsageGetLandscapeServiceEvents200Response) GetEvents() []UsageGetLandscapeServiceEvents200ResponseEventsInner {
	if o == nil {
		var ret []UsageGetLandscapeServiceEvents200ResponseEventsInner
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *UsageGetLandscapeServiceEvents200Response) GetEventsOk() ([]UsageGetLandscapeServiceEvents200ResponseEventsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *UsageGetLandscapeServiceEvents200Response) SetEvents(v []UsageGetLandscapeServiceEvents200ResponseEventsInner) {
	o.Events = v
}

func (o UsageGetLandscapeServiceEvents200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageGetLandscapeServiceEvents200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["totalItems"] = o.TotalItems
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	toSerialize["beginDate"] = o.BeginDate
	toSerialize["endDate"] = o.EndDate
	toSerialize["events"] = o.Events
	return toSerialize, nil
}

func (o *UsageGetLandscapeServiceEvents200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"totalItems",
		"beginDate",
		"endDate",
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsageGetLandscapeServiceEvents200Response := _UsageGetLandscapeServiceEvents200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsageGetLandscapeServiceEvents200Response)

	if err != nil {
		return err
	}

	*o = UsageGetLandscapeServiceEvents200Response(varUsageGetLandscapeServiceEvents200Response)

	return err
}

type NullableUsageGetLandscapeServiceEvents200Response struct {
	value *UsageGetLandscapeServiceEvents200Response
	isSet bool
}

func (v NullableUsageGetLandscapeServiceEvents200Response) Get() *UsageGetLandscapeServiceEvents200Response {
	return v.value
}

func (v *NullableUsageGetLandscapeServiceEvents200Response) Set(val *UsageGetLandscapeServiceEvents200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageGetLandscapeServiceEvents200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageGetLandscapeServiceEvents200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageGetLandscapeServiceEvents200Response(val *UsageGetLandscapeServiceEvents200Response) *NullableUsageGetLandscapeServiceEvents200Response {
	return &NullableUsageGetLandscapeServiceEvents200Response{value: val, isSet: true}
}

func (v NullableUsageGetLandscapeServiceEvents200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageGetLandscapeServiceEvents200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

