// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WorkspacesGetWorkspace200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspacesGetWorkspace200Response{}

// WorkspacesGetWorkspace200Response struct for WorkspacesGetWorkspace200Response
type WorkspacesGetWorkspace200Response struct {
	TeamId            int            `json:"teamId"`
	Name              string         `json:"name"`
	PlanId            int            `json:"planId"`
	IsPrivateRepo     bool           `json:"isPrivateRepo"`
	Replicas          int            `json:"replicas"`
	Id                int            `json:"id"`
	BaseImage         *string        `json:"baseImage,omitempty"`
	DataCenterId      int            `json:"dataCenterId"`
	UserId            int            `json:"userId"`
	GitUrl            NullableString `json:"gitUrl"`
	InitialBranch     NullableString `json:"initialBranch"`
	SourceWorkspaceId NullableInt    `json:"sourceWorkspaceId"`
	WelcomeMessage    NullableString `json:"welcomeMessage"`
	VpnConfig         NullableString `json:"vpnConfig"`
	Restricted        bool           `json:"restricted"`
	CollectTraces     bool           `json:"collectTraces"`
	PersistentLogs    bool           `json:"persistentLogs"`
}

type _WorkspacesGetWorkspace200Response WorkspacesGetWorkspace200Response

// NewWorkspacesGetWorkspace200Response instantiates a new WorkspacesGetWorkspace200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspacesGetWorkspace200Response(teamId int, name string, planId int, isPrivateRepo bool, replicas int, id int, dataCenterId int, userId int, gitUrl NullableString, initialBranch NullableString, sourceWorkspaceId NullableInt, welcomeMessage NullableString, vpnConfig NullableString, restricted bool, collectTraces bool, persistentLogs bool) *WorkspacesGetWorkspace200Response {
	this := WorkspacesGetWorkspace200Response{}
	this.TeamId = teamId
	this.Name = name
	this.PlanId = planId
	this.IsPrivateRepo = isPrivateRepo
	this.Replicas = replicas
	this.Id = id
	this.DataCenterId = dataCenterId
	this.UserId = userId
	this.GitUrl = gitUrl
	this.InitialBranch = initialBranch
	this.SourceWorkspaceId = sourceWorkspaceId
	this.WelcomeMessage = welcomeMessage
	this.VpnConfig = vpnConfig
	this.Restricted = restricted
	this.CollectTraces = collectTraces
	this.PersistentLogs = persistentLogs
	return &this
}

// NewWorkspacesGetWorkspace200ResponseWithDefaults instantiates a new WorkspacesGetWorkspace200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspacesGetWorkspace200ResponseWithDefaults() *WorkspacesGetWorkspace200Response {
	this := WorkspacesGetWorkspace200Response{}
	return &this
}

// GetTeamId returns the TeamId field value
func (o *WorkspacesGetWorkspace200Response) GetTeamId() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value
// and a boolean to check if the value has been set.
func (o *WorkspacesGetWorkspace200Response) GetTeamIdOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TeamId, true
}

// SetTeamId sets field value
func (o *WorkspacesGetWorkspace200Response) SetTeamId(v int) {
	o.TeamId = v
}

// GetName returns the Name field value
func (o *WorkspacesGetWorkspace200Response) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WorkspacesGetWorkspace200Response) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WorkspacesGetWorkspace200Response) SetName(v string) {
	o.Name = v
}

// GetPlanId returns the PlanId field value
func (o *WorkspacesGetWorkspace200Response) GetPlanId() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value
// and a boolean to check if the value has been set.
func (o *WorkspacesGetWorkspace200Response) GetPlanIdOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanId, true
}

// SetPlanId sets field value
func (o *WorkspacesGetWorkspace200Response) SetPlanId(v int) {
	o.PlanId = v
}

// GetIsPrivateRepo returns the IsPrivateRepo field value
func (o *WorkspacesGetWorkspace200Response) GetIsPrivateRepo() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPrivateRepo
}

// GetIsPrivateRepoOk returns a tuple with the IsPrivateRepo field value
// and a boolean to check if the value has been set.
func (o *WorkspacesGetWorkspace200Response) GetIsPrivateRepoOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPrivateRepo, true
}

// SetIsPrivateRepo sets field value
func (o *WorkspacesGetWorkspace200Response) SetIsPrivateRepo(v bool) {
	o.IsPrivateRepo = v
}

// GetReplicas returns the Replicas field value
func (o *WorkspacesGetWorkspace200Response) GetReplicas() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.Replicas
}

// GetReplicasOk returns a tuple with the Replicas field value
// and a boolean to check if the value has been set.
func (o *WorkspacesGetWorkspace200Response) GetReplicasOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Replicas, true
}

// SetReplicas sets field value
func (o *WorkspacesGetWorkspace200Response) SetReplicas(v int) {
	o.Replicas = v
}

// GetId returns the Id field value
func (o *WorkspacesGetWorkspace200Response) GetId() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WorkspacesGetWorkspace200Response) GetIdOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WorkspacesGetWorkspace200Response) SetId(v int) {
	o.Id = v
}

// GetBaseImage returns the BaseImage field value if set, zero value otherwise.
func (o *WorkspacesGetWorkspace200Response) GetBaseImage() string {
	if o == nil || IsNil(o.BaseImage) {
		var ret string
		return ret
	}
	return *o.BaseImage
}

// GetBaseImageOk returns a tuple with the BaseImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspacesGetWorkspace200Response) GetBaseImageOk() (*string, bool) {
	if o == nil || IsNil(o.BaseImage) {
		return nil, false
	}
	return o.BaseImage, true
}

// HasBaseImage returns a boolean if a field has been set.
func (o *WorkspacesGetWorkspace200Response) HasBaseImage() bool {
	if o != nil && !IsNil(o.BaseImage) {
		return true
	}

	return false
}

// SetBaseImage gets a reference to the given string and assigns it to the BaseImage field.
func (o *WorkspacesGetWorkspace200Response) SetBaseImage(v string) {
	o.BaseImage = &v
}

// GetDataCenterId returns the DataCenterId field value
func (o *WorkspacesGetWorkspace200Response) GetDataCenterId() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.DataCenterId
}

// GetDataCenterIdOk returns a tuple with the DataCenterId field value
// and a boolean to check if the value has been set.
func (o *WorkspacesGetWorkspace200Response) GetDataCenterIdOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataCenterId, true
}

// SetDataCenterId sets field value
func (o *WorkspacesGetWorkspace200Response) SetDataCenterId(v int) {
	o.DataCenterId = v
}

// GetUserId returns the UserId field value
func (o *WorkspacesGetWorkspace200Response) GetUserId() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *WorkspacesGetWorkspace200Response) GetUserIdOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *WorkspacesGetWorkspace200Response) SetUserId(v int) {
	o.UserId = v
}

// GetGitUrl returns the GitUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WorkspacesGetWorkspace200Response) GetGitUrl() string {
	if o == nil || o.GitUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.GitUrl.Get()
}

// GetGitUrlOk returns a tuple with the GitUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkspacesGetWorkspace200Response) GetGitUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GitUrl.Get(), o.GitUrl.IsSet()
}

// SetGitUrl sets field value
func (o *WorkspacesGetWorkspace200Response) SetGitUrl(v string) {
	o.GitUrl.Set(&v)
}

// GetInitialBranch returns the InitialBranch field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WorkspacesGetWorkspace200Response) GetInitialBranch() string {
	if o == nil || o.InitialBranch.Get() == nil {
		var ret string
		return ret
	}

	return *o.InitialBranch.Get()
}

// GetInitialBranchOk returns a tuple with the InitialBranch field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkspacesGetWorkspace200Response) GetInitialBranchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InitialBranch.Get(), o.InitialBranch.IsSet()
}

// SetInitialBranch sets field value
func (o *WorkspacesGetWorkspace200Response) SetInitialBranch(v string) {
	o.InitialBranch.Set(&v)
}

// GetSourceWorkspaceId returns the SourceWorkspaceId field value
// If the value is explicit nil, the zero value for int will be returned
func (o *WorkspacesGetWorkspace200Response) GetSourceWorkspaceId() int {
	if o == nil || o.SourceWorkspaceId.Get() == nil {
		var ret int
		return ret
	}

	return *o.SourceWorkspaceId.Get()
}

// GetSourceWorkspaceIdOk returns a tuple with the SourceWorkspaceId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkspacesGetWorkspace200Response) GetSourceWorkspaceIdOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceWorkspaceId.Get(), o.SourceWorkspaceId.IsSet()
}

// SetSourceWorkspaceId sets field value
func (o *WorkspacesGetWorkspace200Response) SetSourceWorkspaceId(v int) {
	o.SourceWorkspaceId.Set(&v)
}

// GetWelcomeMessage returns the WelcomeMessage field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WorkspacesGetWorkspace200Response) GetWelcomeMessage() string {
	if o == nil || o.WelcomeMessage.Get() == nil {
		var ret string
		return ret
	}

	return *o.WelcomeMessage.Get()
}

// GetWelcomeMessageOk returns a tuple with the WelcomeMessage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkspacesGetWorkspace200Response) GetWelcomeMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WelcomeMessage.Get(), o.WelcomeMessage.IsSet()
}

// SetWelcomeMessage sets field value
func (o *WorkspacesGetWorkspace200Response) SetWelcomeMessage(v string) {
	o.WelcomeMessage.Set(&v)
}

// GetVpnConfig returns the VpnConfig field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WorkspacesGetWorkspace200Response) GetVpnConfig() string {
	if o == nil || o.VpnConfig.Get() == nil {
		var ret string
		return ret
	}

	return *o.VpnConfig.Get()
}

// GetVpnConfigOk returns a tuple with the VpnConfig field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkspacesGetWorkspace200Response) GetVpnConfigOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VpnConfig.Get(), o.VpnConfig.IsSet()
}

// SetVpnConfig sets field value
func (o *WorkspacesGetWorkspace200Response) SetVpnConfig(v string) {
	o.VpnConfig.Set(&v)
}

// GetRestricted returns the Restricted field value
func (o *WorkspacesGetWorkspace200Response) GetRestricted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Restricted
}

// GetRestrictedOk returns a tuple with the Restricted field value
// and a boolean to check if the value has been set.
func (o *WorkspacesGetWorkspace200Response) GetRestrictedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Restricted, true
}

// SetRestricted sets field value
func (o *WorkspacesGetWorkspace200Response) SetRestricted(v bool) {
	o.Restricted = v
}

// GetCollectTraces returns the CollectTraces field value
func (o *WorkspacesGetWorkspace200Response) GetCollectTraces() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CollectTraces
}

// GetCollectTracesOk returns a tuple with the CollectTraces field value
// and a boolean to check if the value has been set.
func (o *WorkspacesGetWorkspace200Response) GetCollectTracesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CollectTraces, true
}

// SetCollectTraces sets field value
func (o *WorkspacesGetWorkspace200Response) SetCollectTraces(v bool) {
	o.CollectTraces = v
}

// GetPersistentLogs returns the PersistentLogs field value
func (o *WorkspacesGetWorkspace200Response) GetPersistentLogs() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PersistentLogs
}

// GetPersistentLogsOk returns a tuple with the PersistentLogs field value
// and a boolean to check if the value has been set.
func (o *WorkspacesGetWorkspace200Response) GetPersistentLogsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PersistentLogs, true
}

// SetPersistentLogs sets field value
func (o *WorkspacesGetWorkspace200Response) SetPersistentLogs(v bool) {
	o.PersistentLogs = v
}

func (o WorkspacesGetWorkspace200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspacesGetWorkspace200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["teamId"] = o.TeamId
	toSerialize["name"] = o.Name
	toSerialize["planId"] = o.PlanId
	toSerialize["isPrivateRepo"] = o.IsPrivateRepo
	toSerialize["replicas"] = o.Replicas
	toSerialize["id"] = o.Id
	if !IsNil(o.BaseImage) {
		toSerialize["baseImage"] = o.BaseImage
	}
	toSerialize["dataCenterId"] = o.DataCenterId
	toSerialize["userId"] = o.UserId
	toSerialize["gitUrl"] = o.GitUrl.Get()
	toSerialize["initialBranch"] = o.InitialBranch.Get()
	toSerialize["sourceWorkspaceId"] = o.SourceWorkspaceId.Get()
	toSerialize["welcomeMessage"] = o.WelcomeMessage.Get()
	toSerialize["vpnConfig"] = o.VpnConfig.Get()
	toSerialize["restricted"] = o.Restricted
	toSerialize["collectTraces"] = o.CollectTraces
	toSerialize["persistentLogs"] = o.PersistentLogs
	return toSerialize, nil
}

func (o *WorkspacesGetWorkspace200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"teamId",
		"name",
		"planId",
		"isPrivateRepo",
		"replicas",
		"id",
		"dataCenterId",
		"userId",
		"gitUrl",
		"initialBranch",
		"sourceWorkspaceId",
		"welcomeMessage",
		"vpnConfig",
		"restricted",
		"collectTraces",
		"persistentLogs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkspacesGetWorkspace200Response := _WorkspacesGetWorkspace200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkspacesGetWorkspace200Response)

	if err != nil {
		return err
	}

	*o = WorkspacesGetWorkspace200Response(varWorkspacesGetWorkspace200Response)

	return err
}

type NullableWorkspacesGetWorkspace200Response struct {
	value *WorkspacesGetWorkspace200Response
	isSet bool
}

func (v NullableWorkspacesGetWorkspace200Response) Get() *WorkspacesGetWorkspace200Response {
	return v.value
}

func (v *NullableWorkspacesGetWorkspace200Response) Set(val *WorkspacesGetWorkspace200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspacesGetWorkspace200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspacesGetWorkspace200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspacesGetWorkspace200Response(val *WorkspacesGetWorkspace200Response) *NullableWorkspacesGetWorkspace200Response {
	return &NullableWorkspacesGetWorkspace200Response{value: val, isSet: true}
}

func (v NullableWorkspacesGetWorkspace200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspacesGetWorkspace200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
