// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
	"fmt"
)

// ManagedServicesListProviders200ResponseInner struct for ManagedServicesListProviders200ResponseInner
type ManagedServicesListProviders200ResponseInner struct {
	ManagedServicesListProviders200ResponseInnerAnyOf  *ManagedServicesListProviders200ResponseInnerAnyOf
	ManagedServicesListProviders200ResponseInnerAnyOf1 *ManagedServicesListProviders200ResponseInnerAnyOf1
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ManagedServicesListProviders200ResponseInner) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ManagedServicesListProviders200ResponseInnerAnyOf
	err = json.Unmarshal(data, &dst.ManagedServicesListProviders200ResponseInnerAnyOf)
	if err == nil {
		jsonManagedServicesListProviders200ResponseInnerAnyOf, _ := json.Marshal(dst.ManagedServicesListProviders200ResponseInnerAnyOf)
		if string(jsonManagedServicesListProviders200ResponseInnerAnyOf) == "{}" { // empty struct
			dst.ManagedServicesListProviders200ResponseInnerAnyOf = nil
		} else {
			return nil // data stored in dst.ManagedServicesListProviders200ResponseInnerAnyOf, return on the first match
		}
	} else {
		dst.ManagedServicesListProviders200ResponseInnerAnyOf = nil
	}

	// try to unmarshal JSON data into ManagedServicesListProviders200ResponseInnerAnyOf1
	err = json.Unmarshal(data, &dst.ManagedServicesListProviders200ResponseInnerAnyOf1)
	if err == nil {
		jsonManagedServicesListProviders200ResponseInnerAnyOf1, _ := json.Marshal(dst.ManagedServicesListProviders200ResponseInnerAnyOf1)
		if string(jsonManagedServicesListProviders200ResponseInnerAnyOf1) == "{}" { // empty struct
			dst.ManagedServicesListProviders200ResponseInnerAnyOf1 = nil
		} else {
			return nil // data stored in dst.ManagedServicesListProviders200ResponseInnerAnyOf1, return on the first match
		}
	} else {
		dst.ManagedServicesListProviders200ResponseInnerAnyOf1 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ManagedServicesListProviders200ResponseInner)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ManagedServicesListProviders200ResponseInner) MarshalJSON() ([]byte, error) {
	if src.ManagedServicesListProviders200ResponseInnerAnyOf != nil {
		return json.Marshal(&src.ManagedServicesListProviders200ResponseInnerAnyOf)
	}

	if src.ManagedServicesListProviders200ResponseInnerAnyOf1 != nil {
		return json.Marshal(&src.ManagedServicesListProviders200ResponseInnerAnyOf1)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableManagedServicesListProviders200ResponseInner struct {
	value *ManagedServicesListProviders200ResponseInner
	isSet bool
}

func (v NullableManagedServicesListProviders200ResponseInner) Get() *ManagedServicesListProviders200ResponseInner {
	return v.value
}

func (v *NullableManagedServicesListProviders200ResponseInner) Set(val *ManagedServicesListProviders200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServicesListProviders200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServicesListProviders200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServicesListProviders200ResponseInner(val *ManagedServicesListProviders200ResponseInner) *NullableManagedServicesListProviders200ResponseInner {
	return &NullableManagedServicesListProviders200ResponseInner{value: val, isSet: true}
}

func (v NullableManagedServicesListProviders200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServicesListProviders200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
