// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

/*
Codesphere Public API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the OrganizationsListOrgTeams200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationsListOrgTeams200ResponseInner{}

// OrganizationsListOrgTeams200ResponseInner struct for OrganizationsListOrgTeams200ResponseInner
type OrganizationsListOrgTeams200ResponseInner struct {
	Id                  int        `json:"id"`
	DefaultDataCenterId int        `json:"defaultDataCenterId"`
	Name                string     `json:"name"`
	Description         *string    `json:"description,omitempty"`
	AvatarId            *string    `json:"avatarId,omitempty"`
	AvatarUrl           *string    `json:"avatarUrl,omitempty"`
	IsFirst             *bool      `json:"isFirst,omitempty"`
	CreatedAt           *time.Time `json:"createdAt,omitempty"`
}

type _OrganizationsListOrgTeams200ResponseInner OrganizationsListOrgTeams200ResponseInner

// NewOrganizationsListOrgTeams200ResponseInner instantiates a new OrganizationsListOrgTeams200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationsListOrgTeams200ResponseInner(id int, defaultDataCenterId int, name string) *OrganizationsListOrgTeams200ResponseInner {
	this := OrganizationsListOrgTeams200ResponseInner{}
	this.Id = id
	this.DefaultDataCenterId = defaultDataCenterId
	this.Name = name
	return &this
}

// NewOrganizationsListOrgTeams200ResponseInnerWithDefaults instantiates a new OrganizationsListOrgTeams200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationsListOrgTeams200ResponseInnerWithDefaults() *OrganizationsListOrgTeams200ResponseInner {
	this := OrganizationsListOrgTeams200ResponseInner{}
	return &this
}

// GetId returns the Id field value
func (o *OrganizationsListOrgTeams200ResponseInner) GetId() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrganizationsListOrgTeams200ResponseInner) GetIdOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrganizationsListOrgTeams200ResponseInner) SetId(v int) {
	o.Id = v
}

// GetDefaultDataCenterId returns the DefaultDataCenterId field value
func (o *OrganizationsListOrgTeams200ResponseInner) GetDefaultDataCenterId() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.DefaultDataCenterId
}

// GetDefaultDataCenterIdOk returns a tuple with the DefaultDataCenterId field value
// and a boolean to check if the value has been set.
func (o *OrganizationsListOrgTeams200ResponseInner) GetDefaultDataCenterIdOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultDataCenterId, true
}

// SetDefaultDataCenterId sets field value
func (o *OrganizationsListOrgTeams200ResponseInner) SetDefaultDataCenterId(v int) {
	o.DefaultDataCenterId = v
}

// GetName returns the Name field value
func (o *OrganizationsListOrgTeams200ResponseInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OrganizationsListOrgTeams200ResponseInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OrganizationsListOrgTeams200ResponseInner) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *OrganizationsListOrgTeams200ResponseInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsListOrgTeams200ResponseInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *OrganizationsListOrgTeams200ResponseInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *OrganizationsListOrgTeams200ResponseInner) SetDescription(v string) {
	o.Description = &v
}

// GetAvatarId returns the AvatarId field value if set, zero value otherwise.
func (o *OrganizationsListOrgTeams200ResponseInner) GetAvatarId() string {
	if o == nil || IsNil(o.AvatarId) {
		var ret string
		return ret
	}
	return *o.AvatarId
}

// GetAvatarIdOk returns a tuple with the AvatarId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsListOrgTeams200ResponseInner) GetAvatarIdOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarId) {
		return nil, false
	}
	return o.AvatarId, true
}

// HasAvatarId returns a boolean if a field has been set.
func (o *OrganizationsListOrgTeams200ResponseInner) HasAvatarId() bool {
	if o != nil && !IsNil(o.AvatarId) {
		return true
	}

	return false
}

// SetAvatarId gets a reference to the given string and assigns it to the AvatarId field.
func (o *OrganizationsListOrgTeams200ResponseInner) SetAvatarId(v string) {
	o.AvatarId = &v
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise.
func (o *OrganizationsListOrgTeams200ResponseInner) GetAvatarUrl() string {
	if o == nil || IsNil(o.AvatarUrl) {
		var ret string
		return ret
	}
	return *o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsListOrgTeams200ResponseInner) GetAvatarUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarUrl) {
		return nil, false
	}
	return o.AvatarUrl, true
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *OrganizationsListOrgTeams200ResponseInner) HasAvatarUrl() bool {
	if o != nil && !IsNil(o.AvatarUrl) {
		return true
	}

	return false
}

// SetAvatarUrl gets a reference to the given string and assigns it to the AvatarUrl field.
func (o *OrganizationsListOrgTeams200ResponseInner) SetAvatarUrl(v string) {
	o.AvatarUrl = &v
}

// GetIsFirst returns the IsFirst field value if set, zero value otherwise.
func (o *OrganizationsListOrgTeams200ResponseInner) GetIsFirst() bool {
	if o == nil || IsNil(o.IsFirst) {
		var ret bool
		return ret
	}
	return *o.IsFirst
}

// GetIsFirstOk returns a tuple with the IsFirst field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsListOrgTeams200ResponseInner) GetIsFirstOk() (*bool, bool) {
	if o == nil || IsNil(o.IsFirst) {
		return nil, false
	}
	return o.IsFirst, true
}

// HasIsFirst returns a boolean if a field has been set.
func (o *OrganizationsListOrgTeams200ResponseInner) HasIsFirst() bool {
	if o != nil && !IsNil(o.IsFirst) {
		return true
	}

	return false
}

// SetIsFirst gets a reference to the given bool and assigns it to the IsFirst field.
func (o *OrganizationsListOrgTeams200ResponseInner) SetIsFirst(v bool) {
	o.IsFirst = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *OrganizationsListOrgTeams200ResponseInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsListOrgTeams200ResponseInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *OrganizationsListOrgTeams200ResponseInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *OrganizationsListOrgTeams200ResponseInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o OrganizationsListOrgTeams200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationsListOrgTeams200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["defaultDataCenterId"] = o.DefaultDataCenterId
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.AvatarId) {
		toSerialize["avatarId"] = o.AvatarId
	}
	if !IsNil(o.AvatarUrl) {
		toSerialize["avatarUrl"] = o.AvatarUrl
	}
	if !IsNil(o.IsFirst) {
		toSerialize["isFirst"] = o.IsFirst
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	return toSerialize, nil
}

func (o *OrganizationsListOrgTeams200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"defaultDataCenterId",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationsListOrgTeams200ResponseInner := _OrganizationsListOrgTeams200ResponseInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationsListOrgTeams200ResponseInner)

	if err != nil {
		return err
	}

	*o = OrganizationsListOrgTeams200ResponseInner(varOrganizationsListOrgTeams200ResponseInner)

	return err
}

type NullableOrganizationsListOrgTeams200ResponseInner struct {
	value *OrganizationsListOrgTeams200ResponseInner
	isSet bool
}

func (v NullableOrganizationsListOrgTeams200ResponseInner) Get() *OrganizationsListOrgTeams200ResponseInner {
	return v.value
}

func (v *NullableOrganizationsListOrgTeams200ResponseInner) Set(val *OrganizationsListOrgTeams200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationsListOrgTeams200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationsListOrgTeams200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationsListOrgTeams200ResponseInner(val *OrganizationsListOrgTeams200ResponseInner) *NullableOrganizationsListOrgTeams200ResponseInner {
	return &NullableOrganizationsListOrgTeams200ResponseInner{value: val, isSet: true}
}

func (v NullableOrganizationsListOrgTeams200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationsListOrgTeams200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
