// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package delete

import (
	"github.com/codesphere-cloud/cs-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DeleteTeam provides a mock function for the type MockClient
func (_mock *MockClient) DeleteTeam(teamId int) error {
	ret := _mock.Called(teamId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeam")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(teamId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTeam'
type MockClient_DeleteTeam_Call struct {
	*mock.Call
}

// DeleteTeam is a helper method to define mock.On call
//   - teamId int
func (_e *MockClient_Expecter) DeleteTeam(teamId any) *MockClient_DeleteTeam_Call {
	return &MockClient_DeleteTeam_Call{Call: _e.mock.On("DeleteTeam", teamId)}
}

func (_c *MockClient_DeleteTeam_Call) Run(run func(teamId int)) *MockClient_DeleteTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_DeleteTeam_Call) Return(err error) *MockClient_DeleteTeam_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteTeam_Call) RunAndReturn(run func(teamId int) error) *MockClient_DeleteTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWorkspace provides a mock function for the type MockClient
func (_mock *MockClient) DeleteWorkspace(wsId int) error {
	ret := _mock.Called(wsId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkspace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(wsId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkspace'
type MockClient_DeleteWorkspace_Call struct {
	*mock.Call
}

// DeleteWorkspace is a helper method to define mock.On call
//   - wsId int
func (_e *MockClient_Expecter) DeleteWorkspace(wsId any) *MockClient_DeleteWorkspace_Call {
	return &MockClient_DeleteWorkspace_Call{Call: _e.mock.On("DeleteWorkspace", wsId)}
}

func (_c *MockClient_DeleteWorkspace_Call) Run(run func(wsId int)) *MockClient_DeleteWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_DeleteWorkspace_Call) Return(err error) *MockClient_DeleteWorkspace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteWorkspace_Call) RunAndReturn(run func(wsId int) error) *MockClient_DeleteWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkspace provides a mock function for the type MockClient
func (_mock *MockClient) GetWorkspace(workspaceId int) (api.Workspace, error) {
	ret := _mock.Called(workspaceId)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspace")
	}

	var r0 api.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (api.Workspace, error)); ok {
		return returnFunc(workspaceId)
	}
	if returnFunc, ok := ret.Get(0).(func(int) api.Workspace); ok {
		r0 = returnFunc(workspaceId)
	} else {
		r0 = ret.Get(0).(api.Workspace)
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(workspaceId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkspace'
type MockClient_GetWorkspace_Call struct {
	*mock.Call
}

// GetWorkspace is a helper method to define mock.On call
//   - workspaceId int
func (_e *MockClient_Expecter) GetWorkspace(workspaceId any) *MockClient_GetWorkspace_Call {
	return &MockClient_GetWorkspace_Call{Call: _e.mock.On("GetWorkspace", workspaceId)}
}

func (_c *MockClient_GetWorkspace_Call) Run(run func(workspaceId int)) *MockClient_GetWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetWorkspace_Call) Return(v api.Workspace, err error) *MockClient_GetWorkspace_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_GetWorkspace_Call) RunAndReturn(run func(workspaceId int) (api.Workspace, error)) *MockClient_GetWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTeamMember provides a mock function for the type MockClient
func (_mock *MockClient) RemoveTeamMember(teamId int, userId int) error {
	ret := _mock.Called(teamId, userId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTeamMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = returnFunc(teamId, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_RemoveTeamMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTeamMember'
type MockClient_RemoveTeamMember_Call struct {
	*mock.Call
}

// RemoveTeamMember is a helper method to define mock.On call
//   - teamId int
//   - userId int
func (_e *MockClient_Expecter) RemoveTeamMember(teamId any, userId any) *MockClient_RemoveTeamMember_Call {
	return &MockClient_RemoveTeamMember_Call{Call: _e.mock.On("RemoveTeamMember", teamId, userId)}
}

func (_c *MockClient_RemoveTeamMember_Call) Run(run func(teamId int, userId int)) *MockClient_RemoveTeamMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_RemoveTeamMember_Call) Return(err error) *MockClient_RemoveTeamMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_RemoveTeamMember_Call) RunAndReturn(run func(teamId int, userId int) error) *MockClient_RemoveTeamMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrompt creates a new instance of MockPrompt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrompt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrompt {
	mock := &MockPrompt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPrompt is an autogenerated mock type for the Prompt type
type MockPrompt struct {
	mock.Mock
}

type MockPrompt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrompt) EXPECT() *MockPrompt_Expecter {
	return &MockPrompt_Expecter{mock: &_m.Mock}
}

// InputPrompt provides a mock function for the type MockPrompt
func (_mock *MockPrompt) InputPrompt(prompt string) string {
	ret := _mock.Called(prompt)

	if len(ret) == 0 {
		panic("no return value specified for InputPrompt")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(prompt)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPrompt_InputPrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InputPrompt'
type MockPrompt_InputPrompt_Call struct {
	*mock.Call
}

// InputPrompt is a helper method to define mock.On call
//   - prompt string
func (_e *MockPrompt_Expecter) InputPrompt(prompt any) *MockPrompt_InputPrompt_Call {
	return &MockPrompt_InputPrompt_Call{Call: _e.mock.On("InputPrompt", prompt)}
}

func (_c *MockPrompt_InputPrompt_Call) Run(run func(prompt string)) *MockPrompt_InputPrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPrompt_InputPrompt_Call) Return(s string) *MockPrompt_InputPrompt_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPrompt_InputPrompt_Call) RunAndReturn(run func(prompt string) string) *MockPrompt_InputPrompt_Call {
	_c.Call.Return(run)
	return _c
}
