// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pipeline

import (
	"context"
	"github.com/codesphere-cloud/cs-go/api"
	mock "github.com/stretchr/testify/mock"
	"io"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DeployLandscape provides a mock function for the type MockClient
func (_mock *MockClient) DeployLandscape(wsId int, profile string) error {
	ret := _mock.Called(wsId, profile)

	if len(ret) == 0 {
		panic("no return value specified for DeployLandscape")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = returnFunc(wsId, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeployLandscape_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeployLandscape'
type MockClient_DeployLandscape_Call struct {
	*mock.Call
}

// DeployLandscape is a helper method to define mock.On call
//   - wsId int
//   - profile string
func (_e *MockClient_Expecter) DeployLandscape(wsId interface{}, profile interface{}) *MockClient_DeployLandscape_Call {
	return &MockClient_DeployLandscape_Call{Call: _e.mock.On("DeployLandscape", wsId, profile)}
}

func (_c *MockClient_DeployLandscape_Call) Run(run func(wsId int, profile string)) *MockClient_DeployLandscape_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_DeployLandscape_Call) Return(err error) *MockClient_DeployLandscape_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeployLandscape_Call) RunAndReturn(run func(wsId int, profile string) error) *MockClient_DeployLandscape_Call {
	_c.Call.Return(run)
	return _c
}

// GetPipelineState provides a mock function for the type MockClient
func (_mock *MockClient) GetPipelineState(wsId int, stage string) ([]api.PipelineStatus, error) {
	ret := _mock.Called(wsId, stage)

	if len(ret) == 0 {
		panic("no return value specified for GetPipelineState")
	}

	var r0 []api.PipelineStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, string) ([]api.PipelineStatus, error)); ok {
		return returnFunc(wsId, stage)
	}
	if returnFunc, ok := ret.Get(0).(func(int, string) []api.PipelineStatus); ok {
		r0 = returnFunc(wsId, stage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.PipelineStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = returnFunc(wsId, stage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetPipelineState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPipelineState'
type MockClient_GetPipelineState_Call struct {
	*mock.Call
}

// GetPipelineState is a helper method to define mock.On call
//   - wsId int
//   - stage string
func (_e *MockClient_Expecter) GetPipelineState(wsId interface{}, stage interface{}) *MockClient_GetPipelineState_Call {
	return &MockClient_GetPipelineState_Call{Call: _e.mock.On("GetPipelineState", wsId, stage)}
}

func (_c *MockClient_GetPipelineState_Call) Run(run func(wsId int, stage string)) *MockClient_GetPipelineState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetPipelineState_Call) Return(vs []api.PipelineStatus, err error) *MockClient_GetPipelineState_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockClient_GetPipelineState_Call) RunAndReturn(run func(wsId int, stage string) ([]api.PipelineStatus, error)) *MockClient_GetPipelineState_Call {
	_c.Call.Return(run)
	return _c
}

// StartPipelineStage provides a mock function for the type MockClient
func (_mock *MockClient) StartPipelineStage(wsId int, profile string, stage string) error {
	ret := _mock.Called(wsId, profile, stage)

	if len(ret) == 0 {
		panic("no return value specified for StartPipelineStage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, string, string) error); ok {
		r0 = returnFunc(wsId, profile, stage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_StartPipelineStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartPipelineStage'
type MockClient_StartPipelineStage_Call struct {
	*mock.Call
}

// StartPipelineStage is a helper method to define mock.On call
//   - wsId int
//   - profile string
//   - stage string
func (_e *MockClient_Expecter) StartPipelineStage(wsId interface{}, profile interface{}, stage interface{}) *MockClient_StartPipelineStage_Call {
	return &MockClient_StartPipelineStage_Call{Call: _e.mock.On("StartPipelineStage", wsId, profile, stage)}
}

func (_c *MockClient_StartPipelineStage_Call) Run(run func(wsId int, profile string, stage string)) *MockClient_StartPipelineStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_StartPipelineStage_Call) Return(err error) *MockClient_StartPipelineStage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_StartPipelineStage_Call) RunAndReturn(run func(wsId int, profile string, stage string) error) *MockClient_StartPipelineStage_Call {
	_c.Call.Return(run)
	return _c
}

// StreamLogs provides a mock function for the type MockClient
func (_mock *MockClient) StreamLogs(ctx context.Context, apiUrl string, wsId int, stage string, step int, w io.Writer) error {
	ret := _mock.Called(ctx, apiUrl, wsId, stage, step, w)

	if len(ret) == 0 {
		panic("no return value specified for StreamLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, string, int, io.Writer) error); ok {
		r0 = returnFunc(ctx, apiUrl, wsId, stage, step, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_StreamLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamLogs'
type MockClient_StreamLogs_Call struct {
	*mock.Call
}

// StreamLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - apiUrl string
//   - wsId int
//   - stage string
//   - step int
//   - w io.Writer
func (_e *MockClient_Expecter) StreamLogs(ctx interface{}, apiUrl interface{}, wsId interface{}, stage interface{}, step interface{}, w interface{}) *MockClient_StreamLogs_Call {
	return &MockClient_StreamLogs_Call{Call: _e.mock.On("StreamLogs", ctx, apiUrl, wsId, stage, step, w)}
}

func (_c *MockClient_StreamLogs_Call) Run(run func(ctx context.Context, apiUrl string, wsId int, stage string, step int, w io.Writer)) *MockClient_StreamLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 io.Writer
		if args[5] != nil {
			arg5 = args[5].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_StreamLogs_Call) Return(err error) *MockClient_StreamLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_StreamLogs_Call) RunAndReturn(run func(ctx context.Context, apiUrl string, wsId int, stage string, step int, w io.Writer) error) *MockClient_StreamLogs_Call {
	_c.Call.Return(run)
	return _c
}
