/*
Codesphere Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MetadataGetDatacenters200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetadataGetDatacenters200ResponseInner{}

// MetadataGetDatacenters200ResponseInner struct for MetadataGetDatacenters200ResponseInner
type MetadataGetDatacenters200ResponseInner struct {
	Id          float32 `json:"id"`
	Name        string  `json:"name"`
	City        string  `json:"city"`
	CountryCode string  `json:"countryCode"`
}

type _MetadataGetDatacenters200ResponseInner MetadataGetDatacenters200ResponseInner

// NewMetadataGetDatacenters200ResponseInner instantiates a new MetadataGetDatacenters200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetadataGetDatacenters200ResponseInner(id float32, name string, city string, countryCode string) *MetadataGetDatacenters200ResponseInner {
	this := MetadataGetDatacenters200ResponseInner{}
	this.Id = id
	this.Name = name
	this.City = city
	this.CountryCode = countryCode
	return &this
}

// NewMetadataGetDatacenters200ResponseInnerWithDefaults instantiates a new MetadataGetDatacenters200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetadataGetDatacenters200ResponseInnerWithDefaults() *MetadataGetDatacenters200ResponseInner {
	this := MetadataGetDatacenters200ResponseInner{}
	return &this
}

// GetId returns the Id field value
func (o *MetadataGetDatacenters200ResponseInner) GetId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MetadataGetDatacenters200ResponseInner) GetIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MetadataGetDatacenters200ResponseInner) SetId(v float32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *MetadataGetDatacenters200ResponseInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MetadataGetDatacenters200ResponseInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MetadataGetDatacenters200ResponseInner) SetName(v string) {
	o.Name = v
}

// GetCity returns the City field value
func (o *MetadataGetDatacenters200ResponseInner) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *MetadataGetDatacenters200ResponseInner) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *MetadataGetDatacenters200ResponseInner) SetCity(v string) {
	o.City = v
}

// GetCountryCode returns the CountryCode field value
func (o *MetadataGetDatacenters200ResponseInner) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *MetadataGetDatacenters200ResponseInner) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *MetadataGetDatacenters200ResponseInner) SetCountryCode(v string) {
	o.CountryCode = v
}

func (o MetadataGetDatacenters200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetadataGetDatacenters200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["city"] = o.City
	toSerialize["countryCode"] = o.CountryCode
	return toSerialize, nil
}

func (o *MetadataGetDatacenters200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"city",
		"countryCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMetadataGetDatacenters200ResponseInner := _MetadataGetDatacenters200ResponseInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMetadataGetDatacenters200ResponseInner)

	if err != nil {
		return err
	}

	*o = MetadataGetDatacenters200ResponseInner(varMetadataGetDatacenters200ResponseInner)

	return err
}

type NullableMetadataGetDatacenters200ResponseInner struct {
	value *MetadataGetDatacenters200ResponseInner
	isSet bool
}

func (v NullableMetadataGetDatacenters200ResponseInner) Get() *MetadataGetDatacenters200ResponseInner {
	return v.value
}

func (v *NullableMetadataGetDatacenters200ResponseInner) Set(val *MetadataGetDatacenters200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMetadataGetDatacenters200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMetadataGetDatacenters200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetadataGetDatacenters200ResponseInner(val *MetadataGetDatacenters200ResponseInner) *NullableMetadataGetDatacenters200ResponseInner {
	return &NullableMetadataGetDatacenters200ResponseInner{value: val, isSet: true}
}

func (v NullableMetadataGetDatacenters200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetadataGetDatacenters200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
