// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	mock "github.com/stretchr/testify/mock"
	"time"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DeleteWorkspace provides a mock function for the type MockClient
func (_mock *MockClient) DeleteWorkspace(wsId int) error {
	ret := _mock.Called(wsId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkspace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(wsId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkspace'
type MockClient_DeleteWorkspace_Call struct {
	*mock.Call
}

// DeleteWorkspace is a helper method to define mock.On call
//   - wsId int
func (_e *MockClient_Expecter) DeleteWorkspace(wsId interface{}) *MockClient_DeleteWorkspace_Call {
	return &MockClient_DeleteWorkspace_Call{Call: _e.mock.On("DeleteWorkspace", wsId)}
}

func (_c *MockClient_DeleteWorkspace_Call) Run(run func(wsId int)) *MockClient_DeleteWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_DeleteWorkspace_Call) Return(err error) *MockClient_DeleteWorkspace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteWorkspace_Call) RunAndReturn(run func(wsId int) error) *MockClient_DeleteWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// DeployLandscape provides a mock function for the type MockClient
func (_mock *MockClient) DeployLandscape(wsId int, profile string) error {
	ret := _mock.Called(wsId, profile)

	if len(ret) == 0 {
		panic("no return value specified for DeployLandscape")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = returnFunc(wsId, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeployLandscape_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeployLandscape'
type MockClient_DeployLandscape_Call struct {
	*mock.Call
}

// DeployLandscape is a helper method to define mock.On call
//   - wsId int
//   - profile string
func (_e *MockClient_Expecter) DeployLandscape(wsId interface{}, profile interface{}) *MockClient_DeployLandscape_Call {
	return &MockClient_DeployLandscape_Call{Call: _e.mock.On("DeployLandscape", wsId, profile)}
}

func (_c *MockClient_DeployLandscape_Call) Run(run func(wsId int, profile string)) *MockClient_DeployLandscape_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_DeployLandscape_Call) Return(err error) *MockClient_DeployLandscape_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeployLandscape_Call) RunAndReturn(run func(wsId int, profile string) error) *MockClient_DeployLandscape_Call {
	_c.Call.Return(run)
	return _c
}

// DeployWorkspace provides a mock function for the type MockClient
func (_mock *MockClient) DeployWorkspace(args DeployWorkspaceArgs) (*Workspace, error) {
	ret := _mock.Called(args)

	if len(ret) == 0 {
		panic("no return value specified for DeployWorkspace")
	}

	var r0 *Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(DeployWorkspaceArgs) (*Workspace, error)); ok {
		return returnFunc(args)
	}
	if returnFunc, ok := ret.Get(0).(func(DeployWorkspaceArgs) *Workspace); ok {
		r0 = returnFunc(args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Workspace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(DeployWorkspaceArgs) error); ok {
		r1 = returnFunc(args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_DeployWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeployWorkspace'
type MockClient_DeployWorkspace_Call struct {
	*mock.Call
}

// DeployWorkspace is a helper method to define mock.On call
//   - args DeployWorkspaceArgs
func (_e *MockClient_Expecter) DeployWorkspace(args interface{}) *MockClient_DeployWorkspace_Call {
	return &MockClient_DeployWorkspace_Call{Call: _e.mock.On("DeployWorkspace", args)}
}

func (_c *MockClient_DeployWorkspace_Call) Run(run func(args DeployWorkspaceArgs)) *MockClient_DeployWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 DeployWorkspaceArgs
		if args[0] != nil {
			arg0 = args[0].(DeployWorkspaceArgs)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_DeployWorkspace_Call) Return(v *Workspace, err error) *MockClient_DeployWorkspace_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_DeployWorkspace_Call) RunAndReturn(run func(args DeployWorkspaceArgs) (*Workspace, error)) *MockClient_DeployWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// ExecCommand provides a mock function for the type MockClient
func (_mock *MockClient) ExecCommand(workspaceId int, command string, workdir string, env map[string]string) (string, string, error) {
	ret := _mock.Called(workspaceId, command, workdir, env)

	if len(ret) == 0 {
		panic("no return value specified for ExecCommand")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(int, string, string, map[string]string) (string, string, error)); ok {
		return returnFunc(workspaceId, command, workdir, env)
	}
	if returnFunc, ok := ret.Get(0).(func(int, string, string, map[string]string) string); ok {
		r0 = returnFunc(workspaceId, command, workdir, env)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(int, string, string, map[string]string) string); ok {
		r1 = returnFunc(workspaceId, command, workdir, env)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(int, string, string, map[string]string) error); ok {
		r2 = returnFunc(workspaceId, command, workdir, env)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockClient_ExecCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecCommand'
type MockClient_ExecCommand_Call struct {
	*mock.Call
}

// ExecCommand is a helper method to define mock.On call
//   - workspaceId int
//   - command string
//   - workdir string
//   - env map[string]string
func (_e *MockClient_Expecter) ExecCommand(workspaceId interface{}, command interface{}, workdir interface{}, env interface{}) *MockClient_ExecCommand_Call {
	return &MockClient_ExecCommand_Call{Call: _e.mock.On("ExecCommand", workspaceId, command, workdir, env)}
}

func (_c *MockClient_ExecCommand_Call) Run(run func(workspaceId int, command string, workdir string, env map[string]string)) *MockClient_ExecCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]string
		if args[3] != nil {
			arg3 = args[3].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_ExecCommand_Call) Return(s string, s1 string, err error) *MockClient_ExecCommand_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *MockClient_ExecCommand_Call) RunAndReturn(run func(workspaceId int, command string, workdir string, env map[string]string) (string, string, error)) *MockClient_ExecCommand_Call {
	_c.Call.Return(run)
	return _c
}

// GetPipelineState provides a mock function for the type MockClient
func (_mock *MockClient) GetPipelineState(wsId int, stage string) ([]PipelineStatus, error) {
	ret := _mock.Called(wsId, stage)

	if len(ret) == 0 {
		panic("no return value specified for GetPipelineState")
	}

	var r0 []PipelineStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, string) ([]PipelineStatus, error)); ok {
		return returnFunc(wsId, stage)
	}
	if returnFunc, ok := ret.Get(0).(func(int, string) []PipelineStatus); ok {
		r0 = returnFunc(wsId, stage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PipelineStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = returnFunc(wsId, stage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetPipelineState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPipelineState'
type MockClient_GetPipelineState_Call struct {
	*mock.Call
}

// GetPipelineState is a helper method to define mock.On call
//   - wsId int
//   - stage string
func (_e *MockClient_Expecter) GetPipelineState(wsId interface{}, stage interface{}) *MockClient_GetPipelineState_Call {
	return &MockClient_GetPipelineState_Call{Call: _e.mock.On("GetPipelineState", wsId, stage)}
}

func (_c *MockClient_GetPipelineState_Call) Run(run func(wsId int, stage string)) *MockClient_GetPipelineState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetPipelineState_Call) Return(vs []PipelineStatus, err error) *MockClient_GetPipelineState_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockClient_GetPipelineState_Call) RunAndReturn(run func(wsId int, stage string) ([]PipelineStatus, error)) *MockClient_GetPipelineState_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkspace provides a mock function for the type MockClient
func (_mock *MockClient) GetWorkspace(workspaceId int) (Workspace, error) {
	ret := _mock.Called(workspaceId)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspace")
	}

	var r0 Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (Workspace, error)); ok {
		return returnFunc(workspaceId)
	}
	if returnFunc, ok := ret.Get(0).(func(int) Workspace); ok {
		r0 = returnFunc(workspaceId)
	} else {
		r0 = ret.Get(0).(Workspace)
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(workspaceId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkspace'
type MockClient_GetWorkspace_Call struct {
	*mock.Call
}

// GetWorkspace is a helper method to define mock.On call
//   - workspaceId int
func (_e *MockClient_Expecter) GetWorkspace(workspaceId interface{}) *MockClient_GetWorkspace_Call {
	return &MockClient_GetWorkspace_Call{Call: _e.mock.On("GetWorkspace", workspaceId)}
}

func (_c *MockClient_GetWorkspace_Call) Run(run func(workspaceId int)) *MockClient_GetWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetWorkspace_Call) Return(v Workspace, err error) *MockClient_GetWorkspace_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_GetWorkspace_Call) RunAndReturn(run func(workspaceId int) (Workspace, error)) *MockClient_GetWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// GitPull provides a mock function for the type MockClient
func (_mock *MockClient) GitPull(wsId int, remote string, branch string) error {
	ret := _mock.Called(wsId, remote, branch)

	if len(ret) == 0 {
		panic("no return value specified for GitPull")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, string, string) error); ok {
		r0 = returnFunc(wsId, remote, branch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_GitPull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GitPull'
type MockClient_GitPull_Call struct {
	*mock.Call
}

// GitPull is a helper method to define mock.On call
//   - wsId int
//   - remote string
//   - branch string
func (_e *MockClient_Expecter) GitPull(wsId interface{}, remote interface{}, branch interface{}) *MockClient_GitPull_Call {
	return &MockClient_GitPull_Call{Call: _e.mock.On("GitPull", wsId, remote, branch)}
}

func (_c *MockClient_GitPull_Call) Run(run func(wsId int, remote string, branch string)) *MockClient_GitPull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_GitPull_Call) Return(err error) *MockClient_GitPull_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_GitPull_Call) RunAndReturn(run func(wsId int, remote string, branch string) error) *MockClient_GitPull_Call {
	_c.Call.Return(run)
	return _c
}

// ListBaseimages provides a mock function for the type MockClient
func (_mock *MockClient) ListBaseimages() ([]Baseimage, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListBaseimages")
	}

	var r0 []Baseimage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]Baseimage, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []Baseimage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Baseimage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListBaseimages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBaseimages'
type MockClient_ListBaseimages_Call struct {
	*mock.Call
}

// ListBaseimages is a helper method to define mock.On call
func (_e *MockClient_Expecter) ListBaseimages() *MockClient_ListBaseimages_Call {
	return &MockClient_ListBaseimages_Call{Call: _e.mock.On("ListBaseimages")}
}

func (_c *MockClient_ListBaseimages_Call) Run(run func()) *MockClient_ListBaseimages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_ListBaseimages_Call) Return(vs []Baseimage, err error) *MockClient_ListBaseimages_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockClient_ListBaseimages_Call) RunAndReturn(run func() ([]Baseimage, error)) *MockClient_ListBaseimages_Call {
	_c.Call.Return(run)
	return _c
}

// ListTeams provides a mock function for the type MockClient
func (_mock *MockClient) ListTeams() ([]Team, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListTeams")
	}

	var r0 []Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]Team, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []Team); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTeams'
type MockClient_ListTeams_Call struct {
	*mock.Call
}

// ListTeams is a helper method to define mock.On call
func (_e *MockClient_Expecter) ListTeams() *MockClient_ListTeams_Call {
	return &MockClient_ListTeams_Call{Call: _e.mock.On("ListTeams")}
}

func (_c *MockClient_ListTeams_Call) Run(run func()) *MockClient_ListTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_ListTeams_Call) Return(vs []Team, err error) *MockClient_ListTeams_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockClient_ListTeams_Call) RunAndReturn(run func() ([]Team, error)) *MockClient_ListTeams_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkspacePlans provides a mock function for the type MockClient
func (_mock *MockClient) ListWorkspacePlans() ([]WorkspacePlan, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListWorkspacePlans")
	}

	var r0 []WorkspacePlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]WorkspacePlan, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []WorkspacePlan); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]WorkspacePlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListWorkspacePlans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkspacePlans'
type MockClient_ListWorkspacePlans_Call struct {
	*mock.Call
}

// ListWorkspacePlans is a helper method to define mock.On call
func (_e *MockClient_Expecter) ListWorkspacePlans() *MockClient_ListWorkspacePlans_Call {
	return &MockClient_ListWorkspacePlans_Call{Call: _e.mock.On("ListWorkspacePlans")}
}

func (_c *MockClient_ListWorkspacePlans_Call) Run(run func()) *MockClient_ListWorkspacePlans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_ListWorkspacePlans_Call) Return(vs []WorkspacePlan, err error) *MockClient_ListWorkspacePlans_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockClient_ListWorkspacePlans_Call) RunAndReturn(run func() ([]WorkspacePlan, error)) *MockClient_ListWorkspacePlans_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkspaces provides a mock function for the type MockClient
func (_mock *MockClient) ListWorkspaces(teamId int) ([]Workspace, error) {
	ret := _mock.Called(teamId)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkspaces")
	}

	var r0 []Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]Workspace, error)); ok {
		return returnFunc(teamId)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []Workspace); ok {
		r0 = returnFunc(teamId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Workspace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(teamId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListWorkspaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkspaces'
type MockClient_ListWorkspaces_Call struct {
	*mock.Call
}

// ListWorkspaces is a helper method to define mock.On call
//   - teamId int
func (_e *MockClient_Expecter) ListWorkspaces(teamId interface{}) *MockClient_ListWorkspaces_Call {
	return &MockClient_ListWorkspaces_Call{Call: _e.mock.On("ListWorkspaces", teamId)}
}

func (_c *MockClient_ListWorkspaces_Call) Run(run func(teamId int)) *MockClient_ListWorkspaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_ListWorkspaces_Call) Return(vs []Workspace, err error) *MockClient_ListWorkspaces_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockClient_ListWorkspaces_Call) RunAndReturn(run func(teamId int) ([]Workspace, error)) *MockClient_ListWorkspaces_Call {
	_c.Call.Return(run)
	return _c
}

// ScaleLandscapeServices provides a mock function for the type MockClient
func (_mock *MockClient) ScaleLandscapeServices(wsId int, services map[string]int) error {
	ret := _mock.Called(wsId, services)

	if len(ret) == 0 {
		panic("no return value specified for ScaleLandscapeServices")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, map[string]int) error); ok {
		r0 = returnFunc(wsId, services)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_ScaleLandscapeServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScaleLandscapeServices'
type MockClient_ScaleLandscapeServices_Call struct {
	*mock.Call
}

// ScaleLandscapeServices is a helper method to define mock.On call
//   - wsId int
//   - services map[string]int
func (_e *MockClient_Expecter) ScaleLandscapeServices(wsId interface{}, services interface{}) *MockClient_ScaleLandscapeServices_Call {
	return &MockClient_ScaleLandscapeServices_Call{Call: _e.mock.On("ScaleLandscapeServices", wsId, services)}
}

func (_c *MockClient_ScaleLandscapeServices_Call) Run(run func(wsId int, services map[string]int)) *MockClient_ScaleLandscapeServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 map[string]int
		if args[1] != nil {
			arg1 = args[1].(map[string]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ScaleLandscapeServices_Call) Return(err error) *MockClient_ScaleLandscapeServices_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_ScaleLandscapeServices_Call) RunAndReturn(run func(wsId int, services map[string]int) error) *MockClient_ScaleLandscapeServices_Call {
	_c.Call.Return(run)
	return _c
}

// ScaleWorkspace provides a mock function for the type MockClient
func (_mock *MockClient) ScaleWorkspace(wsId int, replicas int) error {
	ret := _mock.Called(wsId, replicas)

	if len(ret) == 0 {
		panic("no return value specified for ScaleWorkspace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = returnFunc(wsId, replicas)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_ScaleWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScaleWorkspace'
type MockClient_ScaleWorkspace_Call struct {
	*mock.Call
}

// ScaleWorkspace is a helper method to define mock.On call
//   - wsId int
//   - replicas int
func (_e *MockClient_Expecter) ScaleWorkspace(wsId interface{}, replicas interface{}) *MockClient_ScaleWorkspace_Call {
	return &MockClient_ScaleWorkspace_Call{Call: _e.mock.On("ScaleWorkspace", wsId, replicas)}
}

func (_c *MockClient_ScaleWorkspace_Call) Run(run func(wsId int, replicas int)) *MockClient_ScaleWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ScaleWorkspace_Call) Return(err error) *MockClient_ScaleWorkspace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_ScaleWorkspace_Call) RunAndReturn(run func(wsId int, replicas int) error) *MockClient_ScaleWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// SetEnvVarOnWorkspace provides a mock function for the type MockClient
func (_mock *MockClient) SetEnvVarOnWorkspace(workspaceId int, vars map[string]string) error {
	ret := _mock.Called(workspaceId, vars)

	if len(ret) == 0 {
		panic("no return value specified for SetEnvVarOnWorkspace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, map[string]string) error); ok {
		r0 = returnFunc(workspaceId, vars)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_SetEnvVarOnWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEnvVarOnWorkspace'
type MockClient_SetEnvVarOnWorkspace_Call struct {
	*mock.Call
}

// SetEnvVarOnWorkspace is a helper method to define mock.On call
//   - workspaceId int
//   - vars map[string]string
func (_e *MockClient_Expecter) SetEnvVarOnWorkspace(workspaceId interface{}, vars interface{}) *MockClient_SetEnvVarOnWorkspace_Call {
	return &MockClient_SetEnvVarOnWorkspace_Call{Call: _e.mock.On("SetEnvVarOnWorkspace", workspaceId, vars)}
}

func (_c *MockClient_SetEnvVarOnWorkspace_Call) Run(run func(workspaceId int, vars map[string]string)) *MockClient_SetEnvVarOnWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_SetEnvVarOnWorkspace_Call) Return(err error) *MockClient_SetEnvVarOnWorkspace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_SetEnvVarOnWorkspace_Call) RunAndReturn(run func(workspaceId int, vars map[string]string) error) *MockClient_SetEnvVarOnWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// StartPipelineStage provides a mock function for the type MockClient
func (_mock *MockClient) StartPipelineStage(wsId int, profile string, stage string) error {
	ret := _mock.Called(wsId, profile, stage)

	if len(ret) == 0 {
		panic("no return value specified for StartPipelineStage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, string, string) error); ok {
		r0 = returnFunc(wsId, profile, stage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_StartPipelineStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartPipelineStage'
type MockClient_StartPipelineStage_Call struct {
	*mock.Call
}

// StartPipelineStage is a helper method to define mock.On call
//   - wsId int
//   - profile string
//   - stage string
func (_e *MockClient_Expecter) StartPipelineStage(wsId interface{}, profile interface{}, stage interface{}) *MockClient_StartPipelineStage_Call {
	return &MockClient_StartPipelineStage_Call{Call: _e.mock.On("StartPipelineStage", wsId, profile, stage)}
}

func (_c *MockClient_StartPipelineStage_Call) Run(run func(wsId int, profile string, stage string)) *MockClient_StartPipelineStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_StartPipelineStage_Call) Return(err error) *MockClient_StartPipelineStage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_StartPipelineStage_Call) RunAndReturn(run func(wsId int, profile string, stage string) error) *MockClient_StartPipelineStage_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForWorkspaceRunning provides a mock function for the type MockClient
func (_mock *MockClient) WaitForWorkspaceRunning(workspace *Workspace, timeout time.Duration) error {
	ret := _mock.Called(workspace, timeout)

	if len(ret) == 0 {
		panic("no return value specified for WaitForWorkspaceRunning")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Workspace, time.Duration) error); ok {
		r0 = returnFunc(workspace, timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_WaitForWorkspaceRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForWorkspaceRunning'
type MockClient_WaitForWorkspaceRunning_Call struct {
	*mock.Call
}

// WaitForWorkspaceRunning is a helper method to define mock.On call
//   - workspace *Workspace
//   - timeout time.Duration
func (_e *MockClient_Expecter) WaitForWorkspaceRunning(workspace interface{}, timeout interface{}) *MockClient_WaitForWorkspaceRunning_Call {
	return &MockClient_WaitForWorkspaceRunning_Call{Call: _e.mock.On("WaitForWorkspaceRunning", workspace, timeout)}
}

func (_c *MockClient_WaitForWorkspaceRunning_Call) Run(run func(workspace *Workspace, timeout time.Duration)) *MockClient_WaitForWorkspaceRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Workspace
		if args[0] != nil {
			arg0 = args[0].(*Workspace)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_WaitForWorkspaceRunning_Call) Return(err error) *MockClient_WaitForWorkspaceRunning_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_WaitForWorkspaceRunning_Call) RunAndReturn(run func(workspace *Workspace, timeout time.Duration) error) *MockClient_WaitForWorkspaceRunning_Call {
	_c.Call.Return(run)
	return _c
}

// WakeUpWorkspace provides a mock function for the type MockClient
func (_mock *MockClient) WakeUpWorkspace(wsId int, token string, profile string, timeout time.Duration) error {
	ret := _mock.Called(wsId, token, profile, timeout)

	if len(ret) == 0 {
		panic("no return value specified for WakeUpWorkspace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, string, string, time.Duration) error); ok {
		r0 = returnFunc(wsId, token, profile, timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_WakeUpWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WakeUpWorkspace'
type MockClient_WakeUpWorkspace_Call struct {
	*mock.Call
}

// WakeUpWorkspace is a helper method to define mock.On call
//   - wsId int
//   - token string
//   - profile string
//   - timeout time.Duration
func (_e *MockClient_Expecter) WakeUpWorkspace(wsId interface{}, token interface{}, profile interface{}, timeout interface{}) *MockClient_WakeUpWorkspace_Call {
	return &MockClient_WakeUpWorkspace_Call{Call: _e.mock.On("WakeUpWorkspace", wsId, token, profile, timeout)}
}

func (_c *MockClient_WakeUpWorkspace_Call) Run(run func(wsId int, token string, profile string, timeout time.Duration)) *MockClient_WakeUpWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_WakeUpWorkspace_Call) Return(err error) *MockClient_WakeUpWorkspace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_WakeUpWorkspace_Call) RunAndReturn(run func(wsId int, token string, profile string, timeout time.Duration) error) *MockClient_WakeUpWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// WorkspaceStatus provides a mock function for the type MockClient
func (_mock *MockClient) WorkspaceStatus(workspaceId int) (*WorkspaceStatus, error) {
	ret := _mock.Called(workspaceId)

	if len(ret) == 0 {
		panic("no return value specified for WorkspaceStatus")
	}

	var r0 *WorkspaceStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*WorkspaceStatus, error)); ok {
		return returnFunc(workspaceId)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *WorkspaceStatus); ok {
		r0 = returnFunc(workspaceId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*WorkspaceStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(workspaceId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_WorkspaceStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorkspaceStatus'
type MockClient_WorkspaceStatus_Call struct {
	*mock.Call
}

// WorkspaceStatus is a helper method to define mock.On call
//   - workspaceId int
func (_e *MockClient_Expecter) WorkspaceStatus(workspaceId interface{}) *MockClient_WorkspaceStatus_Call {
	return &MockClient_WorkspaceStatus_Call{Call: _e.mock.On("WorkspaceStatus", workspaceId)}
}

func (_c *MockClient_WorkspaceStatus_Call) Run(run func(workspaceId int)) *MockClient_WorkspaceStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_WorkspaceStatus_Call) Return(v *WorkspaceStatus, err error) *MockClient_WorkspaceStatus_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_WorkspaceStatus_Call) RunAndReturn(run func(workspaceId int) (*WorkspaceStatus, error)) *MockClient_WorkspaceStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTime creates a new instance of MockTime. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTime(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTime {
	mock := &MockTime{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTime is an autogenerated mock type for the Time type
type MockTime struct {
	mock.Mock
}

type MockTime_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTime) EXPECT() *MockTime_Expecter {
	return &MockTime_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type MockTime
func (_mock *MockTime) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockTime_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockTime_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockTime_Expecter) Now() *MockTime_Now_Call {
	return &MockTime_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *MockTime_Now_Call) Run(run func()) *MockTime_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTime_Now_Call) Return(time1 time.Time) *MockTime_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockTime_Now_Call) RunAndReturn(run func() time.Time) *MockTime_Now_Call {
	_c.Call.Return(run)
	return _c
}

// Sleep provides a mock function for the type MockTime
func (_mock *MockTime) Sleep(duration time.Duration) {
	_mock.Called(duration)
	return
}

// MockTime_Sleep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sleep'
type MockTime_Sleep_Call struct {
	*mock.Call
}

// Sleep is a helper method to define mock.On call
//   - duration time.Duration
func (_e *MockTime_Expecter) Sleep(duration interface{}) *MockTime_Sleep_Call {
	return &MockTime_Sleep_Call{Call: _e.mock.On("Sleep", duration)}
}

func (_c *MockTime_Sleep_Call) Run(run func(duration time.Duration)) *MockTime_Sleep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTime_Sleep_Call) Return() *MockTime_Sleep_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTime_Sleep_Call) RunAndReturn(run func(duration time.Duration)) *MockTime_Sleep_Call {
	_c.Run(run)
	return _c
}
