name: Generate, Tag & Release

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ github.ref }}
          fetch-tags: true
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: 'go.mod'

      - name: Tag
        run: hack/tag-release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack Notification on Failure
        if: ${{ failure() }}
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data '{
              "channel": "#team-oms-sdk",
              "icon_emoji": ":siren:",
              "text": "🚨 Release Job Failure 🚨\nRepository: ${{ github.repository }}\nBranch/Ref: `${{ github.ref }}`\nRun url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }' \
            ${{ secrets.PACKAGE_JOB_SLACK_WEBHOOK }}
